### ISSUE TITLE
Major security issue: index.html points at remote code

### ISSUE THREAD

**Issue by felixrieseberg** [standardnotes/desktop#10]
Excellent effort! However, it also introduces a _major_ security hole:

The Electron Desktop App simply loads an index.html which points at remote JavaScript. That's crazy dangerous - if that endpoint gets compromised, nothing keeps the attacker from running `rm -rf /` on every user's machine. 

I'm a member of the Electron maintainers group and fully realize that this is partly on us for not educating better. Remote code should never run with full privileges - consider using a `webview` instead, which can be sandboxed.

**Comment by mobitar** [comment]
Gotcha, easy fix, will get that out asap. We did this as a way to push out changes quicker since we were still making major improvements often.

**Comment by mobitar** [comment]
Fixed in latest release: https://github.com/standardnotes/desktop/releases/
