### ISSUE TITLE
Allow only one instance of App to run, if the second instance is launched, close it and bring the first instance to the front (feature request)

### ISSUE THREAD

**Issue by sanchoio** [standardnotes/desktop#102]
This feature request is about productivity. Let's imagine the situation when an average user has from 5 to 7 opened windows, he is switching between apps from time to time and occasionally makes some notes with Standard Notes. At the same time, user don't remember if they lauched Standard Notes during this session or not. At the present moment, every time the user has to make a note, they must view running applications, select SN (if running) or launch it (if not running). If the user launche the second instance of SN, he always gets an error and the second app is closed (so the action has neither sense nor benefit for the user. 

From my personal user experience, if the app I use daily doesn't have hide to system tray + launch minimized + global shortcut functionality, I try with Gnome Keyboard Settings add shortcut which launches the app and it designed to bring first instance upfront, it just brings it upfront and calmly quits. This way I have no need every time to search among other running apps the app I use frequently.
So if the app X isn't running yet and I start it with keyboard shortcut or launcher or terminal, it starts normally. If there's already an instance of the app X, it just brings focus to the already running instance and quit.

Summarizing, IMHO current behavior has no practical value for the regular user and can be easily substituted with more beneficial one.

![screenshot from 2017-10-11 23-35-44](https://user-images.githubusercontent.com/32115115/31480472-a07baaae-aee3-11e7-9d58-27f0d23cc507.png)

**Comment by mobitar** [comment]
Thanks for the feedback. I agree this would be helpful behavior. Though seemingly complex to build. I won't have the chance to get to it any time soon, but I'll leave it open to community contributions.

**Comment by mirsev** [comment]
What about a special lock file containing the process ID in app's directory? New instance just checks the presence of this file and, if it exists, sends a signal to the already running process and quits.

**Comment by mobitar** [comment]
That could work.

**Comment by sancho-one** [comment]
I guess there's a problem with cross-platform realization of it as this
issue isn't handled by this app directly but by AppImage, in my
understanding.

**Comment by mobitar** [comment]
But if the user can't find the other instance, then now they'll have a ghost instance + an autoclosing instance.

**Comment by Marsup** [comment]
@mobitar you have everything available to do it in theory:
- https://github.com/electron/electron/blob/master/docs/api/app.md#apprequestsingleinstancelock
- https://github.com/electron/electron/blob/master/docs/api/app.md#appfocus

The snippet in `requestSingleInstanceLock` is exactly what you want.

**Comment by mobitar** [comment]
Interesting, that could work. Not sure it's prevalent enough to prioritize but I think we should add this in at some point.

**Comment by Marsup** [comment]
Why close this ? You don't intend to do it ?

**Comment by mobitar** [comment]
Closed about 100 issues. Only kept things I expect to actually work on in the next year. I still have this in mind. It's just not prioritized in the top 20.

**Comment by virtuallyvlad** [comment]
Implemented with https://github.com/standardnotes/desktop/pull/339 and https://github.com/standardnotes/desktop/pull/359
