### ISSUE TITLE
Minimal markdown: # symbol inside ``` 

### ISSUE THREAD

**Issue by sancho-one** [standardnotes/desktop#104]
Parsing error: # shouldn't be highlighted as header. See screenshot:

![screenshot from 2017-10-12 23-31-09](https://user-images.githubusercontent.com/32115115/31530377-a6a9abde-afa5-11e7-878d-dc8e3b6cd962.png)

**Comment by mobitar** [comment]
Thanks, transferred here: https://github.com/sn-extensions/minimal-markdown-editor/issues/1
