### ISSUE TITLE
Clicking a URL link in the preview window of the Advanced Markdown editor borkes the UI

### ISSUE THREAD

**Issue by bearMountain** [standardnotes/desktop#106]
**Setup:**
- Run Standard Notes from the Desktop App (OSX)
- Install the Advanced Markdown editor
- Create a note with a URL link: `[A Website](www.google.com)`
- In the preview section of the Advanced Markdown editor, click on the link

**Current Behavior:**
- After clicking the link, the link was not opened up in a web browser
- After a few seconds, the whole editor screen went white 
- (my guess is that the electron app somehow tried to load the url in app, and then the screen goes white once that load fails?)

**Expected Behavior:**
- The link would be opened in your default web browser

**Context:**
- When clicking on the link, if you use a CMD+Click, it actually will open up the link in your default web browser
- When the main editing window gets borked, you can change the editor mode to plain and then back to Advanced Markdown to restore the viewing of the note

**Comment by bearMountain** [comment]
<img width="360" alt="screen shot 2017-10-25 at 10 37 48 pm" src="https://user-images.githubusercontent.com/1703113/32032452-4245965a-b9d5-11e7-9640-3368630a66fa.png">
Borked my editor menu as well.

**Comment by mobitar** [comment]
Good catch. Will take a look at this. I'm more concerned about what happened with the editor menu. Does it still look like this? What if you quit the app and re-open it?

**Comment by mobitar** [comment]
Ok, the link clicking issue has been fixed. Please get back to me about the menu issue.
