### ISSUE TITLE
2.0.2 - issue with views/editors (blank)

### ISSUE THREAD

**Issue by luckman212** [standardnotes/desktop#109]
Seems to be a major issue with 2.0.2 on Mac!

With the "Folders" extension enabled, the sidebar is not rendered at all:
![image](https://user-images.githubusercontent.com/1992842/32416546-d2ebef92-c218-11e7-84c3-734b679c7765.png)

Also, any external editor (does not affect the "System / Plain") causes the note area to be blank as well.

I have tried logging out / logging back in as well as using the "Clear Cache and Reload" menu item...

**Comment by mobitar** [comment]
Sorry, looks like the extensions server was overloaded. Please try again now.

**Comment by mobitar** [comment]
Actually give me one sec..

**Comment by mobitar** [comment]
Ok, should be good to go. I upgraded the server as well to ease the pressure.

**Comment by luckman212** [comment]
Yep, all good now, thanks. Does this mean though that SN depends on an external server to run? I never knew that - thought it worked fine "offline".

**Comment by mobitar** [comment]
The extensions (editors, components, themes) are hosted, which means they require a connection to download every app session. Aside from the extensions, the core app functions totally offline.

Re the hosted extensions, this isn't their final form. Definitely plan to improve this infrastructure to remove dependence on our servers.

**Comment by luckman212** [comment]
Yes I wasn't fully aware of that. Seems definitely like a critical change to make at some point if you want to fulfill the _"100 year notes app"_ promise on the homepage.
