### ISSUE TITLE
Going to markdown preview and back to editing mode doesn't place the text input back into original location.

### ISSUE THREAD

**Issue by dalan-stripe** [standardnotes/desktop#11]
Was expecting that I could be typing a note in markdown, use CMD + M to preview the note being rendered in markdown and then CMD + M again to continue typing, but the text cursor I think is reset to some other input. 

This is very subjective, but _It feels_ like this isn't the correct UX to have. I should be able to switch quickly and then just continue typing where I last left off.

~Literally unusuable~, just kidding, I just discovered you guys from HN and it's always amazing to find great simple tools like this with a public github repo. Thank you for such great work. 👏

**Comment by mobitar** [comment]
Good catch, will get a fix out for this asap. Markdown might actually be refactored into an extension, but that's another issue.

**Comment by mobitar** [comment]
Fixed
