### ISSUE TITLE
Remember menu bar visibility setting

### ISSUE THREAD

**Issue by lokesh-krishna** [standardnotes/desktop#111]
Presently, the menu bar is visible by default and even if toggled to hide, it is still visible the next time the app is opened. Would be nice if it remembered the setting picked the last time and maintained that state until toggled again.

**Comment by martinsvoboda1101** [comment]
Any progress on this? It's kinda annoying having to hide the menu every time the app starts.

**Comment by mobitar** [comment]
This only happens if you're using the app without an account. Which I don't fully recommend as a safe practice. How are you creating backups of your data on an automatic basis in a safe location?

**Comment by martinsvoboda1101** [comment]
You mean StandardNotes account? I do have that, and I do have automatic backups enabled.

My client version is 2.2.0, and I'm on Linux, if that helps.

**Comment by mobitar** [comment]
Ohh I see. You're talking about the Windows menu bar. Thought you were talking about the Account menu. Haven't looked into this yet though, but will keep an eye out on it for a future update.
