### ISSUE TITLE
Standardized date and time backup name

### ISSUE THREAD

**Issue by daylightbrightledlight** [standardnotes/desktop#112]
I propose that Standard Notes should used the International Standard [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) date and time notation for the backup name. Currently the backup names look like the following example:

Current name: `Mon Nov 13 2017 21-04-41 GMT-0500 (EST).txt`

The current naming scheme can make it very difficult to manage the order of backups. I propose using the International Standard [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) as the name of the backup instead. This standard is commonly used for anything long-lasting, from communication protocols to file specifications. The following would be an example:

Proposed name: `2017-11-13T210441-0500.txt`

If a condensed version is necessary, the following combined date and time in UTC can be used instead:

Alternate name: `20171114T020441Z.txt`

I also think that adopting the proposed notation will also make the Standard Notes look good, since it would then be using an International Standard and will adhere to the [Longevity Statement](https://standardnotes.org/longevity).

**Comment by daylightbrightledlight** [comment]
@mobitar You're right. However I think something like `2017-11-13 at 210441-0500.txt` is more readable with many similarly-named backups because they would be ordered properly in a directory with many backups.

I feel like this would be a more appropriate choice than the current method because the intended user for Standard Notes would prefer standards rather than a custom non-standard formatting. This was one of the reasons why I want to support your project.

**Comment by daylightbrightledlight** [comment]
Right now it looks like `Standard Notes Encrypted Backup - Mon Dec 03 2018 23-33-30 GMT-0500.txt`. I think this is bad because if I were to have a folder full of these backup files, they would not be properly ordered.

**Comment by mobitar** [comment]
This issue was referring to the automated backups, I believe. The ones managed via the Backups top level menu. In that case, it's using the proposed date format, so this issue is fixed. For manual backups, those are meant to be more human readable, but consistency wouldn't hurt I suppose.
