### ISSUE TITLE
task editor doesn't convert plaintext - [ ] to a checkbox when switching editor

### ISSUE THREAD

**Issue by wireddude** [standardnotes/desktop#113]
I made a text file with a bunch of tasks
`- [ ] item 1`

I installed the task editor plugin and switched to task mode. It didn't change any of my tasks to be checkboxes. any tips? Seems I can only may official checkboxes by using the textbox at the top.

**Comment by mobitar** [comment]
Right now it converts tasks based on 2 new lines, not one. I might just change this to 1 since that makes more sense.

So you need to have:

```
- Task 1

- Task 2
```

in your raw text, as opposed to 

```
- Task 1
- Task 2
```

**Comment by mobitar** [comment]
Ok, I've updated it to use a single new line instead of double. Just refresh to get the update.

**Comment by wireddude** [comment]
Thanks I was able to verify that including a blank line between tasks works. but on the webapp, and macos (2.0.4.1) it's not working properly when I don't include that blank line. When you say refresh, you mean remove the extension, and re-add it?

**Comment by mobitar** [comment]
You can just hit cmd+r to refresh the app. Or quit and re-open it. But now you need only one new line, not two.

So like this:
- Task 1
- Task 2
