### ISSUE TITLE
yeah yeah

### ISSUE THREAD

**Issue by ryderr** [standardnotes/desktop#116]
im aware this is not the original intent of the app.. but i think it would be VERY handy if there was a way to make standard checkbox to-do lists within the same framework, maybe it could be as simple as when you add a tag "to-do" it adds a select box next to each line.. and some simple CSS opacity (50%) on items that are checked? would be VERY handy!

**Comment by mobitar** [comment]
Hey @ryderr, check out the Task Editor: https://standardnotes.org/extensions/simple-task-editor
