### ISSUE TITLE
Progress counter on note import gives erroneous count.

### ISSUE THREAD

**Issue by kennethb22** [standardnotes/desktop#117]
See attached screen shot. The number of notes synced is greater than then number of the notes in the database: 2400/1294. It stopped around 3200/1294 notes and reported all notes had been successfully imported. Spot checked the notes and they do all appear to have imported correctly.

![2017-11-27 - standard notes sync](https://user-images.githubusercontent.com/19860067/33274664-b39e950c-d35e-11e7-944c-dea7d30b4a1e.png)

**Comment by mobitar** [comment]
Hmm..I assume you performed an import from file?

**Comment by mobitar** [comment]
Oops, sorry, you stated that in your title. I believe what happened here is since you imported data on top of an existing account, the counter counted the duplicates as unique items. I'll investigate this.

**Comment by mobitar** [comment]
Should be fixed in recent releases.
