### ISSUE TITLE
Offline database issue

### ISSUE THREAD

**Issue by jebeaudet** [standardnotes/desktop#12]
Hi

I'm getting a message saying "Please enable permissions for Standard Notes to use IndexedDB for offline mode" when using the app in Linux Mint Sarah (based on 16.04 Ubuntu LTS). It looks like I'm getting the message when the app is trying to save the note I'm writing. Even with this popup, the notes look like they're properly synced.

Thanks!

**Comment by mobitar** [comment]
Hmm that would be for offline storage. It will still sync to remote server. I tested on Linux a couple days ago, but let me test again shortly here and see if I can replicate the issue. Is it working in Chrome for you?

**Comment by jebeaudet** [comment]
Yes it's working fine in the chrome app.

**Comment by mobitar** [comment]
Ok thanks, will take a look at Linux app before the end of the week.

**Comment by justinshaffner** [comment]
I'm encountering the same error on Linux Ubuntu MATE.

**Comment by lasfter** [comment]
Same issue on Arch Linux running AwesomeWM

**Comment by mobitar** [comment]
Thanks all will get this checked out asap.

**Comment by csbenz** [comment]
Same on Windows

**Comment by mobitar** [comment]
Is anyone who is having this issue available to jump on Slack and quickly help me test an updated version? I can't replicate this error at all, so I can't be sure if I've fixed it :/

Slack link: https://slackin-ekhdyygaer.now.sh/

**Comment by jebeaudet** [comment]
Sure, be right there

**Comment by mobitar** [comment]
The fix for @jebeaudet was to restart the app/computer. If anyone could try restarting their computer and confirm if that fixes the issue, let me know.

**Comment by justinshaffner** [comment]
After restarting the computer, there's a new error:
`Offline database issue: undefined`

**Comment by mobitar** [comment]
Interesting. I added this new log instead of the old one that aims to print out the actual error. Strange that it's undefined. Can you confirm or deny this: when you are signed out, and you see this error, and you type a note, then reload the app (via Ctrl+R), is your note still there? If it is, then perhaps the error is benign. Let me know what you see.

**Comment by justinshaffner** [comment]
Regardless of how many times I sign our of the Desktop app, restart it, or the computer, this error remains. It pops up continuously every time the Desktop app tries to save. The app always starts with only one note, the initial New Note 1. When I create a new note, and refresh, the new note is gone with a fresh New Note 1. However, new notes created through the Desktop do appear in the Browser app, but no saved notes appear in the Desktop app, regardless of where they were created. Hope this helps!

**Comment by mobitar** [comment]
Ok, strange, sorry about this. Please use the web app until we can sort this out. Really wish I could replicate it :/

**Comment by yohanmishkin** [comment]
Seems to happen every time the application wants to sync.

![image](https://cloud.githubusercontent.com/assets/7291324/22118623/8a3ad602-de46-11e6-93a8-2a21cb81f99a.png)

**Comment by mobitar** [comment]
Ah ha! A log statement. This helps. So the DB instance is null. Now to figure out why that's the case.

**Comment by mobitar** [comment]
Can you take a screenshot of what you see in the inspector here:

<img width="527" alt="screen shot 2017-01-19 at 12 26 38 pm" src="https://cloud.githubusercontent.com/assets/3277844/22119801/957ab374-de42-11e6-88a7-7bc90860c278.png">

**Comment by yohanmishkin** [comment]
I don't see anything after restarting the application and refreshing IndexedDB. I'm currently signed into n3.standardnotes.org.

**Comment by mobitar** [comment]
You don't see anything as in the error is gone?

**Comment by yohanmishkin** [comment]
Apologies. The error remains, and there are no child nodes beneath the IndexedDB node in Storage inspector.

**Comment by mobitar** [comment]
Ok, I'm going to push out an update right now with more detailed logging. One min.

**Comment by mobitar** [comment]
Ok can you clear application cache, then reload, and let me know the details of the log statements you see. Should be pretty verbose.

**Comment by yohanmishkin** [comment]
Logs:

http://pastebin.com/A7iUJG7X

**Comment by mobitar** [comment]
Can you expand the nodes of the error object and target and see if you can find anything descriptive in there of what the issue is? Maybe some kind of error code or something?

**Comment by yohanmishkin** [comment]
![image](https://cloud.githubusercontent.com/assets/7291324/22120578/4844b1fc-de4e-11e6-8bce-9c71e406d88e.png)

**Comment by mobitar** [comment]
Do you have sufficient space on your hard drive? Some reports say that might be the issue (I doubt this many people have insufficient space on their disk though)

**Comment by yohanmishkin** [comment]
A few hundred GB available.

**Comment by mobitar** [comment]
Ok can you type this in your file explorer: `%appdata%. Then go Standard Notes/IndexedDB and then delete the contents in there. And tell me if that fixes the issue.

**Comment by mobitar** [comment]
I think I know what the issue is! Can you open your task manager and tell me how many Standard Notes processes you see?

**Comment by mobitar** [comment]
Ok so I'm pretty sure the issue is because of this: https://github.com/standardnotes/desktop/issues/14

That is, when you close the Window, the app doesn't quit, and therefore when you launch it again, it creates a new process, thus causing conflicts with IndexedDB access. This is why a restart fixed it for some people.

To fix, open up your task manager and quit all processes of Standard Notes. Then install the update here:
https://github.com/standardnotes/desktop/releases/tag/v0.1.2

If anyone runs this, please confirm your results.

**Comment by justinshaffner** [comment]
Here's what I'm seeing in the inspector:
```
Offline database issue: Eventbubbles: truecancelBubble: falsecancelable: truecomposed: falsecurrentTarget: nulldefaultPrevented: falseeventPhase: 0isTrusted: truepath: Array[0]returnValue: truesrcElement: IDBOpenDBRequesttarget: IDBOpenDBRequesttimeStamp: 3050.9700000000003type: "error"__proto__: EventAT_TARGET: 2BLUR: 8192BUBBLING_PHASE: 3CAPTURING_PHASE: 1CHANGE: 32768CLICK: 64DBLCLICK: 128DRAGDROP: 2048FOCUS: 4096KEYDOWN: 256KEYPRESS: 1024KEYUP: 512MOUSEDOWN: 1MOUSEDRAG: 32MOUSEMOVE: 16MOUSEOUT: 8MOUSEOVER: 4MOUSEUP: 2NONE: 0SELECT: 16384bubbles: (...)get bubbles: ()cancelBubble: (...)get cancelBubble: ()set cancelBubble: ()cancelable: (...)get cancelable: ()composed: (...)get composed: ()composedPath: composedPath()constructor: Event()currentTarget: (...)get currentTarget: ()defaultPrevented: (...)get defaultPrevented: ()eventPhase: (...)get eventPhase: ()initEvent: initEvent()path: (...)get path: ()preventDefault: preventDefault()returnValue: (...)get returnValue: ()set returnValue: ()srcElement: (...)get srcElement: ()stopImmediatePropagation: stopImmediatePropagation()stopPropagation: stopPropagation()target: (...)get target: ()timeStamp: (...)get timeStamp: ()type: (...)get type: ()Symbol(Symbol.toStringTag): "Event"__proto__: Object
Offline database issue: Event
Getting all items with db null
Uncaught TypeError: Cannot read property 'transaction' of null
Offline database issue: Event
Saving items with db null
Uncaught TypeError: Cannot read property 'transaction' of null
Offline database issue: Event
Saving items with db null
Uncaught TypeError: Cannot read property 'transaction' of null
Offline database issue: Event {isTrusted: true, type: "error", target: IDBOpenDBRequest, currentTarget: IDBOpenDBRequest, eventPhase: 2…}
Saving items with db null
Uncaught TypeError: Cannot read property 'transaction' of null
```

**Comment by yohanmishkin** [comment]
@mobitar it worked!

**Comment by mobitar** [comment]
Yesssss!

**Comment by justinshaffner** [comment]
Upgraded, and it works!

**Comment by mobitar** [comment]
:) Thank you all for your reports.
