### ISSUE TITLE
Note De-Duplicator

### ISSUE THREAD

**Issue by wireddude** [standardnotes/desktop#120]
I've imported and exported my backups several times and somewhere along the way I've created some duplicate entries. Is there a tool or a quick way to de-dupe entries?

**Comment by mobitar** [comment]
No I'm afraid not. Although this has been something on my mind.

You can also choose to delete all data via the Data Dashboard, then perform the import.

**Comment by mobitar** [comment]
The Batch Manager extension now does this.
