### ISSUE TITLE
Tags feature to list all notes with specific tags and separate option to delete it

### ISSUE THREAD

**Issue by rsau** [standardnotes/desktop#122]
For autocomplete tags, when clicking tag on a note, tag gets deleted. Is it possible to list all the notes which have that tag? 
For delete option a `X` might be provided when hovering over the tag. 

Thanks

**Comment by mobitar** [comment]
If you want to list all notes which have a tag, you should just select that tag from the tags list in the left-most panel. Not sure if I'm entirely following what you mean.

**Comment by rsau** [comment]
Deleting tag when clicking on it feels counter-intuitive. 

Idea of listing the tags when clicking on it came from labels in gmail. When a label is clicked, gmail list all the messages belong to that label. 

Some of my tags are  

- ubuntu
- yarn
- youtube
- work
- webinar
- webgl
- virtualization
- vpn
- varnish
- vagrant 
- unit-testing 

They are at bottom of the list. I have to scroll every time or search the tags to list them. If I have a note open and I want to see related notes, it would be easier option to just click on the tag and list all those notes. 


Another option is to provide rename or delete option when tag is clicked. 

Not high priority but nice to have feature. 


Thanks

**Comment by mobitar** [comment]
Got it, thanks for the feedback.
