### ISSUE TITLE
[macOS] [desktop 2.0.42] Simple Task Editor doesn't always render content on first try

### ISSUE THREAD

**Issue by wireddude** [standardnotes/desktop#123]
A few times I tried to view my task list, and it didn't render when I selected the note from the lefthand pane. I had to click into the empty note to see it, and click around to a few other notes. Once it shows up, I cannot reproduce it anymore. maybe a one time fluke, but I wanted to log just incase you've seen it before.

**Comment by mobitar** [comment]
So have you seen this only once, or you see it once in a while but can't replicate it? Next time this happens try to pay attention to what note you're coming from, and what editor that note uses. I've found and fixed an issue related to switching notes with different editors, so it might be something related.

**Comment by mobitar** [comment]
Should be improved in recent releases.
