### ISSUE TITLE
[Arch Linux]: Markdown Editor is no longer an option

### ISSUE THREAD

**Issue by someguynamedmatt** [standardnotes/desktop#126]
Arch (Linux 4.14.3-1-ARCH)
Gnome 3

I can click on `Extensions` in the lower-left of the StandardNotes window and `Activate` my Markdown extension (Simple Markdown), but it isn't available in the `Editors` menu in the notes window. This happened after the latest upgrade (`2`? I'm currently running `2.0.2`)

**Comment by mobitar** [comment]
Please upgrade your app to the latest version (2.0.41) as editors are now converted to use a different system.
