### ISSUE TITLE
feature request: titleBarStyle: 'hiddenInset'

### ISSUE THREAD

**Issue by will-stone** [standardnotes/desktop#127]
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/654103/33610056-352e5d3c-d9c2-11e7-9cd5-217e6a54132a.png">

I've not submitted a pull request for this because I don't know how well this translates to other systems but that was created by adding the option `titleBarStyle: 'hiddenInset'` to the `app/index.js` BrowserWindow, and adding some margin-top to the `.tags #tags-title-bar`.

**Comment by mobitar** [comment]
This is really cool! I like the way it looks. I might just add this in for the next version. Will have to test it myself though to see if anything unexpected happens.

**Comment by mobitar** [comment]
Ok, getting ready to publish this here: https://github.com/standardnotes/desktop/releases/tag/v2.0.43-beta2

**Comment by will-stone** [comment]
That's great. Thanks. I can confirm it works on macOS.
