### ISSUE TITLE
Add Linux snap target

### ISSUE THREAD

**Issue by RobBrazier** [standardnotes/desktop#129]
Could a snap package be created for Linux as well as the existing Deb and AppImage?

From what I gather, snaps automatically update as well, and cover most Linux distros now.

This should be as easy as adding "snap" to the target for Linux. There are some extra config options required as well though, to define the confinement etc.

https://www.electron.build/configuration/snap

I'm happy to give this a go if you want

**Comment by mobitar** [comment]
Sure, feel free to give this a go. If I recall I tried this once but could not successfully get it to work, but that may have been another package format.

**Comment by RobBrazier** [comment]
I've managed to get it working for x86_64 within a docker container, still working on i386 though. 
Just out of interest, how are you building the release artifacts, hopefully I can try and optimise the process

**Comment by mobitar** [comment]
I just run `npm run release` to build and release to GitHub. [electron-builder](https://github.com/electron-userland/electron-builder) handles most of it.

**Comment by RobBrazier** [comment]
okay,  grand - just trying that now. Is this just from your local machine then? 

It looks like when building snaps, electron-builder a bit pickier when it comes to compiling for multiple architectures (it seems to need extra node bindings for i386, AppImage doesn't do this though). I guess that might have been the snag you hit before?

What I'm kind of tempted to do (might be a bit easier) is separate the snap into a new repository and build from the .deb, e.g https://github.com/snapcrafters/atom

**Comment by mobitar** [comment]
Correct I'm building from my local machine. That might be the issue I ran into.
