### ISSUE TITLE
Homebrew Cask

### ISSUE THREAD

**Issue by gwerbin** [standardnotes/desktop#13]
In case anyone involved is interested, I wrote a Homebrew formula for the Mac version of Standard Notes:

https://github.com/gwerbin/homebrew-tap/blob/master/Casks/standard-notes.rb

So the program is now installable on macOS with:

```shell
brew tap gwerbin/tap
brew cask install standard-notes
```

If you like the idea of having a Homebrew formula, I can submit this to the Homebrew project for inclusion in their core repository. However it's tough for me to keep up-to-date with releases on software like this that I don't necessarily use very often, so I'd encourage you to take ownership of the formula, since they do require manual version bumps and SHA hash updates.

**Comment by mobitar** [comment]
Sweet, this is awesome, thanks! What's the best way to go about updating releases on Homebrew?

**Comment by gwerbin** [comment]
Casks and Formulas are basically declarative configuration files that also happen to be valid Ruby code. Homebrew Formulas were and are traditionally used for source builds, or for pre-built binaries that only install to `/usr/local`. Casks are for pre-built packages like .app packages, fonts, or anything that requires a GUI installer.

Unfortunately the syntax and style are slightly different between a traditional Homebrew Formula and a Cask, because they started as separate projects and were merged. Writing them can be a little esoteric, but updating them is typically dead-simple. This is the full content of the Cask I posted:

```ruby
cask 'standard-notes' do
  version '0.1.1'
  sha256 '9b6a96ac9d00687f9fdd1ccd456ce36575228dd3a6b90662e8fe529bee04d955'
  url 'https://github.com/standardnotes/desktop/releases/download/v0.1.1/Standard.Notes-Mac-0.1.1.dmg'

  name 'Standard Notes'
  homepage 'https://standardnotes.org/'

  app 'Standard Notes.app'
end
```

When the version is changed, all that needs to happen is the `0.1.1` in the `version` "stanza" gets updated, the the URL in the `url` stanza gets updated, and the hash in the `sha256` gets updated to the hash of the .dmg file. Homebrew-cask takes care of the rest. Then it's just a matter of making a pull request to caskroom/homebrew-cask with the changes.

If installation ever becomes more complicated, Homebrew-cask has nice documentation [here](https://github.com/caskroom/homebrew-cask/tree/master/doc/cask_language_reference) that you can follow.

**Comment by mobitar** [comment]
Great, thanks for the detailed explanation. Yes, if you can submit this initial version that'd be great, and then I can take updates from there, and reach out to you if I encounter any issues.

**Comment by gwerbin** [comment]
https://github.com/caskroom/homebrew-cask/pull/29146

**Comment by mobitar** [comment]
Thanks @gwerbin!

**Comment by gwerbin** [comment]
Merged! FYI here are instructions for updating a Cask: https://github.com/caskroom/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask

**Comment by mobitar** [comment]
Awesome thanks!
