### ISSUE TITLE
Option to disable red underline on words not written correctly

### ISSUE THREAD

**Issue by haskaalo** [standardnotes/desktop#130]
How about a option to disable red underline on words not written correctly? 

![image](https://user-images.githubusercontent.com/7819295/33802651-93e9b5d0-dd49-11e7-86be-09c5b2158dfd.png)

It can sometimes be annoying when the word you wrote is actually correct or in another language but it doesn't know

**Comment by mobitar** [comment]
You can't disable spellcheck currently but it should choose the right dictionary for whatever language your system uses. I don't think it recognizes latin.

**Comment by mirsev** [comment]
I'm not sure that it may support any language. 
![image](https://user-images.githubusercontent.com/12778668/34817821-19e3301e-f6ca-11e7-9857-05dab6763b6c.png)
On my Ubuntu 16.04 LTS it recognizes only English, ignores Cyrillic and is annoyed by Spanish. It does not appear to be really useful now, especially if one uses Standard Notes to keep some private or confidential information like user names and passwords. The latter must not be dictionary words by definition.
So, I think it would be great if the spellcheck can be optionally switched off.

**Comment by mobitar** [comment]
Yeah, I'm starting to notice this too. I've added it to my priority list.

**Comment by mobitar** [comment]
Spellcheck can now be disabled via the Options menu.
