### ISSUE TITLE
[Feature Request] Desktop widgets

### ISSUE THREAD

**Issue by Igetin** [standardnotes/desktop#132]
I'm looking for a feature similar to Sticky Notes on Windows and KNotes on Linux. There should be an option in the desktop application to pin/stick a note to the user's desktop. The note should also be editable there.

**Comment by mobitar** [comment]
Pin to desktop? Not really sure what that means. You can pin to top. But SN is a self-contained environment. There's no external file editing.

**Comment by Igetin** [comment]
Maybe I should have used the word "widget"? Changed the title for clarity.

Here's an example of Xpad:

![screenshot_2017-12-27_18-51-44_xpad](https://user-images.githubusercontent.com/14016863/34388052-41b6b67e-eb3a-11e7-96b4-dd0110551a77.png)

The notes stay in the desktop along the shorcut icons, and they can be freely dragged around there. There's also an option to lock the notes so that you won't accidentally edit them. When the system is rebooted, the notes appear right where you left them.

**Comment by mobitar** [comment]
Ah ok, yeah that would be very difficult for our system. This would need to happen in the form of a 3rd party app on top of SN.
