### ISSUE TITLE
Scrollbars

### ISSUE THREAD

**Issue by Philiphlop** [standardnotes/desktop#133]
I have massive scrollbars, not sure why they are so big, but it really breaks the look of SN, especially when using a theme. 

![image](https://user-images.githubusercontent.com/22427598/34361796-792ea77c-ea65-11e7-844f-9669a7681598.png)

I had a play around in dev tools and can customise some to be consistent with the theme style, smaller widths and overlay the box, making it far less obtrusive. Though some areas are iframed in and the CSS struggles to go that deep. I don't see any way to save custom CSS, so have come to here.

**Comment by mobitar** [comment]
Hmm, I'll have to take a look at this. If you have a snippet that worked for the base-level CSS, please share it as to save me the research work ;)

**Comment by Philiphlop** [comment]
I don't have what I played with, but I got it from here

https://www.w3schools.com/howto/howto_css_custom_scrollbar.asp

**Comment by Philiphlop** [comment]
Have taken more of a look, it's a bit tricky when there are iframes such as the tags list, as browsers struggle to apply CSS within an iframe. But here you can see what's done for the notes list which looks a lot more pleasing and fits nicely. 

```
*::-webkit-scrollbar {     
        background-color: transparent !important;
        width: 1em !important;
}

*::-webkit-scrollbar-thumb:window-inactive,
*::-webkit-scrollbar-thumb {
        background:  rgba(0,0,0,.5) !important;
}
```

I had to apply this to the inpsector stylesheet, then delete the element and undo to re-insert it. I presume this makes the CSS reload for the elements. 

![image](https://user-images.githubusercontent.com/22427598/36301670-9192df98-12fd-11e8-8840-59005b6024a3.png)

**Comment by mobitar** [comment]
That does look better. I'll see about adding this in the external themes.

**Comment by mobitar** [comment]
Fixed in v3.
