### ISSUE TITLE
Folders & Theme Colours

### ISSUE THREAD

**Issue by Philiphlop** [standardnotes/desktop#134]
I have two extensions enabled, "Folders" and "Midnight", but they don't play well with each other.  The selected folder text colour is not contrasted to the bar/row of the folder. So it's not readable. 

![image](https://user-images.githubusercontent.com/22427598/34361887-7057392e-ea66-11e7-88fe-8cfb3ad95a3a.png)

**Comment by mobitar** [comment]
Should be much improved in v3.
