### ISSUE TITLE
[Feature Request] Add pictures in notes, not HTML links pointing to images

### ISSUE THREAD

**Issue by calvadosxo** [standardnotes/desktop#136]
There is only 2 things stopping me from using Standard Notes as my full notes and task management system and this is one of them. And, of course, it should be compatible with the android app (edit: I mean the feature of adding local images in notes should be compatible with both desktop and mobile).

Keep up the good work, you are doing an amazing job.

**Comment by JoshuaRLi** [comment]
The android app is fully functional, AFAIK. If you have any issues, please report them [here](https://github.com/standardnotes/mobile/issues).

The ability to embed pictures in notes is against the simple, universal, text-oriented design philosophy of Standard Notes. Though it would be interesting to have some sort of SN Extension that detects image links and renders them in-place, client side.

**Comment by calvadosxo** [comment]
There is already a way to add image and render links with the "Plus Editor", so I don't see SN to be only text-oriented. There is also a mention when you try to import a file with the Plus Editor that says that it is not "yet" possible. So, it must then be part of the SN philosophy, or at least, of the extensions philosophy.

**Comment by JoshuaRLi** [comment]
Ah, was not aware the plus editor has that functionality since I don't use it.

**Comment by mobitar** [comment]
Yes, part of the "extended" philosophy, but still a far way, because uploaded images will require encryption/decryption and key management, which is not trivial. Still focusing on the fundamentals for now.
