### ISSUE TITLE
How do backups function?

### ISSUE THREAD

**Issue by harrisondesbrosses** [standardnotes/desktop#140]
Hello-

I'm just hoping to learn more about how backups work. 

- How do you choose the location of backups / can you change the file path if needed?
-When are these backups created?
-How does importing them back into SN work if I were to mess up my current file structure and want to backup from an import? Would tags be retained.

I plan on hosting these backups on my server in encrypted form and would just like to do a test crash of my current setup to see if I'm able to restore notes correctly.

Thank you!

**Comment by mobitar** [comment]
Hey @harrisondesbrosses, good question. There are two sorts of backups:

1. Manual Backups: made by the user when they click Account -> Download Backup.
2. Automatic Backups – made by the Desktop app automatically when it is open.

Both backups have the same formats, and can be imported into the application at any time in the future. Backups include relationships, so tags will be retained.

Manual backups are on a per-usage basis, so you select the download location every time. Automatic backups default to your home directory on your computer, under Standard Notes Backups. You can change the location to which automatic backups should happen via the "Backups" top-level menu item, then click Change Backups Location. Changing the location will keep your old location files in place, and begin using your new directory for new backups.

Hope that helps.

**Comment by harrisondesbrosses** [comment]
Totally helps. Consider it done!
