### ISSUE TITLE
2.1_beta Editor extensions won't install

### ISSUE THREAD

**Issue by chegeiser** [standardnotes/desktop#145]
Hi,

I installed the Beta 2.1 version and the Editors that I had previously installed still worked - good. But I noticed that in the description of features in beta version extensions are supposed to be available offline, and that this could be checked by clicking on the three dots button. My Editor extensions did not have the three dots, so I uninstalled them and then tried to re-install them. They will not install now. 

When I enter the extension link it gives me a section to confirm the installation, I click on the Install button and it then says 'Extension successfully installed'. However, the extension does not show up in the list of extensions at the bottom of the screen nor does it show up as one of the available Editors.

So I tried using the web version of Standard Notes. This time it all worked. And when I refresh the Windows desktop app the editor is available. However, the three dots button that would allow me to force offline editor only is still not there. 

Additionally, this three dots button is in place for the Extensions extension - see screen shot attached.
![extensions_sn](https://user-images.githubusercontent.com/17602493/35594297-7cca0642-05c7-11e8-875c-d8b38a81455d.jpg)

**Comment by mobitar** [comment]
@chegeiser the new Extensions manager doesn't support editor installation by URL. Instead, you should add the repository URL for your Extended account, which can be found at dashboard.standardnotes.org, after you sign in, and all the way at the bottom. This should be the new method by which you install extensions.

**Comment by chegeiser** [comment]
There’s a long Extended Preview Code available at the bottom of dashboard.standardnotes.com but I can’t figure out where to enter this code.

**Comment by mobitar** [comment]
You would enter it in the Extensions menu as shown here:

<img width="879" alt="screen shot 2018-02-01 at 12 29 21 pm" src="https://user-images.githubusercontent.com/3277844/35695944-90a4c596-074b-11e8-8cac-dd956d66cadc.png">

**Comment by airjoshb** [comment]
What if you don't have the Extended Code field in your app?

**Comment by mobitar** [comment]
What are you seeing instead?

**Comment by airjoshb** [comment]
<img width="396" alt="screen shot 2018-02-09 at 10 30 52 am" src="https://user-images.githubusercontent.com/44965/36043520-6ba929c8-0d84-11e8-9a79-2ebf8fdf2c0e.png">

**Comment by mobitar** [comment]
Oh you’ll need to download the 2.1 beta above. You’re running 2.0 here.

On Feb 9, 2018, at 12:01 PM, Josh Bradley <notifications@github.com> wrote:

What if you don't have the Extended Code field in your app?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/standardnotes/desktop/issues/145#issuecomment-364510307>,
or mute the thread
