### ISSUE TITLE
Replace "Cmd" with "Ctrl" in UI for non-mac platforms

### ISSUE THREAD

**Issue by mrbiber** [standardnotes/desktop#15]
At the moment, the "File" dropdown menu lists "Cmd"-shortcuts on Linux. This should be "Ctrl"

**Comment by mobitar** [comment]
Good catch, thanks.

**Comment by yohanmishkin** [comment]
Looks good to me on Windows.

**Comment by m4rcu5nl** [comment]
In the Windows client this seems only to be the case in the 'File' dropdown within the editor section of the client. It shows 'Cmd + O' to toggle fullscreen. Very minor issue, but thought I'd add it to this report anyway.

**Comment by mobitar** [comment]
Shortcut text has been removed.
