### ISSUE TITLE
2.1 beta Extra Drag bars in edit panel

### ISSUE THREAD

**Issue by inkstain** [standardnotes/desktop#150]
Am encountering an extra vertical drag bar on each side of the editing window. The left side one is immediated adjacent to the one for the Note list, but hovering over from left to right I see two different ~20pixel width vertical columns and dragging on the right one to the right moves the left margin of the edit pane text to the right. Likewise on the extreme right of the edit pane there is another drag bar that if dragged left will restrict the edit panel from that side.

This happens no matter which editor is selected and is reproducable on restarting the app; am using the appimage install on Ubuntu 16.04 64bit. Have tried uninstalling and reinstalling the theme I use as well as all editors (though it happens as well on Plain Text editor)

Please let me know if you need additional details, and thanks for the additional features! All will be useful, especially 2FA when that is completed!

**Comment by mobitar** [comment]
Hey @inkstain, there should indeed be two extra bars in the editor—those are used to adjust the editor margins. Are you referring to something else?

2.1 is launched today with 2FA :)

**Comment by inkstain** [comment]
Ah, I was wondering if that was what they were for, I just never noticed them previously and it struck me as odd that the margins were independent of each other (though that can come in handy at times).

User error on my part :)

And, yes, thanks! I noticed 2FA rolled out this morning my time and I enabled it right away. What a great addition!

**Comment by mobitar** [comment]
:)
