### ISSUE TITLE
2.1.0 Spellcheck can only be disabled in the Plain Editor

### ISSUE THREAD

**Issue by jaco-l** [standardnotes/desktop#151]
Congratulations with the 2.1 release ! Now that spellcheck can be disabled Standard Notes becomes useful to me (I type mainly non-english notes while having an English language pack installed on my system for several reasons). I think Standard Notes is great otherwise and I registered for one year ahead yesterday.

Unfortunately, in the other editors, such as Plus Editor and Simple Markdown Editor the spellcheck is still active and can not be disabled. I hope you can look at this too.

**Comment by mobitar** [comment]
Good catch, thanks, will investigate this.

**Comment by jaco-l** [comment]
This issue is solved
