### ISSUE TITLE
troubles with 2.1 desktop for mac

### ISSUE THREAD

**Issue by RyanMasson** [standardnotes/desktop#154]
- clicking the Account button does nothing
- Extensions button duplicates along the bottom bar
- The title and tags section at the top of a note seems to have disappeared

Did I incorrectly install this new version? All I did was download it from the homepage and open up the zip folder and install the app. And I don't use Standard Notes on any other platform.

Going back to 2.0.42 for now

**Comment by RyanMasson** [comment]
I'm on 10.13.3.

Yeah, I get errors when I click the Account menu. I'm attaching a text file with the whole output of my console when I click it. It includes some of my tags from my notes but that's okay. Could it have something to do with the fact that I've been putting the characters * and ~ before many of my tags?

[SN_2.1_masson_errors.txt](https://github.com/standardnotes/desktop/files/1733859/SN_2.1_masson_errors.txt)

**Comment by mobitar** [comment]
And this log output occurs immediately when you hit the Account button?

**Comment by mobitar** [comment]
Also, how many tags do you have in all, approximately?

**Comment by RyanMasson** [comment]
Yes, the output all appears immediately when I click Account.

I have about 330 tags

**Comment by mobitar** [comment]
What about if you try using the web app at app.standardnotes.org? Do you still see the same issue?

If you don't see the issue on a new login on web, then it might help to reset your data on the Mac, and sign back in. To do that, click on the upper-level "Help" menu, then "Open Data Directory", and delete all the files there. Then restart the app and sign.

**Comment by RyanMasson** [comment]
I don't have the issues on the web app, and when I reset data on the Mac version everything looks great - the new features and all buttons are working. But when I import my notes from a backup, the errors reappear. It seems something about my notes or tags is breaking the app. I just tried removing all * and ~ from the beginning of my tags, but importing still breaks it.

**Comment by RyanMasson** [comment]
I just found the source of the problem:

having more than 10 tags on one note breaks the app

**Comment by mobitar** [comment]
Oh wow, good catch! Just deployed a fix for this on the web app, desktop release will follow some time this week. https://github.com/standardnotes/web/commit/4289d4806d612de63fc56a020faf4f757e4fd1d3
