### ISSUE TITLE
Dragging and dropping an image takes over screen, requires relaunch, sometimes loses content of current edit

### ISSUE THREAD

**Issue by mrled** [standardnotes/desktop#156]
## Problem description

- Platform: macOS
- Version: 2.1.0

I dragged and dropped an image into the application window.

In my defense, I was testing to see whether the application supported attachments. I had created a new note, changed its title from the default "New Note 1" title, and added some text to the body, but I hadn't saved it yet. Then I grabbed an image and dragged it over the application window. The cursor changed from the plain black pointer to the black pointer with a green plus symbol - normally an indication that my drag and drop will be accepted by the application.

In fact, it was, but not in the way I expected. The application displayed the image and only the image, rather than (as I was hoping) adding the image as an attachment to the note. I tried to go back, thinking that this was perhaps default Electron behavior, but there were no back controls in the app or in the menus, and Cmd + Left Arrow, which usually works in a web browser, did not go back either.

When that failed, I closed the application window without quitting the app. However, once done, there was no way to open another application window. Ultimately, I ended up quitting the app from the menu bar and then relaunching.

Fortunately, relaunching did open another application window, but the note I was editing when I had dragged the image did not save my edits. These edits were lost; the title was reverted to "New Note 1", and the note body was empty.

Later, I was curious as to whether it always trashed the current note, or if it only did so if the drag and drop was too fast after making a change, preventing the incremental saving from kicking in. I found that as long as I waited until the message in the upper right corner said "All changes saved", the changes persisted after dragging, dropping, and relaunching.

## Expected behavior

- The application will reject any dragged and dropped item that it cannot handle natively
- The application will either prevent closing its window, or provide a mechanism for opening a new window after it has been closed
- Edits will not be lost during adverse events (including unexpected quits like I made, crashes, or other unplanned incidents)

## Conclusion

Thanks for the cool app :) I love the focus on end-to-end encryption and I will continue testing this app for my use.

Not sure if this is the right place for this, but for the record, attachments are not a big deal to me either way, I just wanted to test whether they were supported. I'm not trying to sneak that feature request in, just reporting some problems I had when I used the app in an unexpected (but well-intentioned) way.

**Comment by mobitar** [comment]
Ah good catch, the window should definitely reject these attachments. Will see what can be done about this.

Regarding the saving, everything autosaves within 250ms, so if somehow you were able to type a title and drag the image all in less than 250ms, it's possible the changes wouldn't be saved, although that would seem impossible to replicate. Will toy around with this.

**Comment by SeanDHeath** [comment]
Still happening on Linux - version 3.0.6. It would be awesome to have the image inserted automatically if in markdown mode.

**Comment by mobitar** [comment]
This is fixed in a recent release. The correct way to attach files is now to use the Bold Editor.
