### ISSUE TITLE
Chatty tool-tips in notes' menu

### ISSUE THREAD

**Issue by x80486** [standardnotes/desktop#158]
I installed the AppImage desktop application `2.1.1-x86_64` in Ubuntu (`Linux uplink 4.13.0-36-generic #40~16.04.1-Ubuntu SMP Fri Feb 16 23:25:58 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`) and I've noticed that some tool-tips are displaying the ternary operation (`code itself`) instead of the actual string that would be the outcome when the condition gets evaluated.

You can see those in: (a) `Menu` > `Pin`, and (b) `Menu` > `Archive`. Additionally, the simple quotes are also part of the tool-tip, but I think that's how you planned since all of them have it.

![tooltip](https://user-images.githubusercontent.com/34633617/36689743-4ca18e30-1afe-11e8-952d-8aaef0e5dd0f.png)

Not a big deal, but something you can squeeze on any release.

**Comment by mobitar** [comment]
Hey @x80486, can you share a screenshot? Having a hard time visualizing what you mean..

**Comment by x80486** [comment]
@mobitar, I updated the comment. See the tool-tip when you hover `Archive` or `Pin`.

**Comment by mobitar** [comment]
Ah I see, that does indeed need to be fixed. It's possible that this PR fixes it: https://github.com/standardnotes/web/pull/187/files
