### ISSUE TITLE
2.1.1 'clear local data' does not clear the local .txt files (Desktop Ubuntu and Windows 10)

### ISSUE THREAD

**Issue by jaco-l** [standardnotes/desktop#159]
The Backups Location just keeps filling up with files named like: <pre>Mon Feb 19 2018 16-11-57 GMT+0100 (CET).txt</pre>

There seems no way to delete these files from within the SN desktop software. `Account -> Sign out and clear local data` has no effect and neither has `Help -> Clear Cache and Reload`.

Note: data backups are encrypted

**Comment by mobitar** [comment]
Hmm..clear local data is meant for something else. Perhaps a "Delete All Local Backups" option should be explicitly added?

**Comment by jaco-l** [comment]
Ah... only now I realize that every .txt file represents a backup. In that case, I suggest to make the backup process more explicit. An automatic backup could replace the last automatic backup, so there will be only one file. In addition, the user could make a deliberate backup with a time-stamp and some chosen label on a moment that makes sense for example just after a bunch of notes were added or reorganized.

In any case, a directory that just fills up with files endlessly seems bad style to me. This may also raise disk space concerns when images are made possible in the notes.

**Comment by mobitar** [comment]
Yeah, totally. I wanted to get a baseline solution out there first, then spend time making it more stylish. I plan on spending more time on this.
