### ISSUE TITLE
Improve visually tag(s) creation/modification

### ISSUE THREAD

**Issue by x80486** [standardnotes/desktop#160]
It would be nice to have some sort of "visual guidance" when creating/editing tags. I'm not referring to those you create by using the `+` button besides the `Tags` label, or edit using the **Rename** link...but the ones you create/edit by typing them in the section below the note's title.

For instance, **(a)** if they looked like a <a href="https://getbootstrap.com/docs/4.0/components/badge/" target="_blank">badge</a> (or pill) you would know that, to change the one already assigned to the note, you would need to double click on it (or something like that); **(b)** when you start typing right after one, you would know that you are creating a new one — and not modifying the existing one.

Additionally, having an _auto-complete_ function when you start typing one (for those you already have) won't hurt also ;)

**Comment by mobitar** [comment]
This is what the autocomplete extension was built for: https://standardnotes.org/extensions/autocomplete-tags

I agree the baseline one could be a little more helpful, but it's very utilitarian.
