### ISSUE TITLE
Auto-update not working - "Sign verification failed, installer signed with incorrect certificate"

### ISSUE THREAD

**Issue by paintedindigo** [standardnotes/desktop#162]
Hello,

I actually came here to suggest this feature, but it seems to already exist in the program. It does not appear to work for me on either of my computers. I have to manually go to Help -> Version: x.x.x and download the new builds from GitHub.

Both computers are Windows 10 with the 64-bit versions of Standard Notes.

I checked log.log and found that there are errors when Standard Notes tries to update. I have attached an excerpt, from the most recent occurrence of this problem.

[log.txt](https://github.com/standardnotes/desktop/files/1791695/log.txt)

**Comment by mobitar** [comment]
Hmm strange, first time I'm hearing about this. Will investigate.

**Comment by Kelvino9** [comment]
Standard Notes on my Windows 10 x64 system doesn't auto update either  for a few months. Have to update the app manually ever since.

**Comment by mobitar** [comment]
Should be fixed in recent releases.
