### ISSUE TITLE
Unfortunate side panels in notes' main area

### ISSUE THREAD

**Issue by x80486** [standardnotes/desktop#163]
I updated to version `2.1.21` (on **macOS** Sierra `10.12.6`) and I noticed the main's note area became less wide....so (I dig it)™ and there are two components called `panel-resizer` between the notes' main area that sometimes _get out of control_.

![app-left-side](https://user-images.githubusercontent.com/34633617/37169969-8c81df1a-22d7-11e8-9fd3-5bfc854c97c5.jpg)

![app-right-side](https://user-images.githubusercontent.com/34633617/37169979-932293f0-22d7-11e8-8381-5b25d707bcc7.jpg)

Funny thing is: you can put them away, but most of the times, when you start/restart the application, they move out of the borders to a (not so) random location — within the notes' main area.

It's easy to live with that, not a problem, but: are those really needed?

**Comment by mobitar** [comment]
The reason for them is kind of to get a full screen mode going: https://github.com/standardnotes/forum/issues/162#issuecomment-366274453

**Comment by x80486** [comment]
OK, so I think the issue then is: _why do they get out (just like that) from the position(s) they should be initially — on the left and right borders of the enclosed component_.

I can confirm it happens, although not every time (I can't figure it out a pattern here), under **macOS Sierra** `10.12.6` and **Arch Linux** `4.15.9-1-ARCH` (GNOME `2.x`) using the version reported and also `2.1.23`.

In any case, I just put them back every time it happens! If it's not a big deal for you or anyone else, you can close this one.

**Comment by mobitar** [comment]
Yeah, there seems to be a bug that distorts the location of the bars, but I too haven't been able to deduce a pattern ;) Keeping a close eye on it..

**Comment by MorgothSauron** [comment]
I encountered that behavior on Fedora 28 too.

**Comment by x80486** [comment]
**Margin resizers** (in the `Options` menu) will do the trick now – disable/enable them.
