### ISSUE TITLE
Little Snitch seems to think SN is running in App Translocation

### ISSUE THREAD

**Issue by harrisondesbrosses** [standardnotes/desktop#164]
Hey! I had posted about this in the Slack chat awhile back.. but I resolved the issue on my desktop. However, this is now playing up on my laptop.

I'm running the latest OSX + have done clean uninstalls via AppCleaner of SN multiple times, wiping out the archives as well.. to no avail! Please help.

![by default 2018-03-10 at 12 39 50 am](https://user-images.githubusercontent.com/22471894/37247712-958f06fc-248d-11e8-9d80-74d4b8da4373.png)

**Comment by mobitar** [comment]
I honestly don't know. Can you try reaching out to Little Snitch and see what they say?

**Comment by harrisondesbrosses** [comment]
That’s a good idea! Will do. Little snitch is so annoying haha.

**Comment by harrisondesbrosses** [comment]
Sent! I'll let you know what they say.

**Comment by harrisondesbrosses** [comment]
Solved! 💃 

Here's the email from the ObDev guys:

"thank you for your request.

Next time you experience this issue, it would be great if you could check the alert window with its details revealed (click on the button with the three dots appearing close to the research assistant button with the glasses or simply press the key ‘I’ or ‘D’).
This should reveal the process path for ‘Standard Notes’ and you will then probably see that the process path is not /Applications but something like /private/var/…

Little Snitch itself identifies the processes by its path, but with App Translocation the path is always a new one with every start of the process.

We wrote a blog post about this issue a while ago. If you wish you can have a look at it at [](https://blog.obdev.at/gatekeeper-and-little-snitch-rules/)

Hope this helps,
Let me know if I can be of any further assistance."

**Comment by mobitar** [comment]
Wait so what's the solution?

**Comment by mobitar** [comment]
Ah ok didn't see the link..

**Comment by harrisondesbrosses** [comment]
It's in that link, a bit too long to paste I think... but it's a simple terminal command that takes the app out of a quarantine.

**Comment by harrisondesbrosses** [comment]
Happy for you to close this whenever - the fix was so easy I don't care if you ever "fix" this. I just think some people may encounter it again.

**Comment by mobitar** [comment]
Interesting..although I didn't get an impression for what the developer should do? Thanks for reaching out to them :)

(Whether issues are opened/closed makes no difference. I treat all issues as discussions and not todos.)

**Comment by harrisondesbrosses** [comment]
Me neither! And of course! 

Noted about closing... so happy you're not some freak mod who has all the time in the world to be policing threads closing left and right haha.

**Comment by mobitar** [comment]
Haha that's exactly the trap I'm trying to avoid. I don't want it to be a game of getting to 0, since one would go quickly mad doing that.
