### ISSUE TITLE
Multiple dots in filename

### ISSUE THREAD

**Issue by Gediminas** [standardnotes/desktop#165]
When file-name contains dots, only part till first dot is shown after import.
(also search ignores text after first dot)
 
e.g.
for file "refx. devx. some description.txt"
title is "refx"
should be **"refx. devx. some description"**

**Comment by mobitar** [comment]
Hmm strange. Do you know if this incorrect structure is also reflected in the import file itself, or just when the import occurs inside the application?

**Comment by Gediminas** [comment]
file (generated by "Plaintext to Standard Notes Converter") has incorrect content.title
{
      ...
      "content_type": "Note",
      "created_at": "2018-03-21T14:01:15.584Z",
      "content": {
        "title": "refx",
        ...
       }
       ...
}

**Comment by mobitar** [comment]
Ah ok, so something is wrong with the converter. Will investigate this when I can.

**Comment by mobitar** [comment]
A bit outdated now. Please let me know if issue still occurs.
