### ISSUE TITLE
Desktop integration issue under Ubuntu 17.10

### ISSUE THREAD

**Issue by mheder** [standardnotes/desktop#166]
This is a minor annoyance really. But since I have to adjust this upon each update I thought it is worth to report. 

On the vertical task bar+app launch bar on the left side of the default ubuntu gnome shell, Standard Notes is unable to be added to the favorites the usual way (which is: running the app and right-clicking on the icon that shows up in the unified taskbar+launchbar). You can force the icon to be there by drag-and-dropping it to the launch bar, but in this case when you launch the app it won't merge with its launcher and you will end up having two icons. 

Fortunately, the issue is easy to solve. The root of the problem is that the desktop file does not contain a 
``
StartupWMClass
`` 
entry. 

If you just add 
``
StartupWMClass=standard notes
``
to **appimagekit-standard-notes.desktop**
the problem goes away. It would be so nice to have it out of the box! 

The app is progressing very well by the way, congrats!

**Comment by mobitar** [comment]
Thanks, added!
