### ISSUE TITLE
After last updated locked notes are unlocked

### ISSUE THREAD

**Issue by jeremyj** [standardnotes/desktop#169]
As per the title: after the last upgrade on Linux all notes that were locked are now unlocked.
Version is 2.1.25 AppImage

**Comment by mobitar** [comment]
Unlikely the cause. Most likely, the notes were duplicated and you're looking at older duplicates. Or some other explanation. See if you can find some further correlations..

**Comment by jeremyj** [comment]
@mobitar after the last update all notes were locked again.
