### ISSUE TITLE
Fast new note flow

### ISSUE THREAD

**Issue by admiral-Guck** [standardnotes/desktop#17]
What would be great is never needing to leave the keyboard to create a new note and tag it. For me, the flow would look like this:
1) cmd-tab into standardnotes
2) cmd-n for new note, type title
3) tab to tags, type tags
4) tab to content, type content

Ideally, tags would autocomplete (but that's not a priority). Also, shouldn't it be possible to delete notes and tags?

**Comment by mobitar** [comment]
Yes you can delete notes and tags via the "File" dropdown. I like your proposition for keyboard shortcuts. A lot of people have been requesting this. There already exists some shortcuts and it shouldn't be too bad to add more. This is high up on the list.

**Comment by admiral-Guck** [comment]
Ah, dunno why I didn't see this before. It's confusing though that the tag dropdown is in the notes column. I expected 'Delete Tag' to delete the selected tag from the selected note (which is a nice feature btw ;) ). Having two 'File' dropdowns doesn't help, either. I'd rename the tag dropdown to 'Options' and put it flush right below the + , or make it a little ⌵ to the right of the + . Maybe you're planning on adding features that would fit into a dropdown in the notes column, but in any case there should be separate dropdowns for options regarding tags, notes and content.

Loving your work so far!

**Comment by mobitar** [comment]
Thanks! And thanks for the feedback, this will definitely be getting revisited in the coming weeks.
