### ISSUE TITLE
Slow reaction to key presses in editor

### ISSUE THREAD

**Issue by ni-ka** [standardnotes/desktop#171]
Hi,

I want to migrate from Evernote to standard notes (using version 2.1.25 on arch / gnome 3.28 / wayland). I used the enex tool to convert my notes (~4500).

When I edit notes, the text appears delayed so the editing has a lag. Makes the app unusable unfortunately.

In this sequence i was pressing and holding the keys down. the numbers should appear continuously but they all appear as a block.

**Comment by mobitar** [comment]
Please try refreshing the app with Ctrl+R to clear up some memory after the import. Right now probably all 4500 notes are loaded into the interface. After the refresh, it will only load immediate notes.

**Comment by ni-ka** [comment]
Thanks @mobitar it is better, but still some delays if i just keep a key pressed down. its not as continous as in other apps or browser.

**Comment by mobitar** [comment]
4500 notes is still quite a lot. How big of a file was the import file generated from the evernote converter?

You can also try quitting the app completely and re-opening it to see if that helps.

**Comment by mobitar** [comment]
In the notes column, can you check whether in initial state, when you scroll, does the scroll bar look really small like there are thousands of items? Or, does it do correctly do paginated scroll, where items are added as you scroll?

**Comment by ni-ka** [comment]
looks like the pagination works.

from a brief look at the profiler output i would say it looks like a change of the text triggers an update of the lastmodified property / potentially even the text, which seems to trigger a sorting based on all notes. if that is the case, maybe the saving of the note should be decoupled from the key events / text update. a nice way would be by triggering a background update a few seconds after the last update (instead of after every keypress)

i can look deeper but would need to install the development environment.

**Comment by mobitar** [comment]
It has something to do with how AngularJS works, in that when a change is made, a global refresh is applied to update all bindings, and sorting is tied to the refresh. Though, I haven't heard of anyone having any issues with it (though it might be rare that someone has that many notes). Perhaps you have some notes that are extremely large? What was the file size of the import file that you used?

**Comment by ni-ka** [comment]
thanks @mobitar 

I've developed with Angular in the past and yes, that is a reason why bindings need to be carefully designed. It is not good practice if things result in slowing down the UI because operations are directly linked to the bindings (i.e. you could have updates done asynchronously). Sometimes it's worth introducing a separate object which is to update the UI (i.e. in this case separating the logic of editing a single note from the sorting of all notes).

My total notes were 75MB, which I don't find too much. But i will try to reduce, since also on mobile the delay in "loading notes" is quite significant. Whats the best way to delete a lot of notes?

Also, since this might be an issue for others in future, it would be good to have generated test files with 1000 notes which you can use to debug the applications.

Cheers

**Comment by mobitar** [comment]
Upcoming 3.0.4 update will make improvements in this area.
