### ISSUE TITLE
Spell-checker not working - Win7

### ISSUE THREAD

**Issue by TheHobbit81** [standardnotes/desktop#173]
Running Windows 7 (64bit) with free Standard Notes, plain editor. Spellchecker is checked (green dot/circle) under Menu -> Global Display but it is not underlining the misspelt words.

**Comment by mobitar** [comment]
Might be a Windows 7 issue..will investigate.

**Comment by TheHobbit81** [comment]
I have found that some programs like Discord only support Spell-checkers in Win8 and above. Not sure if that's relevant.

**Comment by mobitar** [comment]
Hmm there might be a reason for that. We're using this: https://github.com/atom/node-spellchecker which says "Windows 7 and below as well as Linux will rely on Hunspell" so sounds like it should be supported.

**Comment by mobitar** [comment]
Spellcheck indeed is not supported on Windows 7.
