### ISSUE TITLE
[Feature Request] Delete notes with delete key

### ISSUE THREAD

**Issue by CharlesCage** [standardnotes/desktop#175]
Thanks, all, for all your work on this wonderful set of apps and functionality!

Would love it if I could "hot-key" delete notes using the Delete key while a note is selected and I'm not editing the note (e.g. when I've clicked directly on the note and not in the editor yet). This is how others work, and I keep habitually trying to do it. :)

**Comment by mobitar** [comment]
Hi @CharlesCage, glad you're enjoying it! This would fall under the general "keyboard shortcuts" request, which is something still on my mind, but have not decided on when time will be allocated for it. Stay tuned..

**Comment by RemiDesgrange** [comment]
Is this prioritized ? I think that this is possible to implement it quite easily right (just the suppress action). @mobitar if you can point code part to me, I can try to make a PR.

**Comment by mobitar** [comment]
It's not about difficulty. This just falls under general keyboard shortcuts, and we're working our way towards that, focus wise.
