### ISSUE TITLE
"There was an error decrypting this item. Ensure you are running the latest version of this app, then sign out and sign back in to try again."

### ISSUE THREAD

**Issue by ImBehindSevenProxies** [standardnotes/desktop#178]
Hello, often i have this problem on my desktop, i need to relog each times, it happened 3 times in a week.

![sans titre](https://user-images.githubusercontent.com/33770395/39375877-19fd54ec-4a50-11e8-83d2-fb5a250e8527.png)

maybe there is some logs that can help you?
Version 2.1.28, win 10 1709
thanks

**Comment by mobitar** [comment]
Strange. Thanks for including the logs. Do you have a local passcode set up on the app?

**Comment by ImBehindSevenProxies** [comment]
oh ok, yeah when i change the passcode it give this error, i have changed this passcode few times this week's hence the issues. thanks

**Comment by mobitar** [comment]
Gotcha. This issue is fixed in version 2.1.29, which will be released today.
