### ISSUE TITLE
Support for Image Uploads?

### ISSUE THREAD

**Issue by inadarei** [standardnotes/desktop#179]
Currently, the only image "support" this app has is Markdown's image URL tag? Which means - images need to be uploaded to a public URL and then linked?

That is not secure. Image is as much part of the content as text is and it should be locally stored/encrypted, just like text is. No? Not to mention to poor UX of managing images somewhere else and then having to link it here.

Thank you

**Comment by mobitar** [comment]
Hey @inadarei, images are not currently supported natively. The only way would be, as you found, to upload to another service and grab the link. Here's an explanation as to why: https://standardnotes.org/help/36/why-are-images-and-attachments-not-supported
