### ISSUE TITLE
Shortcuts for Lists in Plus Editor are not accessible

### ISSUE THREAD

**Issue by nikolayhg** [standardnotes/desktop#180]
**Problem**: currently the shortcuts for (un)ordered lists in the Plus Editor use NUM7 and NUM8, but my keyboard does not have numpad. So I have to switch from keyboard to the mouse. Also with the current shortcuts the user has to switch from the center of the keyboard to the numpad which takes time.

**Improvement suggestion**:
Use only keyboard shortcuts that 1) are on all keyboards (available) and 2) are on the left and in the center of the keyboard (fast access). For example:

- `Ctrl + Shift + O` - ordered list
- `Ctrl + Shift + U` - unordered list

**Comment by mobitar** [comment]
Hey @nikolayhg, good catch. Editors are open source components not developed by us, so while it's good to post issues about them, I will say that it's unlikely we'll be going in and fixing these issues ourselves, given how complex these projects are. The Plus Editor in particular uses Summernote: https://github.com/summernote/summernote/, so your best bet is posting in there directly for a decent chance at a resolution.

**Comment by nikolayhg** [comment]
@mobitar thank you for the clarification!
