### ISSUE TITLE
Remove <div, p, etc tags> from a note overview under "All notes"

### ISSUE THREAD

**Issue by nikolayhg** [standardnotes/desktop#182]
**Problem**: Currently if a note contains html tags like div, p, b, they are shown in the overview of the note under "All notes". But this information is not useful as an overview. Screenshot: https://i.imgur.com/0RF5JEb.png

**Suggested Solution**: Strip away all tags in the overview of a note under "All notes". Add space before every text content after the first found text content.

**Comment by nikolayhg** [comment]
Is it possible for currently active editor to offer/hold the overview and "All Notes" to query the editor for it?

**Comment by mobitar** [comment]
No that's not possible. But even if it were I don't think it would suffice. What if the current editor is Markdown, but HTML notes are shown in the list? We would need to keep all editors in memory in that case..

**Comment by mobitar** [comment]
Makes no difference to me..closing issues can become an unhealthy addiction ;) I treat all issues as discussion forum posts and not necessarily a todo/issue.

**Comment by nikolayhg** [comment]
@mobitar how about hiding the overview of every note? I think this would lead to simplicity. Because most of the time I am not interested in the overview, just the title. Even the tags are too much information for me and would be great if I could hide them too.

**Comment by mobitar** [comment]
Yup, you can do this now:

<img width="289" alt="screen shot 2018-05-17 at 12 52 01 pm" src="https://user-images.githubusercontent.com/3277844/40194759-1ed7f306-59d1-11e8-9afa-75062a2067c1.png">

**Comment by nikolayhg** [comment]
awesome! Thanks!

**Comment by odyon01** [comment]
Hi Mobitar, any idea when hiding Note Preview will reach the android version of SN (maybe like on short/mid/longterm?) Cheers

**Comment by mobitar** [comment]
I'd say somewhere on the mid range. Working on a lot of important architectural stuff right now so the "nice-to-haves" are taking a temporary back seat.

**Comment by odyon01** [comment]
Ok, thanks for the info mobitar

**Comment by mobitar** [comment]
v3 now takes care of this. Be sure to edit your marked up notes at least once so new previews get updated.
