### ISSUE TITLE
Make standard notes available on Chocolatey

### ISSUE THREAD

**Issue by croo** [standardnotes/desktop#186]
Hi, and thanks for the great app! This is a distributional feature request: 
Please make the standard notes windows app installable by chocolatey package manager.

**Comment by mobitar** [comment]
Hey @croo, glad you're enjoying it :) We don't create packages for external package managers, but we do support community maintainers if they're interesting in creating them. Check out the [Alternative Downloads](https://github.com/standardnotes/desktop#alternative-downloads) section in the readme.
