### ISSUE TITLE
[bug] Hitting ctrl+z leads to empty note

### ISSUE THREAD

**Issue by Random2965** [standardnotes/desktop#188]
Sometimes when I hit ctrl+z a couple of times I end up with an empty note. So far it was not a problem because I always had a backup but it would be really nice if someone could fix that.

**Comment by mobitar** [comment]
This is with the Plus Editor, right? This is on my todo. I took a stab at it before but could not find a solution. Will go in with more resolve this time.

**Comment by mobitar** [comment]
Ok this should be fixed now with the latest version of the Plus Editor. (Automatic on web, autoupdate via Extensions menu on Desktop)

**Comment by Random2965** [comment]
Awesome! yeah in plus editor, thanks for taking care of it. I'll check and give you feedback.

**Comment by Random2965** [comment]
Seems like solved, close for now.
