### ISSUE TITLE
[bug] Display same note even when switching

### ISSUE THREAD

**Issue by Random2965** [standardnotes/desktop#189]
Sometimes when I open the app, it keeps on showing me the content of the first note even after clicking a different one. Dunno if it only happens with extension like plus-editor or with plain text editor as well. After restarting the app it works fine again.
Just occurs like once a week, not a big problem, just wanted to report it.

**Comment by mobitar** [comment]
Yeah, I notice this issue like once a month as well. But because it's so rare, it's been very hard to reproduce, so I don't know what the cause of it is. If by chance you're able to replicate this issue consistently, let me know. Have been trying to do the same myself..

**Comment by Random2965** [comment]
As I said it is not a big issue, if I find a way to replicate it I let you know. Anyway, thanks for the feedback.
