### ISSUE TITLE
Support for checklist

### ISSUE THREAD

**Issue by shahankit** [standardnotes/desktop#19]
Apple notes by default stores checklist using markdown syntax for checklist similar to the format discussed here: https://github.com/blog/1825-task-lists-in-all-markdown-documents. However standard notes markdown preview does not allow checklist via same syntax.

**Comment by mobitar** [comment]
Thanks, will take a look to see if it's possible. I'm guessing there would have to be some Javascript involved to edit the content when a checkbox is selected. In that case that might be too custom of behavior.

**Comment by shahankit** [comment]
But currently even the checkbox are not rendered when I provide following plain text:
```
- [ ] task1
- [ ] task2
- [ ] task3
```

This is rather shown as list with the square brackets rendered as is.

**Comment by mobitar** [comment]
How would you envision using this on a day-to-day basis? Because notes are default are presented in plaintext, and you'd have to toggle Markdown preview. Would you just toggle Markdown preview to see which items are completed? But in that case you can just see the `x`s.

**Comment by shahankit** [comment]
I would like to select markdown as default for both viewing and editing (I'm a bit used to with Apple notes). But yeah toggling to markdown preview with Cmd+M and editing checkbox as checked using double click and writing x is also fine to me.

**Comment by mobitar** [comment]
Ok. This will be pretty slow on priority list. Markdown might actually be refactored into an extension. Will keep you updated.

**Comment by shahankit** [comment]
Sure. Is there a guide on how to develop your own custom extensions?

**Comment by mobitar** [comment]
Yes, take a look at these links. Google Drive sync would be great.

Production Dropbox sync ext:
https://github.com/standardnotes/website/blob/master/app/controllers/dropbox_controller.rb

Pretty simple stuff. I'd use that more of a guide, but here's an explanation (needs some updates):
https://github.com/standardfile/standardfile.github.io/blob/master/doc/Extensions.md

**Comment by shahankit** [comment]
Cool I'll try to do that in my free time.

**Comment by netvl** [comment]
BTW, that's how Github Flavored Markdown works. For example:
- [ ] unchecked item
- [x] checked item

Github also allows checking and unchecking these checkboxes without explicitly entering the edit mode.

This would be a very nice feature - no other markdown-based note apps support such a thing, but it would be very convenient.

**Comment by shahankit** [comment]
@netvl apple notes actually does that.

**Comment by mobitar** [comment]
New Markdown editors available here: https://standardnotes.org/extensions
