### ISSUE TITLE
No more .deb option?

### ISSUE THREAD

**Issue by aden-young** [standardnotes/desktop#191]
Up until version  2.1.31 there has been a .deb  package option for this app, which makes it really easy to install on Ubuntu systems.

The last couple of versions have dropped this, which means I haven't been able to upgrade my current install in the same way.

I understand I can use the appimage, however it's nice to have StandardNotes installed in the same way at the other apps on my system.

Are there any issues with maintaining the .deb package format?

**Comment by mobitar** [comment]
Yeah, .deb was removed, mainly because it didn't support autoupdate like the AppImage did, which meant users were always likely to be running an older version. Also, it created more points of maintenance, which is important for us to minimize, given the hundred year outlook.

**Comment by aden-young** [comment]
That's fair, thanks for the reply @mobitar!

**Comment by Cauchon** [comment]
@mobitar I'd like to chime in and express some disappointment. I use a Pixelbook with a Linux container (in ChromeOS dev channel, will launch later) and AppImages are not yet supported. As an avid user of Standard Notes, the only other option is to use the Android app on my laptop.

The old deb file was working well until today when I had to re-encrypt my notes and it's saying it's no longer compatible with the older version.
