### ISSUE TITLE
Warning/guidance with the security update when having 2  or more desktop SN applications

### ISSUE THREAD

**Issue by jaco-l** [standardnotes/desktop#192]
I updated my Windows SN desktop version to 2.2.0 and then noticed a message offering a 'security update'. This update re-encrypts your hosted notes and it all went well.

Then, I moved over to update my Linux SN desktop version to 2.2.0 also. After updating, the same 'security update' link was shown and I clicked it here too. However, it fails by rejecting your 'password/credentials'. I feared that I had forgotten my password memory somehow, but it turns out to be a bug. You don't actually need to do the security update on your second desktop client too. Just logout (from your account on the SN server, not your client) and login again.

**Comment by mobitar** [comment]
Hey, step 2 of the upgrade process should have told you to sign out on all devices before proceeding. Did you do this and still saw this issue?

**Comment by jaco-l** [comment]
I did see the warning message, but now I realize I did not fully and 100% check if I was signed out from the first Windows SN. Let's assume I had it still running, so it's my mistake to not really heed the warning message. I will close the issue again.

**Comment by mobitar** [comment]
No worries, yeah, the only way to get the update synced to other devices is to sign out and sign back in.
