### ISSUE TITLE
Cancel button as default action on delete confirmation

### ISSUE THREAD

**Issue by erlangp** [standardnotes/desktop#194]
Cancel button as default action on delete confirmation

**Comment by mobitar** [comment]
Afraid this is the default behavior of Javascript's `confirm`. We'd need to build our own alert replacement if we wanted to customize this.

**Comment by virtuallyvlad** [comment]
More important given there's no recently deleted bin, nor can deletion be undone, as far as I know.

+1

**Comment by mobitar** [comment]
Trash bin is planned for a near-future release.

**Comment by mobitar** [comment]
Trash bin available in 3.0.3.
