### ISSUE TITLE
Title is reset when new note is created offline

### ISSUE THREAD

**Issue by jceb** [standardnotes/desktop#197]
I noticed that the title of a new note is reset to "New Note XXX" every once in a while if it's created offline.  As a workaround I discovered that changing to a different note makes StandardNotes "save" note's title properly.

**Comment by mobitar** [comment]
So do you create a new note, then type some letters into the title field, and then those letters just disappear and it reverts to the default text?

Also, by offline do you mean using it without an account, or with an account but without a connection?

**Comment by jceb** [comment]
Yes, exactly, the title is rest.  Today, I noticed that the tags are also reset.

I use standard notes with an account but without internet connection.

I use the latest version, 2.2.4 with the vim plugin.

**Comment by mobitar** [comment]
Hmm that's very bizarre. Can't seem to replicate this issue. If you can capture a screen recording that's always helpful. Usually there's some small detail that helps me understand why it's happening. Otherwise, will have to wait for more user reports.

**Comment by jceb** [comment]
Right after I created this new note a popup appeared that informed me that there were issues uploading the note.  After that I started recording: https://www.youtube.com/watch?v=JyGi_6xSvo8

**Comment by jceb** [comment]
Oops, yes, the video was private.  Changed the visibility

**Comment by nickAtWybar** [comment]
fyi I encounter this every now and then as well. Sometimes I just have to try again 2-3 times and it eventually works.

**Comment by mobitar** [comment]
Hmmm...interesting. Never experienced this before. Unable to replicate it either. @nickAtWybar are you using an editor extension when this happens? Or just the plain editor?

**Comment by nickAtWybar** [comment]
@mobitar interesting, your hunch was correct. When I create new notes in offline mode in the Advanced Markdown Editor, the title resets itself when moving onto the body of the note (back to "New Note X"). When I attempt this in a plain editor note, the title stays to what I define it as. Note, I only tried this a couple times, but it did seem consistent.

**Comment by mobitar** [comment]
Hmm still can't replicate it. I'm testing using the 2.3.0 beta though. Perhaps it's fixed in there? https://github.com/standardnotes/desktop/releases/tag/v2.3.0-beta2

**Comment by nickAtWybar** [comment]
@mobitar indeed it does seem to be fixed (using 2.3.1)...

**Comment by mobitar** [comment]
Ok great!

**Comment by jceb** [comment]
Works also fine for me!  Thank you for fixing it!
