### ISSUE TITLE
Add Note Hierarchy

### ISSUE THREAD

**Issue by justanothergenericuser** [standardnotes/desktop#20]
Please add note hierarchy support. This is literally the only thing that stops me from using this.
Look at the left side of the screenshot for an example of what I mean. 

![look at the left side for example](https://cloud.githubusercontent.com/assets/25201615/22066921/240967fa-dda0-11e6-9764-69200f197b38.png)

**Comment by mobitar** [comment]
Isn't this just like tags? What's wrong with tags for hierarchy?

**Comment by justanothergenericuser** [comment]
Well let's call hierarchy "notebooks" for a second. If I use seperate notebooks for physics and chemistry, but tag the notes that have information about atoms with the tag "atom", it just shows me results from both my physics notebook and chemy notebook. I mean, I can't seperate the topics in an efficient way.

**Comment by mobitar** [comment]
What if you tagged the note both chemistry and atom, and then can search based on multiple tags?

**Comment by mobitar** [comment]
The thing is, you can expect the "brand name" Standard Notes to remain pretty standard. However, since all of this is built on open software and documented methods (that being Standard File), anyone can build their own notes client that offers an unlimited array of functionality. But I hope you understand that in order for this project to survive, it needs to pack lightly and be nimble.

**Comment by justanothergenericuser** [comment]
That might work, but then on the main screen all the notes would be mixed up. All the topics together and probably sorted by last edited. Seperate views for seperate notebooks would be ideal. 
An example of this is OneNote actually, it has a default notebook called "Quick Notes" where all non-categorised notes are and you can add another notebooks as you wish for seperating them by topics.

**Comment by justanothergenericuser** [comment]
Ok, I understand. Thanks.

**Comment by mobitar** [comment]
Interesting. This creates for complex file formats as well though, again leading to decreased sustainability. The best case scenario here is for this project to be popular enough that others start developing clients for it that offer custom functionality. When those projects are then abandoned, users aren't totally screwed since they can come back to this more simple client.

**Comment by justanothergenericuser** [comment]
What if you kept the order for the hierarchy in another file? When the app starts it can read the hierarchy from that file and show notes in order. No need for fiddling with the file format.

**Comment by mobitar** [comment]
Possibly, through extensions. But still a long shot.

**Comment by admiral-Guck** [comment]
I'm very much in favour of multiple tag search, through a filter thing like for note search. It may be not be part of the note basics as you outline them, but I believe not having efficient search is a main drawback of physical notes, so not having it makes digital notes kinda useless (physical notebooks can be as private as it gets, will always be human-readable and provide much bigger expressive freedom than the keyboard).
Things like nested tags (i.e. folders) should of course be left to extensions.

**Comment by leafcutterant** [comment]
Please, please develop this functionality. Very much needed.

**Comment by mobitar** [comment]
The [Folders](https://standardnotes.org/extensions/folders) extension does hierarchy.

**Comment by leafcutterant** [comment]
The Folders extension is a step forward, but to "convert" your *notes* to a hierarchy (and not your *tags*), you need to tag every note with the same string as their title, pay attention to not use a note name twice, and hide the notes sidebar (which means you need to change the layout every time you want to search or create a new note).

**Comment by bryvin** [comment]
I'm a little confused I guess. The folders extensions does seem to allow any functionality that you are describing the same as a traditional folder setup would. You can have multiple tags on each item, and for each tag a certain note has it will appear in both sections. This combined with [Smart Tags](https://standardnotes.org/help/42/how-do-i-view-a-list-of-untagged-notes) which can used to filter items specifically by certain queries of your choosing seems to be possibly a superior option to the traditional folders. These tags are also always relative to the parent and can be separate by a period.

For example these 2 personal and business 'folders' will have completely separate notes:

- banking
     - personal --- tag being: banking.personal
     - business --- tag being: banking.business
- notes
    - personal --- tag being: notes.personal
    - business --- tag being: notes.business

I think something mobitar also has planned for the future is hot keys and making it a little more streamlined so you can more easily do some of the more basic functionality.
