### ISSUE TITLE
After startup, notes are not always updated after clicking on notes in list

### ISSUE THREAD

**Issue by odyon01** [standardnotes/desktop#200]
I had it now a couple of times: I opened SN on win10, and I scroll to the bottom of my first pinned note (which it shows by default), and I see the last lines are missing. Surprised (and a bit scared of losing my text), I quickly click on another note and this one doesn't show up. None of the notes I click on are displayed. 

Solution so far:
- Restarting SN solves the problem, and the note is updated with all the lines I added via the android app. And I can click on other notes.
- I remember disabling the plus-editor also solved the issue (although I have to try again to confirm).

Is this a known issue, @mobitar ? Any suggestion what I can do when I'm again in that situation to collect more info how / why it happens (debug data or so?)

**Comment by mobitar** [comment]
Hmm..the app should sync immediately on launch. Do you know what the state of the app is when you launch it—was it existing in the background, was it minimized, or is a fresh launch?

Also, have you tried clicking the Refresh button in the lower right corner when this happens? This will trigger a force sync.

**Comment by mobitar** [comment]
Oh you know what. If this is using external editors like the Plus Editor, then there is currently this very rare issue that I am struggling to reproduce where the note contents are updated, but they are not communicated to the editors. Version 2.2.5, which was released yesterday, has some improved handling for this, and should display an alert if this happens, so this way you're at least notified. Try updating to this, and let me know if you see this issue again.

**Comment by odyon01** [comment]
Ok, updated. I'll let you know if it happens again!

**Comment by mobitar** [comment]
What do you mean "SN is switching super-fast between Plus-editor 1 and 2"?

**Comment by odyon01** [comment]
Please find in the attachment a screenrecording. I do have the Folder-extension, but it's deactivated.

[2018-07-12 20-50-34.zip](https://github.com/standardnotes/desktop/files/2189896/2018-07-12.20-50-34.zip)

**Comment by mobitar** [comment]
Woah! Not sure why that's happening. Can you uninstall one of the editors from the Extensions menu and see if that helps?

**Comment by odyon01** [comment]
Ok, could have checked this before:

![2018-07-12 21_07_36-notes](https://user-images.githubusercontent.com/7446891/42654137-e72fc17c-8617-11e8-9ff7-738370274620.png)

No idea how I got two instances... Maybe a failed update of the extension or so. 

I uninstalled one of the 2, switched the remaining one to default, and now I don't see the bridge message anymore.

**Comment by mobitar** [comment]
Ok cool. Let me know if you see this issue again.
