### ISSUE TITLE
case-sensitive Tags & tag renaming

### ISSUE THREAD

**Issue by bagodoosh** [standardnotes/desktop#202]
i'm combining two entries here:

1) enhancement: tags are case-sensitive. i.e. "water" is a different entry (in the Tags list) than "Water". i think it would make sense to make tags case-insensitive. (since Search is case-insensitive)

2) issue: when renaming a tag containing uppercase to an existing lowercase tag, they become two identical yet separate tags. i.e. create #water. create #Water. rename "Water" to "water" (in the Tags list). now there exists two separate tag entries both named "water".

**Comment by mobitar** [comment]
Yeah..currently tags are not validated for duplicates. Probably would be a good idea to do so. For case sensitivity, I don't think we want to assume lowercase everything. Especially with sorting. #Water will be sorted in the beginning of the tags, whereas #water will be sorted at the end.

**Comment by Txeni** [comment]
If its worth anything, the way I use folders and tags right now I love the case sensitivity and the fact that lower case versions are sorted at the end.
All my "folders" start with a capital letter, my "tags" start with lower case, that way I can use both without the list getting really messy.
Please don't change that! :)

**Comment by mobitar** [comment]
@Txeni interesting use case. In your workflow, what's the difference between a folder and a tag, if they're both represented by similar interface objects?

**Comment by Txeni** [comment]
@mobitar I use the "folders" to group my notes in regards with "projects" or context in which I'm working on something. I'm doing a PhD and I would have a folder for a specific paper or an article I'm writing. Then I use "tags" to point themes that appear in each of the singular notes, with the hope that they will help me to find them later. Those tags would be things like 'python', 'statistics', 'semantics'... etc
