### ISSUE TITLE
Notes app force closes on android, when opening certain links

### ISSUE THREAD

**Issue by odyon01** [standardnotes/desktop#204]
**Issue**
Notes app force closes on android, when opening certain links

**Reproduction scenario**
1. Create new note
2. Enter title
3. Enable Plus editor
4. Copy paste following link: https://tweakers.net/pricewatch/1124369/scythe-kotetsu-mark-ii.html
5. Press enter. Plus editor converts link to active hyperlink
6. Click on link, and in popup click on "go-to"-link.
7. The page opens using webview 4, but very quickly I get a android message that Notes has crashed.

**Device**
Android 8.1.0, 
SN-version: 2.3.2

**Comment by mobitar** [comment]
Hmm strange. Can you create this issue on the [mobile repo](https://github.com/standardnotes/mobile), so I can keep it as a todo?

**Comment by odyon01** [comment]
Ok, done: https://github.com/standardnotes/mobile/issues/71

You can close this one then I suppose.

**Comment by mobitar** [comment]
Thanks!
