### ISSUE TITLE
Gone from taskbar after update

### ISSUE THREAD

**Issue by s0ftwhere** [standardnotes/desktop#205]
[moved from /forum to /desktop] 

Hello @mobitar ,

Not sure if this is an issue or expected behavior but every time I update Standard Notes on Windows 10 the app disappears from the taskbar and I have to pin it again.

Regards.

**Comment by mobitar** [comment]
I think I've heard this before. Will have to investigate.

**Comment by mobitar** [comment]
Grouping into https://github.com/standardnotes/desktop/issues/228
