### ISSUE TITLE
Malicious Window Program (False Positive)

### ISSUE THREAD

**Issue by antuketot76** [standardnotes/desktop#207]
@mobitar 
Below some analysis that I have done to desktop application for window platform.
Maybe this is false positive detected AV company, need clarify this for file/program intergrity

The file link was [HERE](https://github.com/standardnotes/desktop/releases/download/v2.3.2/standard-notes-setup-2.3.2.exe)
VirusTotal - [HERE](https://www.virustotal.com/#/url/bb4df38f7e81584e628973f4e83200b94b8efc7315c15ba759e2d18ec67ea638/detection)
Hybrid Analysis - [HERE](https://www.hybrid-analysis.com/sample/c17ac4abdec889f9bdcbf9c9a6144672da18ea5334fa84a34a4f2300f96610c2/5b61b3be7ca3e1224570b228)

![image](https://user-images.githubusercontent.com/33280865/43526420-287e6864-95df-11e8-961b-d5daf26e6239.png)

**Comment by mobitar** [comment]
False positives are a common part of antiviruses not being overly familiar with a file.
