### ISSUE TITLE
Plus Editor Issues

### ISSUE THREAD

**Issue by infosisio** [standardnotes/desktop#208]
The Plus editor has the potential to be really convenient but it needs some tweaks and additions imo.

1) When you format some text in the Plus editor, in the left note list preview panel, you see the html tags in the summary of the entry which looks bad.

2) If you then switch from Plus to simple editor, it keeps the html tags, it should revert them.

3) It would be amazing if Plus editor had code syntax highlighting like all the post editors in Forums have. No need to switch between markup and Plus just to put a quick snippet.

Thanks a lot - I look forward to hearing your thoughts.

**Comment by mobitar** [comment]
Number 1 and 2 are very widely known limitations. No way around them for now. 

For 3, the Plus Editor is based on the open source editor Summernote. So it's unlikely we'll be modifying this ourselves. See here for more: https://github.com/sn-extensions/plus-editor/issues

**Comment by leafcutterant** [comment]
No. 2. is not only bad (like bad but avoidable if you know about it), but even unavoidable if your subscription expires. Then I presume the only editor remaining will be the Plain Editor and all your notes that used Plus will become ugly HTML.

**Comment by leafcutterant** [comment]
I can achieve optimal reduction (formatted HTML text -> plain text) by copying the note's contents in Plus to the clipboard, switching to Plain,  and pasting the clipboard to Plain. I thought that if I can do that, then there's probably a way to achieve that on a code level.

**Comment by mobitar** [comment]
In the near future, expired extensions will become read-only, rather than being obstructed altogether.
