### ISSUE TITLE
I cannot build this

### ISSUE THREAD

**Issue by infosisio** [standardnotes/desktop#210]
I have success with getting this to build with npm run start but when I try with the Electron packager the application starts but the contents of the window are just blank.

**Comment by mobitar** [comment]
Can you post a screenshot of the dev console output? Help -> Toggle Error Console

**Comment by infosisio** [comment]
Failed to load resource: net::ERR_FILE_NOT_FOUND
compiled.js Failed to load resource: net::ERR_FILE_NOT_FOUND
index.html:73 Uncaught ReferenceError: angular is not defined
    at index.html:73

**Comment by mobitar** [comment]
Will investigate. In the meantime, go back to an earlier commit and try again. 

`git checkout 900d9496f1c013693998c8d74cb8a9d4fa40830c`

**Comment by infosisio** [comment]
@mobitar index.html is actually blank

**Comment by infosisio** [comment]
@mobitar It seems to be not extracting the resources, I don't understand why this is happening.

**Comment by infosisio** [comment]
I just build 2.1.0-beta2 with success so it's for sure an issue with latest version. It is not extracting the resources of the app. I am on Ubuntu 18.04 64 bit by the way.

**Comment by mobitar** [comment]
Should be fixed now. Try `git pull` then `npm run dist-win` (or dist-mac, dist-linux)
