### ISSUE TITLE
Change CSS of Simple Markdown Editor

### ISSUE THREAD

**Issue by infosisio** [standardnotes/desktop#214]
I have tried really really hard to make a tiny change to the CSS of Simple Markdown Editor and rebuild using webpack but have unfortunately failed.

How is this done ? My issue is with applying line-height, I added a note here as it really annoys me and I can't use it as it is: https://github.com/sn-extensions/simple-markdown-editor/issues/3

Thanks a lot !

**Comment by mobitar** [comment]
What have you tried? I can help you if you let me know where it failed for you.
