### ISSUE TITLE
Search Refresh Bug Noticed

### ISSUE THREAD

**Issue by infosisio** [standardnotes/desktop#215]
I noticed a bug with search. When you load the program for the first time and you search for an existing note, you see it perform a hard refresh. Then if you clear and perform the same search, it doesn't perform that hard refresh which is the most visually pleasant behaviour.

**Comment by mobitar** [comment]
Not sure I know what you mean. What do you mean by hard refresh?

**Comment by infosisio** [comment]
@mobitar Try to start standardnotes and search for things, you will see that a refresh happens in the list, the top entry gets re-selected. Then if you search again, it won't happen again. It only happens the first time.

**Comment by mobitar** [comment]
Still not seeing what you mean. If I search, whether it's the first or second time, the first item is always selected.

**Comment by infosisio** [comment]
@mobitar If you search for the first time and pay attention to the first note in the new list of search results, you will see that the first note gets re-selected. You see the blue highlighting to re-activate, go away and come back again. Then the second time, you don't see that happening, you see it always blue, no refresh or reselection, which is the right, smooth behaviour.

**Comment by infosisio** [comment]
@mobitar I figured out the issue:
```
    this.filterTextChanged = function() {
      $timeout(function(){
        if(!this.selectedNote.visible) {
          this.selectFirstNote(false);
        }
      }.bind(this), 100)
    }
```
If you change this to:
```
    this.filterTextChanged = function() {
      $timeout(function(){
        if(!this.selectedNote.visible) {
          this.selectFirstNote(false);
        }
      }.bind(this), 0)
    }
```
It goes away

**Comment by infosisio** [comment]
@mobitar I don't get this, changing this solved the issue for the web version but it's the same behavior in desktop. Why could that be ?

**Comment by infosisio** [comment]
@mobitar It seems that the desktop version refuses to accept the value of the timeout to be zero and there has to be a delay. If you remove the timeout, then the command does not get to execute...

**Comment by mobitar** [comment]
I'm still not seeing what you mean tbh. Testing both cases results in the same visual behavior. If you can provide a gif or video, that might be helpful.

**Comment by infosisio** [comment]
@mobitar I tested this on a bunch of computers with different distros (even Windows).
It happens everywhere.
Let me write the steps so that you can reproduce it too.
1. Open StandardNotes Desktop Normally. (and log in your account to load your notes)
2. Click on the Search bar then search for something that has matches.
3. Pay attention to the first entry and see the transition between no-highlighting and blue highlighting.
(You see it blink)
4. Now clear the search and search for something new.
5. You will not see a transition this time, you will see it as blue instantly.
If you close StandardNotes desktop and open it again, you will see the same.

**Comment by mobitar** [comment]
I see. Very subtle, but perhaps worthy of fixing nonetheless. I'll keep this in the backlog for when I'm working on small bug fixes.

**Comment by baptiste-grob** [comment]
Closing as the behavior has changed since then
