### ISSUE TITLE
Ideal Clear Search Behavior

### ISSUE THREAD

**Issue by infosisio** [standardnotes/desktop#218]
Right now when you click the "x" icon to clear your search query and view everything again, what is highlighted/selected is the note you've been viewing before clicking that button. Does it make more UX sense to make that reset back the selection to the first entry since that is what happens when you modify the search query ? @mobitar what is your view ?

**Comment by mobitar** [comment]
Might make sense to remember that selection. Just needs more code to do that. Not a high priority issue for me though, so probably will defer to a PR contribution.
