### ISSUE TITLE
Ability to Drag & Drop to Change Order of Notes

### ISSUE THREAD

**Issue by infosisio** [standardnotes/desktop#219]
This may not be incredibly useful or whatsoever but it is very intuitive, especially for newcomers. 

Basically by drag & dropping the note entries, the program could trigger a "custom" sort-by option.

@mobitar I'd like to hear your thoughts on it.

**Comment by mobitar** [comment]
This would require introducing a new field on all notes, like "sortPriority", and then rearranging a bunch of UI and code to respect that in certain conditions. Very complex feature and unlikely to be added.
