### ISSUE TITLE
Offline database issue: undefined error

### ISSUE THREAD

**Issue by yohanmishkin** [standardnotes/desktop#22]
Seems to happen every time the application wants to sync.

![image](https://cloud.githubusercontent.com/assets/7291324/22118623/8a3ad602-de46-11e6-93a8-2a21cb81f99a.png)

**Comment by mobitar** [comment]
Can you post this comment here https://github.com/standardnotes/desktop/issues/12 and I'll close this one.

**Comment by yohanmishkin** [comment]
Complete
