### ISSUE TITLE
Scroll bars are difficult to precisely grab/drag

### ISSUE THREAD

**Issue by virtuallyvlad** [standardnotes/desktop#222]
On my desktop app, in Windows 7, the scroll bars are a bit tricky to actually select and drag.  Aside from being quite narrow and difficult to see, the scroll bar itself has a very narrow selection area before the cursors picks up the panel resizer to the right of it.  Far too many times I end up selecting the resizer instead of the scroll bar.

**Comment by mobitar** [comment]
Hope to adjust this in a future update..

**Comment by virtuallyvlad** [comment]
Looks like v2.3.4 has resolved this -- thanks!
