### ISSUE TITLE
Window Resize Glitch On Elementary OS

### ISSUE THREAD

**Issue by ghost** [standardnotes/desktop#223]
This is probably of limited importance, but I must report it.

On Elementary OS, if you resize the Standard Notes window there is some kind of glitch - you see black background on the edges while this is done.

UPDATE: This happens with the Atom editor as well, it may have to do with Electron.

**Comment by mobitar** [comment]
Yup, I've seen this issue before and is indeed an Electron issue. I believe the last time I looked into this there weren't any solutions..
