### ISSUE TITLE
Activation of Action Bar is Glitchy  

### ISSUE THREAD

**Issue by infosisio** [standardnotes/desktop#224]
I bet you have noticed this but I had to mention it, it becomes noticeable once you start relying on it daily.

**Comment by mobitar** [comment]
I would have expected a more detailed report from you than "glitchy" ;) Have no idea what you're referring to..

**Comment by infosisio** [comment]
@mobitar Sorry for the lack of description, I thought you had it in mind. :D 

Basically you see the activation bar to kinda jump to get placed to its position.

**Comment by mobitar** [comment]
Still need platform, browser, version, video, gif, screenshot, etc. I don't see this at all.

**Comment by infosisio** [comment]
@mobitar Linux, Ubuntu 18.04 desktop version. I am leaving home now, can't send screenshot.

**Comment by mobitar** [comment]
Improvements in this area in v3.
