### ISSUE TITLE
Offline Decryption Script Error

### ISSUE THREAD

**Issue by petermierau** [standardnotes/desktop#226]
The offline decryption script doesn't work with passwords that contain special characters such as !@#$%^&*(){}_+-=

Steps to reproduce the problem:

    Create a password that contains 1 or more special characters

    Use the offline decryption script to attempt to decrypt an encrypted sn backup with above password

    Open the browser console and the errors should be there

The same password works fine for the SN client to login.

It gives the following error more than 100 times:

    17:37:05.179 Error decrypting: DOMException: "String contains an invalid character" Notes_Decryption_Script.html:124:15

onKeyReady

file:///home/path/to/file/Notes_Decryption_Script.html:124:15

decryptFiles/readNext</reader.onload</<

file:///home/path/to/file/Notes_Decryption_Script.html:151:13

value/<

file:///home/path/to/file/Notes_Decryption_Script.html:245:946

value/<

file:///home/path/to/file/Notes_Decryption_Script.html:245:2542

value/</<

file:///home/path/to/file/Notes_Decryption_Script.html:245:2844

value/<

file:///home/path/to/file/Notes_Decryption_Script.html:245:3479

Please tell me if you need any help or further information.

PS. I wasn't able to find the github repository that had this Offline Decryption Script. So I lodged the bug report here. I'm sorry for any hassle caused.

**Comment by sapphireloyalty** [comment]
Sorry, the formatting is wonky, I can't seem to fix it.

**Comment by mobitar** [comment]
Hmm very strange. And you're sure it's the password and not the underlying data? Can you try with a regular password but with the same data and see how that goes? Repo is here btw: https://github.com/standardfile/decrypt
