### ISSUE TITLE
Text contrast and font weights could be improved when using dark themes

### ISSUE THREAD

**Issue by adlersantos** [standardnotes/desktop#227]
I'm a big fan of dark themes. But when using them for Standard Notes on Mac/Windows/Web, the text contrast makes some areas of the code barely readable. Also, the fonts and font weights are not consistent, some parts of the code use non-monospaced fonts (see "import", "class", and "return" in codes below) while other parts use monospaced fonts that seem to be a different font.

Some examples below for the Midnight, Solarized Dark, and Focus themes:

<img width="519" alt="screen shot 2018-08-28 at 10 46 17 am" src="https://user-images.githubusercontent.com/1208372/44730774-b1930080-aaaf-11e8-8a60-8518115debb2.png">
<img width="458" alt="screen shot 2018-08-28 at 10 46 32 am" src="https://user-images.githubusercontent.com/1208372/44730775-b1930080-aaaf-11e8-921b-cf92053f5199.png">
<img width="493" alt="screen shot 2018-08-28 at 10 46 47 am" src="https://user-images.githubusercontent.com/1208372/44730776-b1930080-aaaf-11e8-965e-b055d4db09db.png">

I'm defaulting to not using any themes for the meantime, because code is displayed properly for that.

<img width="499" alt="screen shot 2018-08-28 at 10 47 29 am" src="https://user-images.githubusercontent.com/1208372/44731220-b60be900-aab0-11e8-9c64-46a04797344c.png">

**Comment by mobitar** [comment]
This is very tricky for us because of how difficult it is to stylize every single editor and syntax highlighting to support every theme. So, for now, you'll get a less than 100% experience when using themes with external editors, as themes are firstly optimized with the base editor in mind. Not sure there's a way around this without mass community involvement, as it's definitely a never-ending task.

**Comment by triangulum** [comment]
Aye, I noted this issue fairly quickly too, once I started using some of the darker themes.

Related: what is a standard indent in Standard Notes? A <kbd>Tab</kbd> is different to a <kbd>Cmd</kbd>+<kbd>]</kbd>.

![screen shot 2018-11-25 at 10 40 20 pm](https://user-images.githubusercontent.com/22440652/48978672-269fc180-f103-11e8-9ac9-a65d49c3c93f.png)
![screen shot 2018-11-25 at 10 40 33 pm](https://user-images.githubusercontent.com/22440652/48978673-269fc180-f103-11e8-902c-538996b4f396.png)

**Comment by triangulum** [comment]
And it's worth noting, this [Better Solarized Dark](https://github.com/swalladge/sn-themes) theme seems to be more consistent with the default theme!

> Dark solarized theme, based on the official Midnight theme. Uses mainly official solarized colours, tweaked slightly for greater contrast and visibility on mobile. Features proper solarized code syntax highlighting in editors.

**Comment by mobitar** [comment]
The best way to contribute to themes is just to submit a PR to the repos: https://github.com/sn-extensions/midnight-theme

**Comment by mobitar** [comment]
Should be much improved in recent releases.
