### ISSUE TITLE
More than 170 emoji are currently not correctly rendered on Windows 10

### ISSUE THREAD

**Issue by raearispa** [standardnotes/desktop#229]
**OS:** Windows 10 April 2018 Update (aka 1803)
**App version:** 2.3.4

While most Windows 10 emoji are correctly rendered by the Standard Notes app for Windows, some 177 of them are displayed in black and white and with a design that is not the current Windows 10 emoji design.

Is anyone else on Windows 10 having the same problem?
I know it's not a big issue, but it makes using emoji way less interesting/useful, and I'd very much like to be able to see this fixed.

What follows is a visual explaination of what I'm writing about...

### **The emoji in question:**

☺ ☹ 🗣 👁 🕶 ⛑ ☂ 🐿 🕊 🕷 🕸 🏵 ☘ ☀ ☁ ⛈ 🌤 🌥 🌦 🌧 🌨 🌩 🌪 🌫 🌬 ☂ ❄ ☃ ☄ 🌶 🍽 ⛷ 🎗 🎟 🎖 ⛸ 🏎 🏍 🏔 ⛰ 🏕 🏖 🏜 🏝 🏞 🏟 🏛 🏗 🏘 🏚 ⛩ 🏙 🛤 🛳 ⛴ 🛥 ✈ 🛩 🛰 ⛱ ☠ 🕳 🛍 🗺 🛢 🛎 🕰 🌡 ⛱ 🕹 🖼 🎙 🎚 🎛 ☎ 🖥 🖨 ⌨ 🖱 🖲 🎞 📽 🕯 🗞 🏷 ✉ 🗳 ✏ ✒ 🖋 🖊 🖌 🖍 🗂 🗒 🗓 🖇 ✂ 🗃 🗄 🗑 🗝 ⛏ ⚒ 🛠 🗡 ⚔ 🛡 ⚙ 🗜 ⚖ ⛓ ⚗ 🛏 🛋 ⚰ ⚱ ❤ ❣ 🗯 ♨ ♠ ♥ ♦ ♣ ⚠ ☢ ☣ ⬆ ↗ ➡ ↘ ⬇ ↙ ⬅ ↖ ↕ ↔ ↩ ↪ ⤴ ⤵ ⚛ 🕉 ✡ ☸ ☯ ✝ ☦ ☪ ☮ ⏏ ♻ ☑ ✔ ✖ ✳ ✴ ❇ ‼ ⁉ © ® ™ #️⃣ 0️⃣ 1️⃣ 2️⃣ 3️⃣ 4️⃣ 5️⃣ 6️⃣ 7️⃣ 8️⃣ 9️⃣ ℹ 🏳

### **How emoji on Windows 10 should be displayed:**

[https://emojipedia.org/microsoft](https://emojipedia.org/microsoft)

### **Two Windows 10 apps (the built-in Mail app and the Appy Text app) seen here correctly displaying most of them:**

![screenshot 1799b](https://user-images.githubusercontent.com/30185056/44946839-f5656d00-ae03-11e8-8b18-10d796042e5c.png)

### **How Standard Notes currently renders them:**
![screenshot 1799c](https://user-images.githubusercontent.com/30185056/44946752-81769500-ae02-11e8-883c-4ff2b481c59d.png)

**Comment by mobitar** [comment]
I looked into this briefly some weeks ago and found that on Windows, a simple HTML <textarea> has this issue, which is what we inherit from. Wasn't able to find a solution. But you can test this on something like codepen.io with a simple <textarea></textarea> and you'll see the same issue. Need to spend more time investigating.

**Comment by baptiste-grob** [comment]
Looks like _most_ of these are fixed now! 
![image](https://user-images.githubusercontent.com/60621355/81926631-897c6580-95e2-11ea-81a1-f22c217aebfc.png)
What's interesting is that if you enter the emojis using Windows' emoji selector (Win+;) then it displays the emoji correctly. You can try it with 😊!
We're making sure to keep up with Electron's latest releases, which is all we can do. I hope they fix pasting in this one => 😊
