### ISSUE TITLE
New Note Issue

### ISSUE THREAD

**Issue by infosisio** [standardnotes/desktop#231]
When you first install standardnotes, then login to your account, it adds to the list the default empty note.

**Comment by mobitar** [comment]
Does that note persist and sync? It should only be a dummy note that's not actually saved unless you modify it.

**Comment by infosisio** [comment]
@mobitar Yes it does.

**Comment by mobitar** [comment]
Thanks, will investigate.

**Comment by virtuallyvlad** [comment]
Wonder if it would be any better to avoid auto-creating the initial note in the first place.

**Comment by mobitar** [comment]
It's a "get right into it" mentality. Otherwise the app will start really really blank and confusing.

**Comment by mobitar** [comment]
Behavior related to this has been improved in recent releases.
