### ISSUE TITLE
Windows 10 Right Click no longer displays Context Menu

### ISSUE THREAD

**Issue by rmacm** [standardnotes/desktop#233]
When using the desktop application for Windows 10 right clicking to display the context menu with actions like Copy, Paste etc no longer works.

I'm using version 2.3.5 and it was working ok in 2.3.4

**Comment by mobitar** [comment]
Can confirm this is a known issue. Although I don't believe it has worked in any previous version either..

**Comment by rmacm** [comment]
:) that could be possible.  I can try an earlier version tomorrow just to be certain.

**Comment by rmacm** [comment]
![2018-09-16 22_49_21-greenshot](https://user-images.githubusercontent.com/11667077/45600799-f2bd6700-ba02-11e8-8f1a-2a873c998300.png)

Done with version 2.3.4

**Comment by laserswift** [comment]
Same issue on linux, app version 2.3.5

**Comment by mobitar** [comment]
And is this on the plain editor, or using an editor extension? The context menu will likely not appear using any editor extension, but should appear using the plain editor.

**Comment by rmacm** [comment]
I'll check when I get home tonight but 99% certain it's the plain editor.

**Comment by rmacm** [comment]
Hi, can confirm using the plain editor.  Problem still present in 2.3.6.

**Comment by rmacm** [comment]
I think this can be closed.  In 2.3.8 it is working fine.

**Comment by mobitar** [comment]
Yes, fixed in 2.3.7 :)
