### ISSUE TITLE
Undo/Redo does not scroll back to the relevant location

### ISSUE THREAD

**Issue by virtuallyvlad** [standardnotes/desktop#235]
In the Windows app, if an undo/redo is done that affects text above or below the current visible area, the note does not scroll to the relevant location.

The cursor does seem to jump to the relevant text, but not having the window scroll there means you won't be able to see what is actually being changed.

**Comment by mobitar** [comment]
We just use an HTML textarea for the plain editor, and this functionality isn't supported out of the box. Unlikely we'll add code for this ourselves, but worth looking in to.
