### ISSUE TITLE
Note will sometimes jump to the end while editing/typing

### ISSUE THREAD

**Issue by virtuallyvlad** [standardnotes/desktop#236]
In the Windows app, editing a note sometimes causes the cursor and scroll position to jump to the end of the note.

I haven't been able to pinpoint what exact keys/actions cause this, but thought I should include in case anyone else is experiencing this as well.  Will update if/when I notice a pattern.

**Comment by mobitar** [comment]
Hmm..what version of the app is this? Also, are you using the app with an account or without an account? And what are your network conditions like?

**Comment by virtuallyvlad** [comment]
v2.3.4 on Windows, with an account.  Pretty stable network - hardwired broadband - and I believe SN has always continued syncing even when this occurs.

It typically happens while editing/typing, so half of whatever I was typing will end up at the end of the note.  This quirk, combined with undo/redo not scrolling back to place (https://github.com/standardnotes/desktop/issues/235), makes it a little tricky to correct whatever you were in the middle of doing.

**Comment by mobitar** [comment]
I forgot to ask—what editor are you using when this happens? Plain editor, or one of the editor extensions?

**Comment by virtuallyvlad** [comment]
Plain editor

**Comment by mobitar** [comment]
Strange. We had issues with this over a year ago, but have since been fixed. I haven't heard about it again until now. We'll keep this issue open and see if anyone else is experiencing this.

**Comment by virtuallyvlad** [comment]
On at least one occasion it seems to have been prompted by me hitting the TAB key in order to indent the line.  But it doesn't consistently cause it.  Once I scroll back up, tab will work as normal.

**Comment by bryvin** [comment]
I have not personally experienced this.. but it sounds like it could be an issue with tab going to the next element on the page and not keeping the focus of input for some reason. Kind of like how you go through a form on any website using tab to get to the next input box?

**Comment by virtuallyvlad** [comment]
That's possible.  The cursor disappearing could be it going to another element, or it just going to the very bottom of the note (will need to scroll down next time to see).  I can't remember it ever stopping me from being able to type.  Just that the remainder of the text I'm typing ends up at the bottom of the note.

**Comment by mobitar** [comment]
Should be improvements in this area in v3.

**Comment by virtuallyvlad** [comment]
I found the exact cause but could not re-open this issue so recreated: https://github.com/standardnotes/desktop/issues/333

**Comment by mobitar** [comment]
The tab issue is separate from this, and seems to be specifically related to how we're handling tabbing.
