### ISSUE TITLE
Searching then clicking tag sometimes creates blank note

### ISSUE THREAD

**Issue by virtuallyvlad** [standardnotes/desktop#238]
In the Windows app, a certain search workflow will cause a blank note to be created:

1) Search for any term (preferably one with fewer results)
2) See which tags are used among all of the notes in the search results
3) Click on a tag that is not used
4) New blank note is created under that tag

Related: https://github.com/standardnotes/desktop/issues/237

**Comment by mobitar** [comment]
A blank dummy note will be created as a default placeholder in an empty tag. The question is, if you navigate away without making changes, does the note persist? It should destroy itself if you go to another actual note.

**Comment by virtuallyvlad** [comment]
No, the note doesn't persist if you navigate away.  But it's created under a tag that isn't empty - it already has notes.  Are blank dummy notes supposed to be created for non-empty tags as well?

**Comment by mobitar** [comment]
Ah interesting, I see. Yeah, it's not supposed to do that. Good catch. Have made a note of this.
