### ISSUE TITLE
Advance Markdown editor - code blocks and links in "Preview" mode are hard to read

### ISSUE THREAD

**Issue by ntran** [standardnotes/desktop#240]
Using the following combination: 
- Advanced Markdown editor
- Any dark theme
- View any code block as "Preview" or "Side by side" mode. The code block background currently has a light background which makes the code hard to read. In my opinion, it should have a darker background, with lighter text color
- Link refs also has dark blue color which is harder to read than light blue.

**Comment by mobitar** [comment]
Thanks for the heads up @ntran. I've made a note of this and hope to fix it in the editor's next release.

**Comment by marwanhilmi** [comment]
I'm having this issue as well. I've tried all the markdown editors and none of them are readable.

**Comment by mobitar** [comment]
Should be fixed in latest release.
