### ISSUE TITLE
Feature Request - Web Clipper

### ISSUE THREAD

**Issue by Stele77** [standardnotes/desktop#241]
Hi!
I did a search, and was suprised that i have not found this request already.
I will post it here, as i dont find any suitable repo for such a general request, and as i am not a dev, and Github is still confusing to me. I hope this is okay?

I am an Evernote user nearly since their launch on Android, and for many years on the hunt for a secure alternative.
It took all this time, but with Standard Notes i finally found the Software that ticks all the boxes. Plus, it seems like a high quality software, with a philosophy that puts it over the top.

As my main usecase would be collecting of web pages for research and writing, the thing that breaks the deal is the missing web clipper.

Your competition "Joplin" has this, but it seems less solid, and less competent security wise.
I would be happy to pay for this feature, as i pay for Evernote, but without it, it is simply not doable for me.
I know i could manually save the HTML and copy-paste it, but with dozens of articles i clip every day, this will get old pretty soon.

I know the webclipper is one of, if not THE main feature for many Evernote users from my time in the Evernote forum.
So it would be a big selling point for the mass of Evernote users; And to be honest most are fed up with EN as much as i am, and would be happy to switch IF there is a suitable alternative that ticks all the boxes (And besides the clipper, AFAIK you already do!).

This web clipper extension could be made for chrome, and easily ported to Firefox due to FFs new chrome like extension system.

At the bare minimum it would need to be able to save whole pages with text and pictures, and a selection of the page (like when you select page contents for printing). All with preserving basic formating (Or even better, with the option to use plain text or original formating).

If possible an automatically mode that extracts the article and seperates it from clutter (Like "reader mode" in some browsers and Feed-readers does) would be great to get it on par with EN and OneNote.

An option for saving the page as a picture would be a neat bonus.

Thank you in advance for your consideration, and congratulations to this excellent piece of Software!
Steven

**Comment by mobitar** [comment]
Thanks for the feedback @Stele77. A webclipper has been requested more times than you can imagine ;) Generally, it's out of scope for us. We like to focus on simplicity and only building software we can afford to maintain. At this point, building a webclipper might service some users, but detract from the core experience. Possibly likely to change in the future, but not in the short term.

**Comment by virtuallyvlad** [comment]
Some minimal version of this would be nice just for sharing links between devices in an easier way.  I use Pushbullet currently but it's quite a waste having a whole app for that.

Of course if SN did some sort of parsing or supported including articles altogether that could supplant the need for Instapaper or Pocket, as they would be basically less-secure and less competent versions of that.

Understood both are probably far out / out of scope.

related: https://github.com/standardnotes/forum/issues/287

**Comment by mobitar** [comment]
Yes, it would be possible for an external developer to create this. For example, an external dev created [standardnotes-fs](https://github.com/tannercollin/standardnotes-fs), which mounts your notes as files.

The API spec is here: https://standardfile.org.

**Comment by BuzzKnightbeer** [comment]
Awesome, thanks for the details and pointers.
