### ISSUE TITLE
Right-clicking deleting does not work

### ISSUE THREAD

**Issue by k-antonius** [standardnotes/desktop#25]
I'm using the MacOS desktop app. Right-click delete from the all notes menu does not appear to function. 

<img width="578" alt="standardnoteissuedelete" src="https://cloud.githubusercontent.com/assets/21194351/22154067/0685ba9a-def8-11e6-953f-9183a905cae9.png">

**Comment by mobitar** [comment]
Ah that shouldn't be there. To delete, click File on the note then delete. I'll remove this in the next release.

**Comment by k-antonius** [comment]
Ah. Makes sense. I did eventually figure out that delete was under the file dropdown. Is there a way to recover deleted notes, a trash folder or something?

**Comment by mobitar** [comment]
No, no such thing. If you hooked up with Dropbox, you might check in there.

**Comment by k-antonius** [comment]
It would be great to at least have an "undo-delete" option, in case you accidentally delete a note, if not a full-fledged trash folder. Think it's worth opening a separate issue for that?

**Comment by mobitar** [comment]
Adds too much complexity. But what we can do is a confirmation "Are you sure you want to delete?" to prevent accidents.

**Comment by k-antonius** [comment]
That would probably be sufficient in many cases.

**Comment by mobitar** [comment]
Fixed in latest release: https://github.com/standardnotes/desktop/releases/
