### ISSUE TITLE
Alphabetical Order & View on android 

### ISSUE THREAD

**Issue by th3technician** [standardnotes/desktop#252]
Hi, There is 2 issues really bugging me,

1- The alphabetical order of the folders list, Isn't there any workaround to make it adjustable? like drag and move folder to the place i want it to be, and any new created folder goes to the bottom of the list automatically. It would be very helpful to have that option

2- The view on android, you have to manually change it to the editor you using for it to read the file, for example i use "Plus Editor" as default when i open my notes on android it just reads it as HTML. And i have to manually change it for every note to work. Can't we set a default on android like we do on desktop version?

Any help appreciated!

**Comment by mobitar** [comment]
Custom order of folders is not and will not be supported any time soon. Default editors on mobile are likely to be supported at some point.

**Comment by th3technician** [comment]
Thanks for fast reply. Any workaround for custom order? or at least sorting folders/tags by date created or modified. 

- Also linux version is kinda buggy for me, The email function doesn't work in action bar gives error
` "kali appimagekit-standard-notes.desktop[1468]: gio: mailto:?subject=Check%20List&body= The specified location is not supported"` in /var/log/syslog

`# uname -a
Linux kali 4.18.0-kali2-amd64 #1 SMP Debian 4.18.10-2kali1 (2018-10-09) x86_64 GNU/Linux`

- And sometimes when hovering with mouse between folders and notes tabs the folders tab stuck and keep going up and down till i hover at it again and scroll

**Comment by mobitar** [comment]
Both folders and tags will always resort to an alphabetical order, so your only bet is to name your folders alphabetically. You can for example name your folders with a "1_first_folder", "2_second_folder", and it will sort by the lowest number first.

For the mailto link, you'd need to have a default email client set up for that to work. mailto links won't work without that.

For the stuttering issue, I've seen one other mention of that, but haven't been able to reproduce it yet. Might have something to do with scrollbars. That's definitely on the agenda to improve.

**Comment by th3technician** [comment]
When selecting a note also with long name like " Long Name" it shows up like this 
Long
Name
Note below it

All 3 gets so close to each other while there is enough space for it to be shown as it was. It's not necessary just looks ugly

**Comment by mobitar** [comment]
Do you mean "tag" wherever you said "note" in your descriptions above?

**Comment by th3technician** [comment]
Yes. Sorry

**Comment by mobitar** [comment]
We issued another update on Folders, should be a bit better now. Still needs a bit more work though.

**Comment by th3technician** [comment]
Yeah, It's better now. But still stuck sometimes and keeps going up and down. Only scrolling process is the worst.

Also wouldn't be integrating a reminder or timeline option good? That would make it a tool for both notes and project management. 

I'm having a hard time organizing my time and projects, saving clients data, etc. but don't want to use the other apps cuz they are really bad on the privacy part. This is where i landed on your tool (thanks for making such amazing tool :100: ). 

Anyway looking forward for upcoming updates :+1:  :)

**Comment by mobitar** [comment]
Reminders would be out of scope for us. We only want to be a simple notes app and nothing more :)
