### ISSUE TITLE
When the Plus Editor is activated, notes aren't saved when written/edited in code view. 

### ISSUE THREAD

**Issue by makarandh** [standardnotes/desktop#253]
I am running Standard Notes 2.3.8 on Kubuntu 18.04.1 LTS. 

If I am using the Plus Editor, when I click on 'Code View' and edit my notes, html tags etc., the notes aren't saved. I lost some modifications I made to my notes a couple of times this way way because I was going back and forth between the page and another one as I was copying notes and modifying them until I realized what was happening. Only when I go out of code view, to my Plus editor does it save my notes. 

If it doesn't save automatically in code view, could you at least create a manual way to save my notes? I frequently edit in code mode to get the formatting just right and it's easy to forget to go back to Plus Editor mode if I am jumping back and forth between different notes. 

Thank you.

**Comment by mobitar** [comment]
Good catch, I can confirm this behavior. I'll look into this. I'm sure there's some kind of event we could hook into to catch code changes.

**Comment by mobitar** [comment]
This should now be fixed (be sure to update the Plus Editor from the Extensions menu on desktop).

**Comment by makarandh** [comment]
Thant was quick. It's working. Thank you!
