### ISSUE TITLE
Extended editors preview doesn't work for Plus Editor

### ISSUE THREAD

**Issue by VosaXalo** [standardnotes/desktop#257]
In the changelog of the version 2.3.10 it's listed that:

> "_Extended editors previews will now display cleaner previews (no raw markup)._"

But with the notes written with the Plus Editor the new preview is not working.
With other editors instead it's working.

**Comment by mobitar** [comment]
You'll need to make sure you update the Plus editor from the Extensions menu. If you don't see an update option, try uninstalling and re-installing it (note however that this will disassociate any current notes set to edit with the Plus editor, and will revert them to the plain editor).

Also note that for the previews to be generated, you have to make at least one edit to every note.

**Comment by VosaXalo** [comment]
I have the autoupdate option enabled. Currently the Plus Editor extension is at version 1.1.6. 
Because the autoupdate, I think this is already the latest version, so no need to re-install.

I have edited one of my notes, but the preview is still displayed as raw markup.

**Comment by mobitar** [comment]
If this is on the web app, it's probably a cache issue. Best way to clear your cache for SN only is to open the developer tools (cmd/ctrl + shift + i), select the Network tab, check "Disable cache", then refresh the page. If that doesn't work, with the developer tools still open, click and hold on the refresh button in the upper bar of chrome, until you see a "Empty cache and heard reload" option.

**Comment by VosaXalo** [comment]
Sorry, this is not the web app. I'm using the desktop app version 2.3.11 on Linux KDE Neon (Based on Ubuntu 18.04). I have created a new note for test purposes, and I still see the preview in raw format, as you can see in the attached screenshot:

![screenshot_20181029_200318](https://user-images.githubusercontent.com/6298140/47673823-fae9f400-dbb5-11e8-85c4-73a0f9c884f7.png)

**Comment by mobitar** [comment]
The screenshot is for session history (or cloud history). These don't support formatted previews. By previews we mean the previews in the list of notes.

**Comment by VosaXalo** [comment]
Ahh ok, now I understand!
So, no issue at all in the end :-)
Thank you
