### ISSUE TITLE
Pinned notes disappear on Mac desktop 

### ISSUE THREAD

**Issue by Emily7777** [standardnotes/desktop#259]
Version: 2.3.11

When I pin a note it disappears.  When I search keywords from note, it's not found.

**Comment by mobitar** [comment]
Is it possible you have pinned notes hidden? This would have been done from the Options menu in the notes panel. You would see something like this if they are:

<img width="285" alt="screen shot 2018-11-02 at 9 09 29 am" src="https://user-images.githubusercontent.com/3277844/47920052-0cb1ec80-de7f-11e8-8b86-7fc44b1f0217.png">

**Comment by Emily7777** [comment]
I'm not showing those display options on my end.  I'm seeing "global display" only:
![ssp_temp_capture](https://user-images.githubusercontent.com/28765920/47952073-73203300-df83-11e8-8b99-2c6b9f36c07d.png)

**Comment by mobitar** [comment]
You want to be looking the middle column, your list of notes, and not the editor column. Under the search bar, there is a button that says "Options".
