### ISSUE TITLE
layouting bug

### ISSUE THREAD

**Issue by Aionics** [standardnotes/desktop#261]
When any kind of pop-up menu is active(Account or Extensions button pressed), i still can drug the line between "tags" and "All notes" over the pop-up, if cursor hovering it. Even throught pop-up.
![image](https://user-images.githubusercontent.com/13904925/48030962-b933ed00-e163-11e8-9f04-8abd7553bbde.png)
(desktop, win10)

**Comment by mobitar** [comment]
This should be fixed in desktop 2.3.12.
