### ISSUE TITLE
Feature Request: Require password after program idle for X amount of time

### ISSUE THREAD

**Issue by raideus** [standardnotes/desktop#263]
The password locking feature (#93) is great, but I'd really like it to be a bit stronger.  On OSX, I rarely completely quit applications (even clicking the close ("x") icon on the window doesn't technically quit the app).  So I find my StandardNotes app ends up regularly sitting unlocked on my system tray.

Could we instead configure the password lock to engage after a certain period of program idleness?  My password manager does this and allows me to configure the exact amount of time before it locks. 

An even stricter mode would allow the app to lock as soon as it is minimized or loses focus.

**Comment by mobitar** [comment]
Yup, presently working on this.

**Comment by mobitar** [comment]
Available in v3.
