### ISSUE TITLE
What's the easiest way to automate exports?

### ISSUE THREAD

**Issue by ErikBjare** [standardnotes/desktop#264]
I'm working on [a thing](https://github.com/ErikBjare/QSlang) that parses notes from the Standard Notes export. Now I want to avoid having to manually create an export every time my notes have been updated, any way to automate that?

I found [standardnotes-fs](https://github.com/tannercollin/standardnotes-fs) but it doesn't include metadata like `updated_at` and `created_at`. It'd just be simpler if I could get the same export that's available through the desktop client.

Thanks again for this amazing thing, just renewed my subscription for another 5 years :heart:

**Comment by mobitar** [comment]
Hey @ErikBjare, the easiest way would probably be to hook into the the automatic backups that are created as part of the desktop program. Click Backups -> Open Backups Location to find it (defaults to your home folder). These backups will be encrypted however (unless you use SN without an account). These backups are created twice daily when the app is open. I don't know of another way to do this I'm afraid..

**Comment by ErikBjare** [comment]
Thanks for the amazingly swift reply!

That's a perfectly fine solution, if there's an answer to this question: Any way to easily decrypt notes using Python? (would rather not reimplement the crypto parts)

**Comment by mobitar** [comment]
There are a couple of third-party Python clients for SN. One that comes to mind is https://github.com/tannercollin/standardnotes-fs.

**Comment by ErikBjare** [comment]
@mobitar Just want to let you know that I just picked this up again, and standardnotes-fs did the trick wonderfully. Thanks!

**Comment by mobitar** [comment]
Glad to hear that!
