### ISSUE TITLE
Date/time format option

### ISSUE THREAD

**Issue by cxnky** [standardnotes/desktop#266]
Not too sure whether I should open this here or not, but I think there should be a way to change the date/time layout, since it is currently in the US format (e.g. Nov 23 2018) and being in the UK, this can be confusing at times (e.g. extended expiration date)

**Comment by mobitar** [comment]
Most dates should be locale sensitive. Which dates in particular do you not see formatted properly?

**Comment by mobitar** [comment]
The Extensions panel will most likely be deprecated in the near future, but I'll keep this in mind for what replaces it.
