### ISSUE TITLE
Feature request: Hide tag and note list sidebars

### ISSUE THREAD

**Issue by justyn** [standardnotes/desktop#267]
It would be great to be able to toggle visibility of the two sidebars with a keyboard shortcut (and associated menu option).

When taking notes and using another window, a lot of screen real estate is used up with the permanent list of tags and notes. When you have selected a note, you only want to see the note contents.

This feature (or a variant) is pretty standard in most note apps that I have tried.

The dynamic theme causes the layout to flail around as you move the cursor over you screen so is not the same thing at all (and also it doesn't have a dark theme option).

**Comment by SiGamma** [comment]
Check out the No Distraction theme. There's no keyboard shortcut for it, you have to enable and disable it from the Extensions menu, but it does work.

**Comment by justyn** [comment]
@SiGamma thank you for the tip, it is a useful backup in the meantime.

I notice that it doesn't operate like a normal "theme" - it can be activated at the same time as others. It is very clunky having to disable/reenable the extension every time you want to switch notes. 

Is it possible to add a keyboard shortcut to this extension so that it can control whether it is enabled or not?

**Comment by justyn** [comment]
I'd also suggest that it is not very intuitive for the uninitiated (including me apparently) that in order to hide the side bars you have to enable a special theme, used in combination with your current theme.

**Comment by mobitar** [comment]
You can hide the side panels by double clicking or moving the resizers that appear when you hover over the right side of the panel.

**Comment by justyn** [comment]
@mobitar great, I did not notice that, thanks!

**Comment by justyn** [comment]
Double clicking on the resizers doesn't seem to work for me any more, so I have opened a bug for that as #268 

I still think a single keyboard shortcut to hide/show both these panels would be very useful.

**Comment by daylightbrightledlight** [comment]
Double clicking works for me, but it has UI bugs.

**Comment by mobitar** [comment]
Double clicking with Midnight theme should now be fixed.
