### ISSUE TITLE
breaks wingpanel of elementary os

### ISSUE THREAD

**Issue by dominikzogg** [standardnotes/desktop#27]
I tried this app, and since then I can't use the wingpanel of elementary os with notifications anymore. Do you have an idea what the problem could be?

**Comment by mobitar** [comment]
Hmm first time hearing of Elementary OS believe it or not. Looks interesting. I have no idea what the issue could be. The desktop app is an Electron app, so you might want to search that and see if you find something.

**Comment by dominikzogg** [comment]
hello@mobitar

Thanks for the fast response. What i know Franz (messenger) is electron to and i had no problems. Its the firstime i use a "AppImage" app, but even searching for that did not helped. I also added an issue at the wingpanel subproject of elementary. Will see if they find out what could possible go wrong.

Regards @dominikzogg

**Comment by mobitar** [comment]
@dominikzogg Let me know if you hear any updates on this.

**Comment by probonopd** [comment]
Let me know if you think something should be changed in AppImageKit and/or electron-builder.
