### ISSUE TITLE
Old Installer Cleanup

### ISSUE THREAD

**Issue by hl2guide** [standardnotes/desktop#271]
Please consider adding automatic deletion of old versions of installers (.exe) in: **%localappdata%\Programs\standard-notes**

They bloat out a folder on C drive ☹️

**Comment by hl2guide** [comment]
I'm seeing installers for older versions, having to delete them manually.
.EXE files with the version string in the name.

**Comment by mobitar** [comment]
Interesting, thanks for the heads up.

**Comment by tobiaalberti** [comment]
> 
> 
> Interesting, thanks for the heads up.

I believe this is the same issue I reported to you over Twitter DM back in June of last year. The behavior hasn't changed since then...
![annotation 2019-01-18 114100](https://user-images.githubusercontent.com/30185056/51416725-03314a00-1b7b-11e9-825f-71e0948e77a4.png)

**Comment by baptiste-grob** [comment]
In an upcoming version of the app we'll simply redirect you to the website if you want to download the update manually as there really is no difference and it gives you control over where the installer is stored :)
