### ISSUE TITLE
[Plain editor] Large notes slow down editor when Spellcheck is enabled

### ISSUE THREAD

**Issue by christianhans** [standardnotes/desktop#274]
I have long notes (> 1000 lines). When having Spell check enabled inside the Plain editor it is almost impossible to even edit the note (it takes second for the editor to accept any keyboard input). Turning off spell check removes the slowness.

**Comment by christianhans** [comment]
It seems to be an issue with Electron (or whatever the Desktop app is using). In Chrome this issue does not appear.

**Comment by mobitar** [comment]
What about system memory availability? When you get the chance, it would be helpful if you can check Activity Monitor for CPU and memory usage when this issue is happening.

**Comment by christianhans** [comment]
Plenty of memory available. I've noticed that the delay is a lot higher when pasting a few lines of text (up to 2-3 seconds delay).

Activity monitor while issue is happening:
https://user.fm/files/v2-6cbfb6f33f4851076f5ad43440c41a56/Screen%20Shot%202018-12-08%20at%2010.33.45%20AM.png

Happy to do a screen sharing session if needed to show you the issue in action.

**Comment by mobitar** [comment]
Ok great. If you can capture a video, that could definitely help ingrain it in my mind. In any case, if this is really related to spellcheck, we're going to have very few options, short of seeing if a newer Electron version has some better optimizations for this.

**Comment by christianhans** [comment]
Here you go:
https://www.dropbox.com/s/5d5g1o1qcg4ipx8/sn_test.mov?dl=0

It is an extreme example with a lot of spelling mistakes (50 paragraphs of Lorem Ipsum). With this extreme of an example Chrome is slow too but not as slow as the Electron app.

Also notice how the OSX Window button overlap with the sidebar when the folder sidebar is collapsed.

**Comment by mobitar** [comment]
Hmmm..interesting. Hard to notice the slowdown exactly because I can't see when you type, but, CPU usage definitely shouldn't be nearing 50%. That's going to cause some slowdown for sure. Even you disable spellcheck it remained high. Not sure if you would experience the same CPU usage if you restart the app with spellcheck disabled? Shouldn't really go over 20%. How many notes do you have total?

**Comment by christianhans** [comment]
Restart doesn’t help. About 430 Notes. It only occurs with very large notes though.

Best
Christian

**Comment by mobitar** [comment]
Seems to be some similar reports here: https://github.com/atom/spell-check/issues/58. We do use the same underlying packages for spellcheck as Atom.

**Comment by mobitar** [comment]
Not much we can do here I'm afraid, short of finding another library for spellcheck. Will keep on long term radar.
