### ISSUE TITLE
[macOS] Font weight lower compared to running Standard Notes in Web Browser

### ISSUE THREAD

**Issue by christianhans** [standardnotes/desktop#275]
Hi,

There seems to be an issue with font weight when using the Desktop app.

See this screenshot running the Code Editor (left: Desktop App, right: Chrome):
https://user.fm/files/v2-9ca22bbb6db32f5dfbc239b2e8df6770/Screen%20Shot%202018-12-08%20at%208.53.30%20AM.png

Safari and Firefox have same font display as Chrome does. Only the Desktop app seems to be affected.

**Comment by mobitar** [comment]
Good catch, will take a look.

**Comment by mobitar** [comment]
I believe this was fixed in latest versions of these editors.
