### ISSUE TITLE
Can't highlight multiple things at the same time on osx

### ISSUE THREAD

**Issue by dontbuymonero** [standardnotes/desktop#276]
Normally in osx you can hightly multiple parts of a text (or multiple items in general) by pressing command while highlighting additional items, but this does not work in Standard Notes, at least not on the desktop version. Using latest official version 2.3.13.

**Comment by mobitar** [comment]
Not sure that this is a macOS specific feature, but an application-level feature. Don't think we'd be implementing this ourselves to be frank. Likely not even possible for the plain editor as it uses an HTML textarea.

**Comment by dontbuymonero** [comment]
The same issue exists in plus editor.
