### ISSUE TITLE
OSX Desktop app - When adding new subfolder text is black on night theme.

### ISSUE THREAD

**Issue by DaveFlowberries** [standardnotes/desktop#277]
Text should be white so you can actually see it. 
<img width="181" alt="screen shot 2018-12-13 at 1 36 32 pm" src="https://user-images.githubusercontent.com/25303159/49917964-48a78b00-fedc-11e8-86f6-11322fdbd879.png">

**Comment by mobitar** [comment]
Thanks, next Folders release will be much more optimized for themes.

**Comment by mobitar** [comment]
Should be fixed in v3 release.
