### ISSUE TITLE
Search function inadequate/broken OSX Desktop app

### ISSUE THREAD

**Issue by DaveFlowberries** [standardnotes/desktop#278]
Here is a screen shot of me searching for a note with the title "pc build" using the exact same search text "pc build" you can see the note result is not at the top. It should be the first result.

Sometimes the note I am searching for is buried far down the note list causing me to scroll for a long time to find it. 

Furthermore, the results above my note don't even contain the text "pc build" at all, so I have no idea why they are even showing in the results in the first place....

<img width="233" alt="screen shot 2018-12-16 at 9 44 44 am" src="https://user-images.githubusercontent.com/25303159/50049203-0e2b3180-011a-11e9-8e4f-fae1372a4397.png">

SN 2.3.13 on Mojave

**Comment by mobitar** [comment]
Search will find notes containing any word in your input. Maybe not how you would expect it to work, but then again, everyone will have their own criteria for how search should work. This one produces generous results.

**Comment by DaveFlowberries** [comment]
"Generous" is an understatement I think, the top results don't even contain the keyword I typed. Anyhow, the solution is simple.

1 Exact text search option
2 Title search option

Some basic functionality like this would go a long way. Are these on the roadmap?

Thanks.

**Comment by mobitar** [comment]
Fine-grained search is on the general, non-time-specific roadmap.

**Comment by 7c** [comment]
what can be more important than searching in detail by a note app?
