### ISSUE TITLE
UI Glitch when hiding side panels. 

### ISSUE THREAD

**Issue by DaveFlowberries** [standardnotes/desktop#279]
1. The resize buttons overlap the note title
2. When hiding both panels, the grey vertical bars should ideally end at the horizontal line below "options editor actions" menu for a much cleaner look. Currently it's very distracting and would be MUCH better if the color was something more "midnight" to match the theme. You can see my example below.

3. 1 and 2 should work in all scaling modes.

<img width="153" alt="screen shot 2018-12-16 at 10 29 05 am" src="https://user-images.githubusercontent.com/25303159/50049323-fa81ca00-011d-11e9-8c7c-d21e41f4334b.png">
<img width="79" alt="screen shot 2018-12-16 at 10 29 35 am" src="https://user-images.githubusercontent.com/25303159/50049324-fb1a6080-011d-11e9-8bd3-a533cf4cca65.png">

Here is an example of how the UI should ideally look:
![better ui](https://user-images.githubusercontent.com/25303159/50049676-9531d700-0125-11e9-874a-840cf432845e.jpg)

Here is what it currently looks like:
<img width="1440" alt="screen shot 2018-12-16 at 10 58 32 am" src="https://user-images.githubusercontent.com/25303159/50049681-a549b680-0125-11e9-9f83-bf488bdb34ae.png">

**Comment by mobitar** [comment]
@DaveFlowberries thanks for the feedback. The bar colors will be fixed in the next release so it matches a little more. As for the padding on the top, I'll take a look at this one as well for the next release.

**Comment by mobitar** [comment]
Fixed in v3.
