### ISSUE TITLE
Right click on notes does not work.

### ISSUE THREAD

**Issue by DaveFlowberries** [standardnotes/desktop#280]
No context menu even pops up. Have to manually click options within note every-time is not user friendly

SN 2.3.13 on Mojave

**Comment by mobitar** [comment]
Custom context menus have not yet been implemented, although they are something on the radar.

**Comment by DaveFlowberries** [comment]
I am not talking about a custom context menu, I mean the default context menu does not even show up. Simply nothing happens when I right click on the note.

**Comment by mahyar** [comment]
I would second this feature as a paying customer.  It would be nice if the option menu showed up when you right click on a note in the 'all notes' list.  Saves you a click.
