### ISSUE TITLE
When changing size of font, numbers in ordered lists in Plus Editor don't change font size. 

### ISSUE THREAD

**Issue by makarandh** [standardnotes/desktop#282]
OS: Linux Mint 19
Standard Notes version 3.0.1
Extension: Plus Editor

The font by default in Plus Editor is 16 and default font is Ubuntu. When I change the font size to a different one (in my case, 14), the numbers in numbereds list stays at size 16. The content of the list changes properly to 14 but not the numbers themselves. As a result the list ends up looking ugly (due to size difference between the numbers and the content of the list).

In order to fix it, I have to manually change all `<ol>` tags to `<ol style="font-size: 14px;">`  in the html source. Could you please fix it such that when I change font size of an ordered list, the numbers themselves also change to the selected font size?

**Comment by mobitar** [comment]
Good catch, will need to investigate this! Transferred to here: https://github.com/sn-extensions/plus-editor/issues/10
