### ISSUE TITLE
AppImage of 3.1 does not work in Whonix

### ISSUE THREAD

**Issue by alien2003** [standardnotes/desktop#284]
No issues with 2.x verison.
![screenshot from 2018-12-27 12-42-45](https://user-images.githubusercontent.com/11610652/50477416-33465c80-09c4-11e9-9c67-7d656e09e5fd.png)
![screenshot from 2018-12-27 12-41-29](https://user-images.githubusercontent.com/11610652/50477422-36d9e380-09c4-11e9-8c11-f5a9a49a018c.png)

**Comment by mobitar** [comment]
Strange. I don't believe we've changed any core dependencies for 3.x. Will have to wait to see if anyone else encounters this issue.

**Comment by alien2003** [comment]
Works in last Whonix image. My fault, sorry
