### ISSUE TITLE
Compact Note List View

### ISSUE THREAD

**Issue by mahyar** [standardnotes/desktop#285]
A compact mode for the notes list would be nice, kind of like gmail with their default / comfortable / compact layout options:

![image](https://user-images.githubusercontent.com/22130/50530179-17b88000-0ab0-11e9-8cc5-8fade07acc30.png)

Notational velocity has a few view modes that are more compact that you could get inspiration from:
![image](https://user-images.githubusercontent.com/22130/50530194-2bfc7d00-0ab0-11e9-805d-b362f1c96577.png)
![image](https://user-images.githubusercontent.com/22130/50530199-328af480-0ab0-11e9-9462-4e88cb4edd96.png)

Another thing to make the all notes bar more compact is to make the search bar 1 row vs a 2 row view.

Ex:
```
[     SEARCH   ] [+]
vs.
All Notes      [+]
[     SEARCH     ]
```

**Comment by mobitar** [comment]
You can change display options for a compact view in the Notes panel Options menu: 
<img width="284" alt="screen shot 2018-12-29 at 9 47 32 am" src="https://user-images.githubusercontent.com/3277844/50539973-cb704d00-0b4e-11e9-8e08-23516b964822.png">
