### ISSUE TITLE
Responsive Design Layout

### ISSUE THREAD

**Issue by mahyar** [standardnotes/desktop#286]
Sometimes I like to split screen my notes app on my laptop, with notes on the left and a web browser on the right.  Currently standard notes doesn't respond well to being half the screen, only scaling the notes view and leaving the sidebars mostly static.  So when standard notes becomes half the screen instead of the entire screen, the sidebars take up most of the app.  I have to manually reduce the sidebars and then expand them again once I want to change the note I'm on.

Here are some responsive design examples:
https://responsivedesign.is/examples/

Maybe make the sidebars merge into 2 panels on top of each other when the horizontal viewport reaches a certain width point?  Or go into mobile mode where you only show the note and have a back button that shows a notes list?

A compact notes list view as I brought up in #285 will probably help with this.

**Comment by mobitar** [comment]
You can resize or hide panels via the panel resizer that appears when you hover over the right side of a panel. Double click to hide and drag to resize.

**Comment by virtuallyvlad** [comment]
Having this done automatically could be handy, but some may prefer that their sidebars/panels remain even when the window is half the screen or below a certain width.
