### ISSUE TITLE
Display warning about data/formatting loss upon choosing a different editor

### ISSUE THREAD

**Issue by leafcutterant** [standardnotes/desktop#289]
Most of thew time when you change the editor for an already existing note that has data in it, you either lose that data or it becomes mangled.

I suggest displaying a warning about potential data and formatting loss before the actual switch happens.

**Comment by mobitar** [comment]
Can you describe an example? You would never lose any data. But if you switch from an MD editor to the Plus editor and make a change, then yes, it will be converted to HTML. Or to the task editor, your note would be converted into a list. You can use session history if you want to undo this (actually, this issue is one of the main reasons for session history).

**Comment by leafcutterant** [comment]
The mangling of the data (loss of formatting) is inherent and you can see it anytime when you switch. e.g.: Plus -> Plain, or Sheets -> any. It was quite some time ago, but I also lost formatting when moving between Plain and Task. I'm of the opinion that formatting carries a lot of information, thus my focus.

I thought I can remember more examples, but you definitely lose your data if you switch from anything to Sheets. You kinda still have the data if you switch back without making any changes. (Idea: parsing each line into one cell of column A could create data continuity.) But if you do change anything and you switch back, you lose the previous data and only get the sheet data, in sheet code format.

**Comment by mobitar** [comment]
Good point, could be dangerous if you're not careful. Session history protects you against this, but new users may not yet be familiar with it. But perhaps a warning message when you switch editors could be in order.
