### ISSUE TITLE
Memory usage increases over time

### ISSUE THREAD

**Issue by christianhans** [standardnotes/desktop#294]
Below is a comparison of memory usage. In both cases the same note with the same editor is open. I assume there might be a Garbage Collection issue?

App running for a few seconds:
<img width="422" alt="screen shot 2019-01-08 at 7 22 14 pm" src="https://user-images.githubusercontent.com/355541/50869704-2aba3280-1383-11e9-9667-90c0e4d7a7bb.png">

App running for a few hours:
<img width="401" alt="screen shot 2019-01-08 at 7 21 47 pm" src="https://user-images.githubusercontent.com/355541/50869706-2c83f600-1383-11e9-9268-a70545c6904b.png">

**Comment by mobitar** [comment]
I'd have to do more digging, but part of this would just be natural. For example, if you have session history enabled (which is in-memory), the more changes you make to notes, the larger the memory footprint would grow.
