### ISSUE TITLE
retaining scrolling progress

### ISSUE THREAD

**Issue by superfreeman1989** [standardnotes/desktop#295]
Scrolling progress is lost when switching to another note entry. This is a bug or intended? Would be great to implement anyways especially when you have longer notes and frequently switch between entries.

**Comment by mobitar** [comment]
It's not a bug, just something we haven't explicitly written any code for. Would probably be somewhat trivial to do in the plain editor, but making it work across all editors would take a little more effort. Maybe some day in the future we'll focus on this.

**Comment by bryvin** [comment]
I've always wondered how stuff like this is done. You can't just store the scroll Y for example because that can change from device to device and also just by changing the width of the editor (making the content wrap sooner and pushing it down the page more). If you used the same scroll Y the content you actually were supposed to see would be much further down as it had been wrapped more.

**Comment by mobitar** [comment]
That's true, if you resize the editor then the saved value becomes invalid. We could probably account for that as well.

**Comment by bryvin** [comment]
The thing with accounting for it is also sort of difficult because it would vary on width, font width/size, etc. It's obviously possible cause there are other things that do this.. just curious as to how it works.

**Comment by mobitar** [comment]
True..sounds like it could be tricky.

**Comment by superfreeman1989** [comment]
> It's not a bug, just something we haven't explicitly written any code for. Would probably be somewhat trivial to do in the plain editor, but making it work across all editors would take a little more effort. Maybe some day in the future we'll focus on this.

Could possibly implement locally in the desktop client first? This feature is most useful in doing heavy editing with very long entries and frequent switching, which is probably rare on mobile and web version.
