### ISSUE TITLE
In-note linking to other notes

### ISSUE THREAD

**Issue by themadsilo** [standardnotes/desktop#296]
Would you consider adding the ability to create a link within a note, to another note.

For example, I'd like to create a general todo note, with each of the tasks, whatever they are, linking to whatever note I'd like them to correspond to. I think this would be a great workflow feature for people who have a lot of notes with a lot information, but don't want to reorganize them outside of their tags, while still allowing them to have an overview of whatever progress they're trying to make.

TBH I'm not sure if this is possible, but I wanted to ask anyway. Thanks.

**Comment by mobitar** [comment]
Hey @themadsilo, please see some of these threads:

https://github.com/standardnotes/forum/issues/324
https://github.com/standardnotes/forum/issues/293
https://github.com/standardnotes/forum/issues/43
https://github.com/standardnotes/desktop/issues/181

**Comment by themadsilo** [comment]
Ah. Thank you.
