### ISSUE TITLE
Feature Request: Multiple windows or panes

### ISSUE THREAD

**Issue by kyletolle** [standardnotes/desktop#298]
Requested: Ability to view more than one note at a time.

I often condense an idea that's scattered across multiple notes into a single note. This is best done when I can have one of the old notes right by the side of the new note. Otherwise I'm toggling between two notes in a single window, and you lose your position in each place when this happens.

Also, there are other times when I'm rearranging ideas within the same note, so it'd be nice to have the same note open in two different windows/panes/views.

I only noticed this behavior after using Standard Notes more recently, and I end up opening a new note to capture ideas when I'm on a call, or as I'm working on figuring something out. Later, I wanted to go through multiple notes and pick the relevant pieces out from each of those other notes and create a brand new note that supersedes them all. This was pretty difficult what with losing cursor position and or having to toggle between different tags to see the various notes.

**Comment by christianhans** [comment]
The macOS Notes App allows to open a note in a new Window by double clicking the note in the sidebar. On the Web one can already open Standard Notes in two separate tabs I guess?

**Comment by mobitar** [comment]
Perhaps this can be accomplished with an extension in the future..

**Comment by tmoravec** [comment]
Not sure if it means anything, but I second this feature request :-) .
