### ISSUE TITLE
Registering an account without an email isn't caught

### ISSUE THREAD

**Issue by Stahlneckr** [standardnotes/desktop#30]
When registering an account that isn't an email a UI error isn't thrown and the email is entered into the database as NULL.

**Comment by Stahlneckr** [comment]
Closing this. I seem to be getting the unable to register error now.

I'm running my own server and last night it was registering accounts without a proper email. Was likely user error.

**Comment by mobitar** [comment]
Are you having users register on your server? Are these like people you know? Curious how you're advertising it.

**Comment by Stahlneckr** [comment]
Just myself and some friends. No real advertising aside from word-of-mouth.
