### ISSUE TITLE
autolock puts entie system into "secure text imput" mode, thus disabling many hotkeys

### ISSUE THREAD

**Issue by DaveFlowberries** [standardnotes/desktop#301]
when the auto lock feature is enabled it makes it so all hotkeys and mouse hot keys don't work system wide. when clicking outside the password input box function, it is then restored to normal behavior. osx

**Comment by mobitar** [comment]
Can you give an example of what kind of hotkeys you're referring to?

**Comment by 13xps** [comment]
I have the issue too, here is a screencap. 
<img width="421" alt="screen shot 2019-01-30 at 10 07 13 am" src="https://user-images.githubusercontent.com/42802126/51971689-bf144280-24b4-11e9-9948-c63178c263b3.png">

**Comment by DaveFlowberries** [comment]
@mobitar All the programmable keys on mouse, and keyboard.

**Comment by mobitar** [comment]
@13xps how do you get that dialog to come up? Sorry, still having trouble following along here. Step-by-step instructions that reproduce this issue would be very helpful.

**Comment by baptiste-grob** [comment]
It's been a while so I'll be closing this issue but feel free to open a new one if you are still experiencing this :)
