### ISSUE TITLE
[Feature request] custom keyboard shortcuts (or, disable Ctrl-W)

### ISSUE THREAD

**Issue by quartertone** [standardnotes/desktop#303]
(Windows/Linux)
Not sure if this deserves to be called a bug, but it can be kind of annoying/disruptive.

Sometimes I accidentally hit ctrl+W (when trying to paste using ctrl-V; I use a Dvorak keyboard layout -- never mind) which causes the app/program to close/quit. If I have the "stay signed in" option checked, I just have to enter my local passcode (if set) after I restart the app. If it is not set, then I would need to log in again, and wait while the data + extensions are downloaded.

It would be great to have the option of setting custom shortcut keys for menu options, or disabling existing shortcuts that I don't want to accidentally trigger.

**Comment by bryvin** [comment]
Ctrl + W is a system wide keybind to close an active window, can be seen here: [Windows Keyboard Shortcuts](https://support.microsoft.com/en-us/help/12445/windows-keyboard-shortcuts)

**Comment by mobitar** [comment]
I think a good solution to this would be related to having the Windows app minimize to the task bar instead of quitting, as an option. This will likely make it into a future version, timing yet unknown.
