### ISSUE TITLE
Linux version cannot save font size and editor pane width

### ISSUE THREAD

**Issue by itssasanka** [standardnotes/desktop#308]
There seems to be a problem with the linux version (I understand that it's just an executable).
Every time I open up the app, the font size and layout are all back to default (though I changed them in my last session)
I was able to verify this issue doesn't exist on the OSX app.

Would be great if there's a workaround for this

**Comment by hirusi** [comment]
The font-size/zoom request has been raised before in #50

**Comment by baptiste-grob** [comment]
@itssasanka @hirusi 
Is this issue still present on the latest desktop app? I'm not sure I understood the initial problem but are the zoom controls enough to achieve the result you are looking for?

**Comment by hirusi** [comment]
No, it is not present in recent builds. It was fixed with #355.

**Comment by baptiste-grob** [comment]
Awesome, thanks for confirming that!
