### ISSUE TITLE
No checksum or signature files available

### ISSUE THREAD

**Issue by Kusken** [standardnotes/desktop#309]
There are currently no **checksum** or **signature** file available for verification of file integrity and source.

I can see that the latest release on github has a verified gpg signature, but if I want to download files from the [standard notes website](https://standardnotes.org/) then I have no means to **verify signature or source**.

Please make checksum & signature files available

**Comment by mobitar** [comment]
In the future I plan to have checksums automated as part of release notes. For now, they can be acquired using the steps above.

**Comment by leafcutterant** [comment]
I don't wish to rely solely on my operating system to verify the authenticity of the SN installers. Thank you for considering PGP-signing releases.
