### ISSUE TITLE
Offline database issue : undefined

### ISSUE THREAD

**Issue by dbeybia** [standardnotes/desktop#31]
![capture](https://cloud.githubusercontent.com/assets/10255598/22598247/1294aa80-ea33-11e6-863b-8148ab6b36b1.PNG)

This error pops up when launching Standard Notes version 0.2.1.

**Comment by mobitar** [comment]
Can you open your task manager (in advanced view) and check to make sure only 1 process of Standard Notes is running.

Also, did you have any previous versions installed, or is this your first version?

**Comment by dbeybia** [comment]
I had a previous version installed. And I also have one instance of Standard Notes running.

**Comment by mobitar** [comment]
I'm pretty sure it has something to do with a previous version running as a ghost. Can you try restarting your computer and seeing if that fixes the issue?

**Comment by dbeybia** [comment]
I dont think this has to do with restarting my computer as the problem still persists. I think it has to do with the the older version leaving behind configuration files that are incompatible with the newer version.

**Comment by karthikkonduri** [comment]
Similar case here. I have old version (Version 0.1.1 (0.1.1), MacOS version). However, when I try to launch the application, the UI panel(dashboard) doesn't fire up. Then, I downloaded the new version and tried to fire the new instance up and I encounter the same error.

When I check syspref (top), I see that it starts 3 processes and for a while, one of the processes is in a "STUCK" state. Does it point to anything?

**Comment by mobitar** [comment]
You should quit all processes and launch the new version. Use Activity Monitor on your Mac to do so. Click the "Memory" tab.

**Comment by mrbiber** [comment]
Is it possible to make it impossible to launch two instances of the app at once? This is something that can easily happen.

**Comment by mobitar** [comment]
I'll have to look into that.
