### ISSUE TITLE
Disconnecting external monitor with SN window in it does not transfer window to primary monitor

### ISSUE THREAD

**Issue by saifalfalah** [standardnotes/desktop#311]
Sometimes the Windows app is open, I can see it in the task bar. The preview is available when I hover over the app icon on the task bar but the app never comes into focus when I click on the app on the taskbar. What's more, I can see the app in the Task View but I'm unable to switch to it. 

Usually, the issue is fixed when I restart the computer and randomly occurs again. I suspect the issue is due to usage of multiple monitors which I use for work. The app behaves as if it is visible on the second monitor even though the second monitor is not even connected.

The issue is only with Standard Notes and no other app so this cannot be an issue with Windows. This is really frustrating and I usually have to open the notes in a web browser to get around this issue.

**Comment by saifalfalah** [comment]
I connect my external monitor back and the app is visible on the external monitor.

**Comment by mobitar** [comment]
Hmm..strange that this would be app-specific behavior and not OS behavior. Does quitting the app process and restarting it solve the problem? And does this problem happen with any other Electron apps, like Slack or Atom?

**Comment by saifalfalah** [comment]
Quitting the app and restarting it does NOT solve the problem.

The problem is not with any other electron app. I have VSCode and Slack installed and I use them regularly.

**Comment by mobitar** [comment]
I'd have to be able to replicate this issue for a chance of fixing it. Currently, here's what I've tried, but it works properly:

1. Have two displays connected.
2. Put SN in secondary display.
3. Disconnect secondary display.

At this point, SN is automatically displayed on my primary monitor. 

If you have a different set of steps that can help replicate this, please share. App and OS versions would also be good to know.

**Comment by saifalfalah** [comment]
Just replicated the issue with the following steps:

1. Have two displays connected.
2. Put SN on secondary display.
3. Quit SN.
4. Disconnect secondary display.
5. Open SN again.

SN is now **not** being displayed on the primary display.

6. Reconnect the secondary display.
7. SN is now visible on the secondary display.

**Comment by saifalfalah** [comment]
Even a restart does not fix it. One has to connect the secondary monitor. Drag the SN window to the primary monitor and close it. And then when you disconnect the secondary monitor, SN is visible on the primary monitor.

**Comment by saifalfalah** [comment]
@mobitar were you able to replicate this issue?

**Comment by mobitar** [comment]
Yes, can replicate it. Will need to explore a fix. In the mean time, here's a workaround that fixes the issue:

1. Start SN.
2. Hit Alt + Space on keyboard.
3. Choose "Maximize".

SN should now appear on primary monitor.

For step 2, a menu should appear in the top corner of your display. This menu should be related to the SN window that is out of bounds. If you see this menu in another window, click SN in your task bar to ensure it is the active focus, and repeat step 2.

**Comment by mctehlers** [comment]
I also have this issue on Windows 10 (1809). The workaround does work. This is on a Dell Latitude E7470, that is in a docking station with 2 connected monitors (DisplayPort) both running at 2560x1440 with the laptop display closed. Laptop display resolution is 1920x1080. When I detach the laptop from the dock standard notes does not appear on the laptop monitor. A restart does net help. Tinkering with windows scaling options does not appear to have any impact on this issue.

**Comment by mobitar** [comment]
This is now fixed in 3.0.10-beta2.
