### ISSUE TITLE
Ability to choose more fonts in plus editor? (extended)

### ISSUE THREAD

**Issue by zaen323** [standardnotes/desktop#313]
In the plus editor, there are only 10 fonts available
(Arial, Arial Black, Comic Sans MS, Courier New, Helvetica Neue, Helvetica, Impact, Lucida Grande, Tahoma, Times New Roman, Verdana) and for some reason the default font is Roboto.
Is this the intended behavior?

I looked up some other issues filed and noticed that the plus editor is based on summernote, just not sure if itself supports more fonts than the ones available now.

Also, should I have opened the issue at the sn-extension/plus-editor repo?

**Comment by mobitar** [comment]
The default font is set to "system-ui", which might be Roboto if you're using Android. As for more fonts, I doubt it would be possible, as we'd need fonts supported by all major platforms. 

(Closing here, but feel free to create another issue in the plus-editor repo if you have other questions)

**Comment by zaen323** [comment]
Thanks for the info. It is kind of weird since I am using standardnotes on linux. (Roboto is installed though)

A question coming from there, on what GUI is standardnotes based on linux? This is not really specific to plus editor so I decided to leave it here.

**Comment by zaen323** [comment]
Nevermind, it's electron, right there on the readme page.
I guess I will just find some ways to change the fonts. Appreciate your time as always, Mr. Mo!

**Comment by mobitar** [comment]
@zaen323 anytime! You can always go the [custom theme](https://docs.standardnotes.org/extensions/intro-to-extensions) route if you're wanting to incorporate a specific font.
