### ISSUE TITLE
Release 3.0.4 adds and undeletable note

### ISSUE THREAD

**Issue by igorkulman** [standardnotes/desktop#314]
On macOS I updated the app from 3.0.3 to 3.0.4 and a new empty note appeared

<img width="361" alt="screen shot 2019-02-04 at 08 55 52" src="https://user-images.githubusercontent.com/4746070/52196235-5f72ba00-285b-11e9-955a-290a781a85ba.png">

This note cannot be deleted

<img width="435" alt="screen shot 2019-02-04 at 08 55 48" src="https://user-images.githubusercontent.com/4746070/52196244-67325e80-285b-11e9-8ada-14ebffbefd7e.png">

Even trying to write some text to it shows the same error.

If I do "Sign out and clear all data" and sign back in, the note is still there. It does not appear on iOS, so it must be some "local" issue. Downgrading to 3.0.3 makes the note disappear.

**Comment by mobitar** [comment]
Thanks for the heads up. Will have this fixed for the next release. For the record, this empty note is created on app launch as a placeholder when no notes have loaded. It looks like it's being created erroneously with the new release.

**Comment by mobitar** [comment]
3.0.5 fixes this issue.
