### ISSUE TITLE
Release notes link is incorrect

### ISSUE THREAD

**Issue by igorkulman** [standardnotes/desktop#315]
Running 3.0.3 on macOS, I see `(1) Update Available` in the menu bar. I open it

<img width="298" alt="screen shot 2019-02-06 at 16 16 56" src="https://user-images.githubusercontent.com/4746070/52351319-ceead400-2a2a-11e9-9098-f54d1ec1ec14.png">

The second to last item is `View 3.0.3 Release Notes`. When I tap it it takes me to https://github.com/standardnotes/desktop/releases/v3.0.4, which is release notes for 3.0.4.

Either the link is wrong or more probably the menu item should say `View 3.0.4 Release Notes` as the new version is what is interesting to the user.

**Comment by mobitar** [comment]
Yeah it should say 3.0.4. Thanks!

**Comment by mobitar** [comment]
Fixed in 3.0.5.
