### ISSUE TITLE
[macOS] Empty space when in full screen mode

### ISSUE THREAD

**Issue by christianhans** [standardnotes/desktop#316]
When in full screen, the empty space left behind the windows buttons could be removed such that the tag sidebar stretches all the way to the top

<img width="434" alt="screen shot 2019-02-11 at 7 37 22 am" src="https://user-images.githubusercontent.com/355541/52563653-13ca8e00-2dd0-11e9-83c0-11b334a0e28a.png">

I.e. remove the green margin when in full screen:

<img width="218" alt="screen shot 2019-02-11 at 7 40 32 am" src="https://user-images.githubusercontent.com/355541/52563794-65731880-2dd0-11e9-8208-ca726594dd71.png">

**Comment by mobitar** [comment]
Hmm yeah good point. Extra space was anticipating 3 circular buttons. Will need to see if we can detect fullscreen.

**Comment by baptiste-grob** [comment]
We'll probably fix this when we rework the UI for v4 :) tagging in @zsoltszilvai in case there is useful info for him there !
