### ISSUE TITLE
Desktop/Web editor switches font to monospace when selecting plain editor on mobile

### ISSUE THREAD

**Issue by christianhans** [standardnotes/desktop#319]
Have seen this a couple of times occurring and I think I found the steps to reproduce:

1. Have Standard Notes Desktop App open
2. On mobile, open a note with Minimal Markdown Editor (wait for Desktop App to also switch to the Minimal Markdown Editor)
3. On mobile, Switch to plain editor
4. Wait for Desktop editor to switch to plain editor as well. Although Monospace is disabled under Options it will use a Monospace font (see screenshot below). Please note that the monospace font in this case is not the same Monospace font that is used when "Monospace" is enabled under Options.

Desktop editor at step 4:
<img width="549" alt="screen shot 2019-02-13 at 6 45 12 am" src="https://user-images.githubusercontent.com/355541/52709760-9f245a80-2f5b-11e9-852f-7e60e2a4dff4.png">

Monospace font is disabled at step 4:
<img width="293" alt="screen shot 2019-02-13 at 6 48 22 am" src="https://user-images.githubusercontent.com/355541/52709785-b5cab180-2f5b-11e9-810f-6dec3a22efdc.png">

Editor after enabling Monospace font (notice how it's a different Monospace font):
<img width="108" alt="screen shot 2019-02-13 at 6 48 43 am" src="https://user-images.githubusercontent.com/355541/52709811-c4b16400-2f5b-11e9-9db2-cf8e9dae421e.png">

**Comment by mobitar** [comment]
Interesting. I'll need to investigate this one further.

**Comment by mobitar** [comment]
This is fixed in upcoming 3.0.10.
