### ISSUE TITLE
Will there ever be the ability to export as a txt file?

### ISSUE THREAD

**Issue by laserstrike** [standardnotes/desktop#32]
I'm glad there's a download data function; but it's saved as a json file. Which I tried opening but felt it was too hard to dig through. 

I have no idea how difficult this would be considering the notes are encrypted and stored in the standard file format. I just wanted to say what would be ideal for newbie's like me.

**Comment by mobitar** [comment]
I was actually thinking about this last night. Let me look into it.

**Comment by mobitar** [comment]
I'd imagine if you wanted them in plain txt files, you'd want them decrypted right?

**Comment by mobitar** [comment]
Ok, I've added the ability to export as txt files in the latest release. It's available on web and desktop now. Will download zip file of all notes as txt files.

**Comment by laserstrike** [comment]
Oh wow. That was fast. Thanks so much.
