### ISSUE TITLE
The note you are attempting to save can not be found or has been deleted

### ISSUE THREAD

**Issue by hanct** [standardnotes/desktop#320]
Hi,
I first time register and sign in with both my mobile and desktop, to experience the sync.
So far the sync is ok except that my desktop version has an extra note not appear in mobile.

When i click on the extra note to edit, a prompt appears "The note you are attempting to save can not be found or has been deleted. Changes you make will not be synced. Please copy this note's text and start a new note."

1) May i know what could be the cause of this? 
2) I try to remove this note (via delete forever and move to trash) in my desktop version, but keep getting the same prompt. Is there a way to remove it?

**Comment by hanct** [comment]
Sorry, i notice that my extra note in my desktop version, after clicking here and there. Frankly speaking, i don't even know exactly what i click to make it disappear. 
But i still I hope to know what cause this extra note to appear in the first place, so that I can avoid such situation in future

**Comment by mobitar** [comment]
This is a placeholder note that's created, but in a recent update has been a little stubborn. The upcoming 3.0.5 update will fix this issue. Sorry for the inconvenience!
