### ISSUE TITLE
Standard Notes Potentially Out of Sync

### ISSUE THREAD

**Issue by onlinemumie** [standardnotes/desktop#321]
After update 3.0.5, I have the error message "Potentially Out of Sync" on all my desktop apps (both Linux and Windows 10). I've tried the Sign Out and Sync Resolution options, but the error message persists. I've also tried these solutions on just one computer after Sign Out and Clear Local Data on all other devices, but with no luck.

**Comment by mobitar** [comment]
The new sync integrity feature in 3.0.5 is a bit experimental, and we're still fine tuning it. If after sign out it's not resolved, and your data looks fine, it's safe to ignore that message. In the next version, this message will be less prominent as not to disturb normal workflow.

**Comment by mobitar** [comment]
3.0.8 should make some improvements in this area.
