### ISSUE TITLE
Decrypt script unresponsive

### ISSUE THREAD

**Issue by ghost** [standardnotes/desktop#326]
I downloaded the script from the website (Save As a .txt file is fine, right?) and opened it up in my Firefox browser.

I attached the encrypted note and entered my account password at the time of backup, after which I clicked on the "Download as decrypted import file" option.

Nothing happened. No download had started, and the page did nothing to say an error had occured. It did not change at all, but I know the page did not freeze because the buttons click but they do nothing. The other option to download as zipped plaintext files did not work either.

FWIW, I am running Windows 8.1, the decrypt script was saved to my desktop, and the encrypted backup was stored as a .txt file.

**Comment by mobitar** [comment]
Hey @kalydonscope, how large is the file you're attempting to decrypt? Also, can you open the Developer Tools console while you are doing this to see if it reports any errors?

**Comment by baptiste-grob** [comment]
This issue is quite old so I'll be closing it but feel free to open a new one if you are still experiencing this problem!
