### ISSUE TITLE
Resizing the window resizes the internal panes

### ISSUE THREAD

**Issue by popey** [standardnotes/desktop#327]
Summary:
Dragging the Standard Notes from one screen to another causes the window to un-maximise then re-maximise. The act of un-maximising reduces the size of the editor window, which doesn't re-expand horizontally when the window is re-maximised.

I don't believe this is specific to me having multiple monitors, and can thus be reproduced on a single display.

Environment:
KDE Neon (based on Ubuntu 18.04) with multiple monitors.
Standard Notes 3.0.6

Steps to reproduce

Open a note
Maximise the Standard Notes window on a display
Grab hold of the Standard Notes titlebar to drag it from one display to another
Note when 'detatching' from one screen the window sizes down, and the notes window shrinks horizontally
Drag the window to the top of a new display to initiate the desktop 'snap' feature to maximise it.
Observe that the window is now correctly maximised, but the notes window is horizontally too small.

The workaround is to grab hold of the vertical bar on the right side of the notes editor pane and drag it to the right. I have to do this every time I move the application window around.

**Comment by mobitar** [comment]
@popey thanks for the report. I've seen something similar on Mac and have it down to get this checked out for the next release. Similar in that it has to do with resizing windows, and the note editor margins not adjusting.

**Comment by mobitar** [comment]
This should be fixed in 3.0.8.
