### ISSUE TITLE
Hide menu bar by default?

### ISSUE THREAD

**Issue by jgierer12** [standardnotes/desktop#337]
Hi there,

is it possible to always hide the menu bar? There is an option to hide it, but it doesn't persist after closing and re-opening the app. I'd like to always hide it, since I don't use any of the menu items and the appearance is much cleaner without the menu bar, at least on GNOME.

**Comment by jgierer12** [comment]
If you are OK with adding this, I'm happy to work on a PR for it myself.

I use a dark titlebar with MacOS-style window controls on the left, so the themed menu bar doesn't really fit in with the other apps I'm using at all :wink:

**Comment by mobitar** [comment]
Got the PR, thanks!

**Comment by mobitar** [comment]
Wait..I just realized you said macOS, but on Mac, we don't use a custom title bar at all. All you should see are the red, orange, and green native buttons in the left. Are you seeing something else? Can you share a screenshot?

**Comment by mobitar** [comment]
Ohh nm, you don't use macOS, but macOS _style_.

**Comment by leafcutterant** [comment]
Menu bar hiding seems to be persistent now, I'd say this can be closed.

**Comment by jgierer12** [comment]
Sorry, I don't have StandardNotes installed right now, so I can't confirm whether this works.
