### ISSUE TITLE
[Windows] Incorrect Chinese Font Rendering

### ISSUE THREAD

**Issue by cyanlink** [standardnotes/desktop#340]
On Desktop version, Chinese characters are displayed in ugly-serif (Bad Fallback, SimSun is considered as an ugly serif font among Chinese users):
![image](https://user-images.githubusercontent.com/14952800/57702584-f4722400-7690-11e9-88f7-4d8e373ee735.png)

On Web version (latest Chrome 74) on Windows 10, It's rendered in MS YaHei (way better than SimSun, and it's sans-serif):
![image](https://user-images.githubusercontent.com/14952800/57702426-a3fac680-7690-11e9-864b-1b630a322441.png)

**Comment by mobitar** [comment]
Thanks for the heads up. Is MS YaHei system included? Can you paste some of that Chinese text from your notes here so I can test and compare on my end?

**Comment by cyanlink** [comment]
MS YaHei is installed to the system.
Test Chinese Texts Here:
天地玄黄 宇宙洪荒 日月盈昃 辰宿列张 寒来暑往 秋收冬藏

**Comment by baptiste-grob** [comment]
Should be fixed now :)
