### ISSUE TITLE
Can't pin the icon to Favorites launcher in Ubuntu 19.04

### ISSUE THREAD

**Issue by smartfonreddit** [standardnotes/desktop#345]
Hello,

I installed Standard Notes in Ubuntu 19.04 several days ago and was able to launch, then right click and pin it to Favorites. Its icon was also available while searching in "Applications". Due to tragic circumstances, Ubuntu as a whole had to be reinstalled today. 

I don't remember which version of Standard Notes I was using earlier. Right now it's the latest 3.0.9. I followed the instructions to download the file, move it to Home, execute the chmod. Run the AppImage file. The app opens. When I right click on its launcher icon, there is no "Add to Favorites" anymore, there is just "Quit" and "Notes". The app is no longer available under Applications search either.

I followed a workaround posted somewhere on Github about using "xprop", but the Terminal can't find that package anymore.

Possibly relevant: https://github.com/solus-project/budgie-desktop/issues/817

https://github.com/standardnotes/desktop/issues/166

**Comment by mobitar** [comment]
Try to see if this helps: edit the standardnotes.desktop file (should be in ~/.local/share/applications) and add

StartupWMClass=Standard Notes 

(or StartupWMClass=StandardNotes)

Restart the application. If that file exists you can also try deleting it, then restarting the application via the command line, and it should ask you to recreate the shortcuts.

**Comment by smartfonreddit** [comment]
> try deleting it, then restarting the application via the command line, and it should ask you to recreate the shortcuts.

That fixed it, thank you. My guess is earlier I prematurely terminated the Terminal while the app was doing the first run, or something along the lines.

**Comment by mobitar** [comment]
Ok great! Do you recall what the name of the .desktop file ended up being, and if it was located in the same directory as above? Just so I give the right instructions in the future.

**Comment by smartfonreddit** [comment]
> Ok great! Do you recall what the name of the .desktop file ended up being, and if it was located in the same directory as above? Just so I give the right instructions in the future.

"appimagekit-standard-notes.desktop" was in the directory that you've mentioned.
