### ISSUE TITLE
Monospace fonts appear to be thinner than in Chrome

### ISSUE THREAD

**Issue by christianhans** [standardnotes/desktop#347]
Compare Desktop App to Chrome. I'm using Simple Markdown Editor, but the same occurs for example with Advanced Markdown Editor. Fonts in general look a lot "crisper" in Chrome.

Desktop:
<img width="1325" alt="desktop" src="https://user-images.githubusercontent.com/355541/58581015-872bca80-821c-11e9-82b3-9356976cb45f.png">

Chrome:
<img width="1172" alt="chrome" src="https://user-images.githubusercontent.com/355541/58581019-88f58e00-821c-11e9-943a-771b163ed389.png">

**Comment by mobitar** [comment]
Fixed in https://github.com/sn-extensions/simple-markdown-editor/commit/8795cc21fa64af3e482bbaef54baa5dcead5cdc1 and https://github.com/sn-extensions/advanced-markdown-editor/commit/075e0000324b38511f1cb4928e09ecc443924629, pending deployment.
