### ISSUE TITLE
Note content font looks a lot thinner in desktop app vs web app

### ISSUE THREAD

**Issue by mobitar** [standardnotes/desktop#35]

**Comment by CR0CKER** [comment]
Would be good to have an option to pick a standard font for the desktop app, or at least make the font based on system settings. The current font is horrible.

**Comment by mobitar** [comment]
Fixed

**Comment by CR0CKER** [comment]
Would be nice to have a non-fixed width option for the font. Kerning is a great invention and would greatly improve the readability of notes.
