### ISSUE TITLE
Upgrade Electron, preferably to latest version

### ISSUE THREAD

**Issue by x80486** [standardnotes/desktop#350]
Electron should be updated/upgraded. Currently, **Standard Notes** uses Electron `1.8.4`, but the latest Electron version is `5.0.2` – shipped with Chromium `73.x`, Node.js `12.x`, and V8 `7.3.x`.

**Comment by mobitar** [comment]
Next release will use 1.8.8, then hoping to explore a more recent version.

**Comment by x80486** [comment]
Closed via #353
