### ISSUE TITLE
Delete from right click menu

### ISSUE THREAD

**Issue by aaronraimist** [standardnotes/desktop#36]
Notes and tags both have "Delete" in their right click menu but it doesn't appear to do anything. I would have expected this to delete the note/tag clicked on.

![screen shot 2017-02-07 at 5 30 48 pm](https://cloud.githubusercontent.com/assets/5855073/22716364/61c8c99e-ed5b-11e6-8a7b-a75a743a9ed5.png)

**Comment by aaronraimist** [comment]
Note: it seems like no matter where you click, the same menu always appears which really shouldn't happen.

**Comment by mobitar** [comment]
Hey, what version of the app are you running?

**Comment by aaronraimist** [comment]
Oh apparently quite an old version, 0.1.2. Is there no auto update mechanism built in? I'll update manually for now.

**Comment by mobitar** [comment]
There is auto-update in the new versions. Which should remove Delete from the menu.

**Comment by aaronraimist** [comment]
Thanks for your help. Latest version does remove the delete option.
