### ISSUE TITLE
Clicking a link in the markdown preview traps user in web browser

### ISSUE THREAD

**Issue by phansen01** [standardnotes/desktop#37]
When adding a link to my note via markdown and viewing the preview, clicking the link opens the webpage within the standard notes app and there isn't any clear/visible way for me to kill the markdown preview or navigate back to my notes without quitting the app.

(worth noting that cmd+clicking opens a separate window which avoids this issue, but it seems like having a way to go back 'home' via a menu option/hotkey is preferable here)

**Comment by phansen01** [comment]
from `index.js`:
```javascript
  // handle link clicks
  win.webContents.on('new-window', function(e, url) {
    e.preventDefault();
    shell.openExternal(url);
  });
```

I don't know a lot about electron/js/etc, but I'm wondering what about this block 'misses' regular clicks over cmd + clicks?

**Comment by mobitar** [comment]
Hmm good catch. Not sure what the issue is. Will take a look this weekend.

**Comment by phansen01** [comment]
It looks like `new-window` is sometimes not fired; instead `will-navigate` is fired when `target` is set to `_blank`. 

I've submitted a PR that fixes this on my installation.
