### ISSUE TITLE
Disable custom header bar on KDE

### ISSUE THREAD

**Issue by onedr0p** [standardnotes/desktop#373]
This is an addition to issue #258 

SN Version: 3.0.15
OS: KDE on Manjaro

![image](https://user-images.githubusercontent.com/213795/61261310-747b3f80-a74f-11e9-88cc-ba6c65103100.png)

As you can see I have both Header bars, system and the stand notes one. I have tried editing

```~/.config/Standard Notes/user-preferences.json```

and making it this

```{"useSystemMenuBar":true,"isMenuBarVisible":true,"zoomFactor":1}```

Few issues:
* I still see both header bars 
* There's an additional scroll bar that when I scroll down is the footer of the app (Account, Help, Extensions etc..)
* I cannot click on any button standard notes header bar

It seems as though if the SN header bar went away so would the scroll bar.

I have cleared cache, restarted app and computer. Any other suggestions?

**Comment by mobitar** [comment]
Hmm strange. If you click View, then toggle the themed menu bar, does one of them disappear? Also when you edit preferences file, be sure to restart the app for it to take effect.

**Comment by onedr0p** [comment]
Yes, I have tried all of those things :(

**Comment by mobitar** [comment]
Since you're a dev my recommendation would be to try running the app from source and see what happens with this condition: https://github.com/standardnotes/desktop/blob/master/app/index.html#L159

**Comment by onedr0p** [comment]
I will give this a shot, thanks!

**Comment by onedr0p** [comment]
I compiled from source and it seems to be working fine. I wonder what is wrong with the AUR package...

**Comment by onedr0p** [comment]
The AppImage appears to be working as well. I'll close this issue.

**Comment by mobitar** [comment]
Hmm strange. I'd be surprised if it was something with the package itself. But do let me know if you see this issue again with the AppImage/source!
