### ISSUE TITLE
Menu Options not working on Linux

### ISSUE THREAD

**Issue by dymdipi** [standardnotes/desktop#377]
I'm using the AUR package "standardnotes-desktop 3.0.15-1" (I appreciate that this is unofficial but I'm hoping that I can get some suggestions) on Manjaro Linux, 'Linux 5.1.18-1-MANJARO' kernel using XFCE 4.13. Everything is fully up to date.

The Maximize/Minimize/Close buttons and top left menu button are not responding and the bottom menu with "Account", "Help", "Extensions" etc is also hidden. I have to scroll down for this bar/menu to be visible. It's hidden even if I expand or maximize the window. However if I do scroll down, the bottom menu/bar does function normally.

User "ivanjara" reports the same behaviour in the comments of the AUR package:
https://aur.archlinux.org/packages/standardnotes-desktop/

I installed the application via this command:

`pamac build standardnotes-desktop`

The maintainer of the package "FillFeile" suggested that this sounds like an application issue rather than a packaging issue and that's why I'm raising it here.

Thanks in advance.

**Comment by dagjaneiro** [comment]
Hi @dymdipi, can you try installing the AppImage available at https://standardnotes.org and check if it behaves the same?

**Comment by TylerBrock** [comment]
I'm having the same problem recently. Since it's an electron app it should be the same no matter how it was packaged.

**Comment by dagjaneiro** [comment]
@TylerBrock afraid it's not that linear. We've also received another report recently about issues with the menu bar in the AUR package (https://github.com/standardnotes/desktop/issues/373). It turns out those issues were not present in the `AppImage`.

**Comment by dymdipi** [comment]
I've tried the Appimage and can confirm that it works without issue. I'll report this to the AUR package maintainer.

Thanks

**Comment by rjocoleman** [comment]
Responding here incase anyone comes across it (or is interested)

I haven't looked at this specific code but it'll probably be the same as this: https://github.com/standardnotes/desktop/issues/358#issuecomment-500160551

AUR doesn't pin dependencies, it just grabs the latest version of them. `standardnotes-desktop` relies on Electron to build but an older version than the `electron` package in AUR. The Electron API has changed between the current version referenced in the AUR `PKGBUILD` and the version `standardnotes-desktop` depends on.

It's a packaging problem. In the referenced PR above I submitted a change to `standardnotes-desktop` to be compatible with both versions of the API but this is more to be compatible with the new API when `standardnotes-desktop` updates Electron version with the added benefit of helping out people in the situation that AUR is in.

My suggestion would be applying a patch in the AUR `PKGBUILD` to the `standardnotes-desktop` source code in to adjust the relevant code (which seems to be a reasonably common pattern in AUR to deal with backwards compatibility)
