### ISSUE TITLE
Sort notes by last updated timestamp

### ISSUE THREAD

**Issue by betermieux** [standardnotes/desktop#39]
Hi,
I am using standardnotes a lot and want to propose a minor usability improvement:
How about sorting the notes by the last updated timestamp (it is saved in the database), so I can see the notes I last updated at the beginning of the list? Maybe it could be toggled from the UI if there are people used to the old style of sorting by creation date.
I can try to code a pull request if this sounds usable.
Greetings,

Stefan

**Comment by mobitar** [comment]
Hey @betermieux, check out this issue: https://github.com/standardnotes/web/issues/51

If you'd like to submit a pull request, that would be nice. A good place for this in the UI would be in the "Tag options" dropdown in the middle column. There you could say "Sort by created date" or "Sort by updated date", with a checkmark or some other ascii indicator showing the currently selected one.

**Comment by mobitar** [comment]
Done in latest
