### ISSUE TITLE
Windows 3.0.16 not working when offline

### ISSUE THREAD

**Issue by dreamflasher** [standardnotes/desktop#400]
Currently (3.0.16) on Windows the desktop version is not working when being offline. I can't create new notes, and I can't edit existing ones. Search and viewing works.

**Comment by mobitar** [comment]
Can you elaborate on "can't"?

**Comment by dreamflasher** [comment]
Sure: I press the "+" button and nothing happens. Or I click in the note field or title field and start typing, and it does not accept keystrokes. Only selection works.

**Comment by mobitar** [comment]
This might be related to the issue where the app does not refocus properly after an alert is shown. In this case, probably the alert that says you are offline. This will be fixed in the upcoming 3.0.17 release.

**Comment by dreamflasher** [comment]
Indeed solved by 3.0.17 release.
