### ISSUE TITLE
After incorrectly typing password no keystrokes work

### ISSUE THREAD

**Issue by CapitolRadio** [standardnotes/desktop#401]
After incorrectly typing my local password (Windows desktop app) the app no longer allows me to type after just one incorrect attempt. The app has to be closed and re-opened. This also happens sometimes when editing a note - the ability to type just disappear.

**Comment by alexandruast** [comment]
I am seeing the same behavior, the ability to type just disappears randomly in the latest version.

**Comment by mobitar** [comment]
This will be fixed in upcoming 3.0.17 release.

**Comment by CapitolRadio** [comment]
Thanks a lot @mobitar !
