### ISSUE TITLE
Note editing disabled after note deletion

### ISSUE THREAD

**Issue by CharlesCage** [standardnotes/desktop#404]
On Win 3.0.16, after selecting the Options menu, clicking in a note, note header, or tag area in note header no longer allows editing. (No cursor appears.) 

Selecting the Actions menu causes the cursor to reappear and allow note editing.

**Comment by CharlesCage** [comment]
Sometimes it is necessary to select Download Actions under Actions in order to re-activate editing.

**Comment by mobitar** [comment]
This will be fixed in upcoming 3.0.17 release.
