### ISSUE TITLE
3.0.17 - cannot disable spellcheck in editors

### ISSUE THREAD

**Issue by SiGamma** [standardnotes/desktop#407]
macOS Mojave, 10.14.6. Spellcheck is disabled in the plain editor, but switching to an editor such as Plus or Bold enables it, with no way to turn it off (Options menu shows that option greyed out, says that "spellcheck is not available with editor extensions"). Couldn't find any app-wide settings to disable it (it usually resides in the Edit menu in most apps, e.g. Safari), am I missing something or is it currently not an option?

**Comment by mobitar** [comment]
We just added spellcheck to editors in 3.0.17. There's currently no way to disable it. Something we plan on adding soon.

**Comment by mobitar** [comment]
Editor spellcheck has been removed in 3.0.18 as part of underlying Electron security configuration changes. Not yet determined when it will come back.
