### ISSUE TITLE
3.0.17 - Spellcheck not underlining incorrect words in Plain Editor

### ISSUE THREAD

**Issue by christianhans** [standardnotes/desktop#408]
![Screen Shot 2019-10-09 at 10 37 45](https://user-images.githubusercontent.com/355541/66491531-df9f8e00-ea80-11e9-8b38-d6e2bd676fde.png)

**Comment by christianhans** [comment]
Context menu offers correction suggestions - but incorrect words are not underlined.

**Comment by mobitar** [comment]
Catalina? Haven't tested on that yet.

**Comment by christianhans** [comment]
Seems to be a regression in 3.0.17. Underlining works correctly in 3.0.16 on Catalina.

**Comment by mobitar** [comment]
Still seeing this in 3.0.18?

**Comment by christianhans** [comment]
Just checked - 3.0.18 seems to have resolved it.
