### ISSUE TITLE
3.0.17 Switching to Standard Notes from another app flickers and pushes back to previously used app

### ISSUE THREAD

**Issue by CapitolRadio** [standardnotes/desktop#409]
In the latest update, on Windows, I noticed that if I have Standard Notes open, and ALT - TAB switch to the application from another application (or simply click on Standard Notes in the taskbar), Standard Notes will open and flicker very fast before switching immediately back to the previous app I was using. Once I've been pushed back to the first app (say a browser) the Standard Notes application in the task bar will be flashing orange/busy (as Windows does with all application by default to tell you something is happening in that application) After the first attempt to open/switch to Standard Notes, on the second attempt, Standard Notes will open instantly as it usually does. 

I hope this makes sense! 

Great work as always!

**Comment by mrankine** [comment]
Can replicate, 3.0.17 on Windows.

**Comment by mrankine** [comment]
I also find switching between Chrome and Standard Notes results in _Chrome_ flashing orange on the taskbar -- perhaps indicating there is a Chrom(ium) issue?

**Comment by MrMette** [comment]
I can replicate it as well with 3.0.17 on Windows 10. I don't even have to ALT-TAB, just clicking on the taskbar does do the same thing for me (and it doesn't seem to make a difference which software is active).

Standard Notes will come to the front and it will Switch back to the previous window (and will flicker orange in the tabbar). ALT-Tabbing a second time (or clicking again on the taskbar icon) will swap to Standard Notes.

**Comment by mobitar** [comment]
This has to do with a workaround we implemented due to an issue Electron has with inputs freezing up after an alert is shown. I think we can tweak the workaround a bit to prevent this issue. I'll take a look.

**Comment by Cosmitz** [comment]
Can confirm, same issue here. 3.0.15>3.0.17 Thought it was due to the new minimize to tray on close, but apparently not. Win7, clicking the taskbar icon. Quite annoying.

**Comment by nshaposhnik** [comment]
+1, same issue for me

**Comment by MorgothSauron** [comment]
+1, same issue for my in 3.0.16 and 3.0.17. No message in the console.

**Comment by aaantoszek** [comment]
+1

**Comment by roobs2000** [comment]
+1

**Comment by tomkahn** [comment]
+1

**Comment by iandelaney** [comment]
Checked in to note this same issue. Sadly not alleviated in 3.0.18

**Comment by aberusugi** [comment]
Same here, 3.0.18 it's happening on Win10Pro 1903. If I change focus to let's say Chrome, then back, no matter which method I do it, clicking, alt+tab, etc... It flashes and reverts to Chrome and I have to click it again to make it work.

**Comment by mobitar** [comment]
3.0.18 release notes: https://github.com/standardnotes/desktop/releases/tag/v3.0.18

This issue still doesn't have a good fix (low level Electron issue).

**Comment by aberusugi** [comment]
For some reason it hasn't done it at all this morning. Many other Electron apps are not doing the same thing for me, maybe they are finding some workaround? Good luck figuring it out either way! :)

**Comment by dreamflasher** [comment]
Still not fixed with 3.0.19 – this bug is really annoying.

**Comment by tomkahn** [comment]
Yes, same problem occurs on 3.0.19. Surprisingly annoying indeed!

**Comment by aaantoszek** [comment]
@dreamflasher @tomkahn I'd recommend going back to 3.0.15 (keep in mind this will delete all local data)

**Comment by mobitar** [comment]
3.0.18 contains important security fixes. I wouldn't go lower than that.

This bug is indeed annoying and I haven't found a good solution. The problem is based on the fact that in recent Electron releases, if an alert is presented and dismissed, all inputs stop working. The only solution is to blur the window, then refocus it quickly. The side-effect is the issue you all are seeing.

Related Electron threads: 
https://github.com/electron/electron/issues/18646
https://github.com/electron/electron/issues/19977
https://github.com/electron/electron/issues/20400

Electron team unfortunately has not yet accepted this bug.

**Comment by dreamflasher** [comment]
@mobitar Thank you for working on this. Your current hack is making things worse though. It seems it's unlikely to expect an electron fix any time soon, so how about you rather go with https://github.com/electron/electron/issues/20400#issuecomment-542060365 ? "own css-style alert window"

**Comment by mobitar** [comment]
That is indeed the direction I'm considering.

**Comment by genejo** [comment]
Sadly I encounter the same glitch. Happy to learn there's an active community surrounding Standard Notes though :)

**Comment by AdvaitSarkar** [comment]
+1, 3.0.18 and 3.0.19, Windows 10. Occurs when switching via Alt-Tab as well as clicking in the task bar.

**Comment by coltonrb** [comment]
+1 for rolling back your current fix. I'd deal with the alert issue all day long over the Alt-Tab issue.

**Comment by dreamflasher** [comment]
> 
> 
> That is indeed the direction I'm considering.

This seems to take longer than expected; can you please indeed roll back? The alt-tab push back is a lot worse than the alert issue.

**Comment by dreamflasher** [comment]
Thank you very much!
