### ISSUE TITLE
Structure of the repo

### ISSUE THREAD

**Issue by asymmetric** [standardnotes/desktop#41]
Hi!

I'm not familiar with Electron apps, and I'm confused as to where the "meat" of the app is: encryption, storage, etc.

Is it in the [web repo](https://github.com/standardnotes/web)?

I think it could make life easier for people to have some more information in the REDME in this regard. I'll make a PR as soon as I figure things out :)

**Comment by mobitar** [comment]
Yup the meat is in the web repo. After compiling the web repo, you'll get two files: compiled.js and app.css. Those are the main files used in this repo.
