### ISSUE TITLE
Unable to open Desktop app in macOS Catalina

### ISSUE THREAD

**Issue by mzch** [standardnotes/desktop#412]
Hi,

After upgrading macOS to Catalina, Standardnote desktop app can't be opened.

<img width="532" alt="ScreenShot 2019-10-16 9 27 21" src="https://user-images.githubusercontent.com/621178/66878951-382dd880-eff7-11e9-9605-c3cfee9f2751.png">

p.s. Version 3.0.17 downloaded on Oct, 9.

**Comment by mobitar** [comment]
Please see here for workaround: https://github.com/standardnotes/forum/issues/715#issuecomment-542775702
