### ISSUE TITLE
3.0.18 - Maximize / Minimize Issue

### ISSUE THREAD

**Issue by hl2guide** [standardnotes/desktop#414]
After upgrading to 3.0.18 I noticed that the window's maximize/minimize button seems to not maximize on click but does minimize (if the windows is full screen sized).

e.g.:

![Screenshot (26)](https://user-images.githubusercontent.com/17044982/67385800-7e7acd00-f5df-11e9-8191-70d36aafb48c.png)

**Comment by mobitar** [comment]
Thanks for the heads up!
