### ISSUE TITLE
3.0.18: [Linux] Background color turns white on opening app

### ISSUE THREAD

**Issue by ivywong** [standardnotes/desktop#417]
After upgrading to 3.0.18, whenever I open the app, parts of the UI are reset to the white theme instead of the theme the app is supposed to be loading. For example, if I have my theme set to "Focus", when I open the app, the sidebar background turns white but the text remains light gray. The notes list turns black-on-white, and it appears that any input box in the editor has the correct theme color, while the background also turns white.

If I switch themes, then the colors turn back to normal, but the issue returns if I close the app and reopen it. I can reproduce this problem with the other themes as well.

Screenshots:
(with advanced markdown editor)
![standardnoteswhite](https://user-images.githubusercontent.com/2830112/67539858-51d6bc00-f698-11e9-8056-4753db19013e.png)

(with task list)
![standardnoteswhitetodo](https://user-images.githubusercontent.com/2830112/67540059-e9d4a580-f698-11e9-8e0c-5967c99001fc.png)

I'm on Ubuntu 16.04 LTS (64 bit).

**Comment by bryvin** [comment]
Believe this is a known issue; discussion here: https://github.com/standardnotes/forum/issues/736
