### ISSUE TITLE
Windows shortcut disappears after update

### ISSUE THREAD

**Issue by lorenzschmid** [standardnotes/desktop#42]
Under Windows 7 I have a shortcut of Standard Notes pinned to my taskbar. Unfortunately upon every (automatic) update the shortcut gets deleted and I have to pin it again - a tiny thing but annoying after some updates ;)

**Comment by mobitar** [comment]
Let me know if you have any guidelines for a fix. Otherwise won't be able to prioritize it.

**Comment by lorenzschmid** [comment]
As explained [here](https://github.com/electron-userland/electron-builder/issues/926#issuecomment-271135087) could it be that upon update the app uninstall itself first before being installed again?

> [UninstShortcut](http://nsis.sourceforge.net/WinShell_plug-in) calls [IStartMenuPinnedList::RemoveFromList](https://msdn.microsoft.com/en-us/library/windows/desktop/bb774815(v=vs.85).aspx) which removes the shortcut from being pinned in both the start menu and the taskbar.
>
> Since the updater effectively runs the old uninstall and the new installer this is being called. If the paths are no longer being changed upon update (and the updater should check that, since the new installer could use a different directory) the portion of the uninstall where shortcuts are removed and reinstalled could be skipped when updating.

**Comment by mobitar** [comment]
I do believe that is the case since on Mac the app re-requests permissions after each update.

**Comment by jrc03c** [comment]
This may or may not be related, but my Linux (Xubuntu) menu shortcut disappears after each update because the AppImage filename changes. I don't know if that's what's happening on Windows or not, but I thought I'd mention it.

**Comment by baptiste-grob** [comment]
Closing assuming the problem has been solved since then but feel free to reopen if that isn't the case @lorenzschmid!
