### ISSUE TITLE
3.0.18 Regression for local editors

### ISSUE THREAD

**Issue by lemeb** [standardnotes/desktop#420]
Hi!

4b85c9a changed `app/index.html`'s Content Security Policy (see line 7), and arguably includes a regression for those who want to develop locally. 

Now I get:
```
Refused to frame 'http://localhost:8080/' because it violates 
the following Content Security Policy directive: 
"default-src 'self'". Note that 'frame-src' was not explicitly set, 
so 'default-src' is used as a fallback.
```

I understand where the fix is coming from, but I wonder if there could be a way to carve out an exception in the CSP to allow for localhost extensions...

(I'm not sure how one can get hot reloading without putting localhost as a url...)

Have a great one!

**Comment by krconv** [comment]
I have an extension hosted on GitHub that I found also stopped working this weekend.
```
Refused to frame 'https://krconv.github.io/' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'frame-src' was not explicitly set, so 'default-src' is used as a fallback.
```

**Comment by mobitar** [comment]
Unintended, fixed in next release (today hopefully).

**Comment by lemeb** [comment]
that was fast, thanks!
