### ISSUE TITLE
Can't use polish diacritic "ó" (right alt + o) because ctrl + o is one of the key shortcuts

### ISSUE THREAD

**Issue by mrowa** [standardnotes/desktop#43]
In polish language "ó" is one of the diacritics written using `right alt` + `o`. Electron by default treats `right alt` as `ctrl` + `alt`, so it treats my `right alt` + `o` as `alt` + `ctrl` + `o`. Because of that, when I write "ó", Standard Notes toggles full editor and does not write "ó".

Here's (probably) related issue in Atom: https://github.com/atom/atom-keymap/issues/35

Platform: Windows 10

**Comment by mobitar** [comment]
Hmm..do you know of a safer keyboard shortcut we could use for full screen?

**Comment by mrowa** [comment]
I can think of a keyboard shortcut which would not make a problem in polish, but I'd wager it's not really possible in general: https://en.wikipedia.org/wiki/Diacritic#Languages_with_letters_containing_diacritics

A proper solution would be to differ `right alt` from `alt` + `ctrl` in keyboard shortcuts.

**Comment by mobitar** [comment]
Shortcut has been removed in latest version.
