### ISSUE TITLE
Windows Desktop - Sync Unreachable!

### ISSUE THREAD

**Issue by 10am360** [standardnotes/desktop#435]
Not syncing and saving content on Standard Notes. Just today. Showing error.
![rrr](https://user-images.githubusercontent.com/50535716/69036567-2342cb80-0a21-11ea-80e7-0bab659ff647.JPG)

**Comment by VosaXalo** [comment]
Same issue here on Linux Desktop and on Android app.
On the web this error message shows up continuously:

> There was an error while trying to save your items. Please contact support and share this message: TypeError: Cannot read property 'map' of undefined

It seems to be a general issue.

**Comment by jbeldia** [comment]
Users have been experiencing sync issues across their devices for the past couple of hours

standardnotes/forum#770

As far as I know, the devs are still looking into the issue, hopefully it will be fixed soon!

**Comment by 10am360** [comment]
The SYNC issue has been fixed on my end today. No errors encountered at the moment when using app on Desktop windows.

**Comment by bryvin** [comment]
Yes this issue has been resolved, here is mobitars update on this: https://github.com/standardnotes/forum/issues/770#issuecomment-555086464
