### ISSUE TITLE
"404 Not Found" in left sidebar after installing folder extension

### ISSUE THREAD

**Issue by JulianWgs** [standardnotes/desktop#439]
The error goes away after uninstalling the extension.

Plattform: Windows 10 64bit
Version: 3.0.23

**Comment by baptiste-grob** [comment]
Hey @JulianWgs, sorry for not getting back to you sooner. Does this issue still happen on the latest desktop app? And if it does, is your experience different on the web app?

**Comment by JulianWgs** [comment]
No, its gone :)

**Comment by baptiste-grob** [comment]
Awesome 👍
