### ISSUE TITLE
Suddenly stopped working - System Error

### ISSUE THREAD

**Issue by saifalfalah** [standardnotes/desktop#448]
Standard Notes desktop app suddenly stopped working. Whenever I run it now, I get the error: 

> The code execution cannot proceed because ffmpeg.dll was not found. Reinstalling the program may fix this problem.

Should I reinstall?

**Comment by jbeldia** [comment]
It's worth a try, though you should first secure a backup of your current data through the web app, just in case. The option to download backups is in the "Accounts" tab on the lower left of the app.

**Comment by saifalfalah** [comment]
So I tried uninstalling the app and it gave me the same error. I wasn't even able to start the uninstall process.

What worked though was downloading and installing Standard Notes again on top of the existing app.
