### ISSUE TITLE
Simplify deletion of existing tags from a note

### ISSUE THREAD

**Issue by CR0CKER** [standardnotes/desktop#45]
When deleting an existing tag from a note, right now every single character of the tag must be deleted. It would be much faster if the whole tag could be deleted with a single keystroke, like Evernote has solved it.

**Comment by mobitar** [comment]
Unnecessary complexity. Probably won't happen anytime soon.

**Comment by CR0CKER** [comment]
Well, nevermind then. If the most basic UX improvements are considered an unnecessary complexity, I guess it's all good already and StandardNotes can just stay as it is right now. No need to contribute.
