### ISSUE TITLE
404 page not found in not because of plus editor

### ISSUE THREAD

**Issue by boistordu** [standardnotes/desktop#450]
On a windows Host, after a long period of time of inactivity and so a lot of notes coming in and some new extensions being activated at the same time -
-> the notes created during this period of inactivity on other hosts, with plus editor might result in a 404 not found error on the host in question, not the other hosts.

**Comment by bryvin** [comment]
On the windows app that received the 404 Not Found did you previously have the Plus Editor installed, or did you install this Editor Extension while using another app (any other pc or even just the web app) and then return to the Windows app to find it cannot load the Plus Editor?

Also if you wouldn't mind attempting to change the Editor from the Plus Editor to a different one and then back to verify if the problem still occurs?

We will look into this issue but if you can provide me with the answers from the 2 questions above that would be greatly appreciated!

**Comment by baptiste-grob** [comment]
It's been a while so I'll be closing this but feel free to open a new issue if you're still experiencing this problem 👍
