### ISSUE TITLE
Row of tags cut off after 25 characters

### ISSUE THREAD

**Issue by CR0CKER** [standardnotes/desktop#46]
When adding more than 25 characters of tags to a note, the rest is not displayed properly on macOS. See screenshot. 

<img width="524" alt="notes" src="https://cloud.githubusercontent.com/assets/6056387/23337532/4331e3aa-fc2c-11e6-889e-d897e86d8520.png">

**Comment by mobitar** [comment]
Fixed in https://github.com/standardnotes/web/commit/4d95e6070e4d877901122d8ca73f90e90ecad5a9, will be deployed in desktop app sometime next week.

**Comment by mobitar** [comment]
Available in 0.2.9
