### ISSUE TITLE
Desktop App does not recognize system's date time settings

### ISSUE THREAD

**Issue by christianhans** [standardnotes/desktop#460]
This is from Standard Notes' status bar:
<img width="205" alt="Screen Shot 2020-01-04 at 06 16 01" src="https://user-images.githubusercontent.com/355541/71764767-12a7c100-2eba-11ea-9df4-35bf45ba0798.png">

macOS system date time fomat settings:
<img width="524" alt="Screen Shot 2020-01-04 at 06 16 58" src="https://user-images.githubusercontent.com/355541/71764750-d2484300-2eb9-11ea-9f05-36ae2c6523ff.png">

<img width="522" alt="Screen Shot 2020-01-04 at 06 19 16" src="https://user-images.githubusercontent.com/355541/71764773-24896400-2eba-11ea-8121-b4314d088b29.png">

**Comment by baptiste-grob** [comment]
Thanks for the report! I'll be closing this issue since it is a know problem: #332
