### ISSUE TITLE
Keyboard shortcut to quit on GNU/Linux

### ISSUE THREAD

**Issue by hyphone** [standardnotes/desktop#462]
Hello and good day,

would it be possible to add a keyboard shortcut to quit the app on GNU/Linux via Ctrl + Q?

All the best

**Comment by hyphone** [comment]
https://github.com/standardnotes/desktop/pull/463

**Comment by baptiste-grob** [comment]
We're planning to add keyboard shortcuts in a more general and consistent way. Thanks for your feedback, we've taken note of it :)
