### ISSUE TITLE
Change drop-down menus to icons for better UX

### ISSUE THREAD

**Issue by CR0CKER** [standardnotes/desktop#47]
The dropdown menus in the desktop app are awkward. How about using icons for deleting a note and toggling for full-screen? Using drop downs for tags is also a bit strange -- an icon to quickly delete a tag would be more intuitive.

**Comment by mobitar** [comment]
You're gonna think I'm crazy but I'm intentionally not using icons as icons are a fashion item and degrade quickly with time. If the aim of this project is longevity, it's best not to use icons to make maintenance simpler. As for the dropdown, it allows us to keep the UI clean and organized. It's functional.

**Comment by CR0CKER** [comment]
Guess it comes down to taste, but from a usability point of few, icons are an intuitive way to access functionality. I have to actively search online to find out how to delete a tag because the current dropdown is so unintuitive.

**Comment by CR0CKER** [comment]
Yes, icon styles change like fashion, but icons have been used in personal computing for decades. So I don't think they are in opposition to longevity. Also, I understand longevity is StandardNotes focus when it comes to file formats -- but does that need to hamper UX?

**Comment by hill** [comment]
I agree with @CR0CKER - it took me a solid 10 minutes to work out how to delete a tag. I think the dropdown menu for tags is in a weird place...it feels like the 'notes' column. A right-click menu delete option on the tag itself would be helpful (that was my immediate response as I could find no icon...)

(Awesome project by the way! I'm really looking forward to helping out.)

**Comment by mobitar** [comment]
Thinking through extensions for notes list and tags view. Putting this on hold.
