### ISSUE TITLE
SHA256SUMS wrong file names

### ISSUE THREAD

**Issue by syntacticNaCl** [standardnotes/desktop#471]
OS: LinuxMint 19.1

Currently the `SHA256SUMS` file provided with the releases do not contain the correct file names. Running a `sha256sum -c SHA256SUMS` fails to verify the files since in my case the Appimage I want to use `Standard-Notes-3.0.25.AppImage` shows as `Standard Notes-3.0.25.AppImage` in the `SHA256SUMS` file.

The following files are named incorrectly: 
Standard Notes-3.0.25-mac.zip
Standard Notes-3.0.25.dmg
Standard Notes-3.0.25.dmg.blockmap
Standard Notes-3.0.25-i386.AppImage
Standard Notes-3.0.25.AppImage
Standard Notes Setup 3.0.25.exe
Standard Notes Setup 3.0.25.exe.blockmap

**Comment by baptiste-grob** [comment]
Thanks for the report :)
We've fixed this with 3.4.2: https://github.com/standardnotes/desktop/releases/tag/v3.4.2-beta1
