### ISSUE TITLE
Possible regression in 3.3.0: Search box loses focus when typing

### ISSUE THREAD

**Issue by christianhans** [standardnotes/desktop#473]
I think there is a regression in the 3.3.0 Desktop App:

When typing a search query into the search box I can only type in 2 or 3 characters and the search box loses focus:

1. Select any note
2. Focus search box
3. Start typing a string thats not in this current note but in another note
4. Once the string starts matching the other note the search box looses focus

**Comment by christianhans** [comment]
Issue occurs on other machine as well (both macOS 10.15 Catalina). I did verify that this is a regression introduced in 3.3.0. Issue does not occur on 3.0.25.

**Comment by mobitar** [comment]
What editor does the other note use? This can happen if the editor requests auto-focus. It will take away from focus the search box. This is a long-standing issue which I haven't found a good solution to.

**Comment by sbocinec** [comment]
I experience the same problem (Ubuntu Linux 19.10, Advanced Markdown Editor) - search is almost unusable - always loses focus.

**Comment by christianhans** [comment]
Issue occurs with just the Plain Editor as well.

**Comment by mobitar** [comment]
@sbocinec this is only when using non-plain editor correct? Because I tried with just plain editor and couldn't replicate.

@christianhans are you sure it happens with plain editor only? I would be surprised. If at any point in your search a note appears that uses an external editor, focus may be hijacked. Perhaps the solution to this then is for the app to not auto-select any notes while searching.

cc @baptiste-grob

**Comment by sbocinec** [comment]
@mobitar I use Advanced Markdown Editor as a default, but i tried following:
1. Open the app
2. Change the first note that is on the list (Sort by Title), from the AME to the Plain Editor. Note down a word that appears in this note (ie. fitness)
3. Change to the second note on the list (in my case a TokenVault type note)
4. Start typing to the search field: `fit` Here it loses focus, display the content of the first note, i'm unable to finish typing remaining `ness`

Does this help? Let me know if you need anything else to try

**Comment by mobitar** [comment]
Ahh, I see it now. Yup, that's no good, thanks. Will get this fixed.

**Comment by mobitar** [comment]
Fixed in 3.3.1, deploying shortly.

**Comment by sbocinec** [comment]
I confirm the fix is working. @mobitar  thanks very much for the prompt fix
