### ISSUE TITLE
Suggestion: Autolock when window minimized 

### ISSUE THREAD

**Issue by technotherion** [standardnotes/desktop#478]
Currently on 2.4.0-1 beta. I appreciate the setting to autolock after a certain time period losing focus, but am wondering if autolock immediately when window is minimized, similar to KeePass, would be a possible integration.

**Comment by baptiste-grob** [comment]
Thanks for bringing this up. I've logged the issue and will look into it.

**Comment by baptiste-grob** [comment]
Actually I'm not sure about this… The menu option says "Minimize to tray on close", so I think the behavior should be the same as when the window is minimized, not closed 🤔 Which is what the app is currently doing

**Comment by baptiste-grob** [comment]
I'm closing this issue because the originally reported bug has been fixed, however if you want to continue the discussion @mechanarchy I invite you to start a thread on the [forum](https://github.com/standardnotes/forum) as this is more of a feature addition/change rather than a bug per se 🙂
