### ISSUE TITLE
Opening app, then clicking away, "Saving local backup..." gets stuck in footer

### ISSUE THREAD

**Issue by mobitar** [standardnotes/desktop#484]
> Uncaught (in promise) ReferenceError: SFItemParams is not defined

Unfortunately can't replicate in dev, but can replicate in prod.

**Comment by MorgothSauron** [comment]
I have that problem on Fedora Linux with version 3.3.1. In my case I can trigger the error in the console by clicking the "Download Backup" button under the "Account" menu.
![image](https://user-images.githubusercontent.com/6804228/74380511-00d70900-4dea-11ea-93d4-428df4267fe5.png)

**Comment by greveritt** [comment]
I can trigger the error on macOS Catalina 10.15.3 by giving focus to another application, just like the issue creator. I'm seeing the same stack trace, aside from the different source file location.
![Screen Shot 2020-02-12 at 5 39 12 PM](https://user-images.githubusercontent.com/1747920/74384185-c146f780-4dbe-11ea-9b75-9ecefcbdabf1.png)

**Comment by MorgothSauron** [comment]
> I can trigger the error on macOS Catalina 10.15.3 by giving focus to another application, just like the issue creator. I'm seeing the same stack trace, aside from the different source file location.
> ![Screen Shot 2020-02-12 at 5 39 12 PM](https://user-images.githubusercontent.com/1747920/74384185-c146f780-4dbe-11ea-9b75-9ecefcbdabf1.png)

I updated SN to 3.3.1 on my work computer running macOS 10.15.3 and I have the same error.

**Comment by BBCookie** [comment]
I have this problem too on Windows 10 (version 3.3.1). I can't save local backup to my hard drive, buttons isn't active. Message "Saving local backup..." in "footer" your program is hung and does not respond...

**Comment by Coriakin** [comment]
+1
Also reproducible on OSX 10.15.3.
Did not have any other version of SN on this machine prior to observing this.

**Comment by clyso** [comment]
+1

**Comment by baptiste-grob** [comment]
Hey everyone, version 3.3.2 is out and fixes this issue along with a couple of other ones ([Release notes are here](https://github.com/standardnotes/desktop/releases).) You can either use the app to update (Top menu -> Updates -> Install Update) or if it hangs download it from (standardnotes.org)[https://standardnotes.org/]

**Comment by greveritt** [comment]
@baptiste-grob Ah, thank you! I see my 5 year Extended subscription was a good investment. :-)

**Comment by MorgothSauron** [comment]
@baptiste-grob I updated to 3.3.2 on macOS and it works now. I'll update it on my Linux system when I'm back from work. Thank you for the quick fix.

**Comment by MorgothSauron** [comment]
@baptiste-grob I confirm that updating to 3.3.2 on Linux fixed the problem as well.
