### ISSUE TITLE
Quick Tags extension freezes the app

### ISSUE THREAD

**Issue by YoshK** [standardnotes/desktop#489]
On Windows 10,
installing the "Quick Tags" extension slow down quickly the app until it freezes completely.
The bug has been introduced sometime after I subscribe to premium (11 Feb 2020). I had the same issue with the "Folders" extension for some time but now it seems to be fixed.
Let me know if you need additional details.

**Comment by johnny243** [comment]
Hey @YoshK, what are your system specs? Also, what SN version are you using currently?

Thanks! :smiley:

**Comment by baptiste-grob** [comment]
I think a slowdown or freeze is something that can happen with the way we are handling extensions downloading/installing today, depending on what the OS is doing (lots of sync read/writes to the filesystem on the main thread which could just freeze the app on a slow drive)… We're working on making this part or the app more robust however!
If this is something that _continues_ to happen after the extension has finished installing, however… Then there might be something else going on 🤔

**Comment by baptiste-grob** [comment]
Fixed in version 3.3.5 :)
