### ISSUE TITLE
Freeze during initial login

### ISSUE THREAD

**Issue by pcrockett** [standardnotes/desktop#498]
After installing the desktop app, when logging in for the first time, Standard Notes starts to download extensions and initialize them. In the middle of this process, Standard Notes just freezes.

I then manually kill Standard Notes and restart it, the plugins finish downloading, and everything starts to work fine. I never encounter the problem again until I set up Standard Notes on a new PC.

I see this on both Windows and Linux.

I have the following extensions installed:

* Dynamic and Futura themes are activated
* No Distraction theme is deactivated
* 2FA Manager
* Batch Manager
* CloudLink
* FileSafe
* Quick Tags
* Bold Editor
* Simple Markdown Editor
* Simple Task Editor
* Note History Action Menu

As a side note, I often launch Standard Notes from the terminal, and here's the output I see just before the freeze:

> Checking for update for: Simple Markdown Editor Latest Version: 1.3.6 Installed Version 1.3.6

**Comment by JaspalSuri** [comment]
Thank for your providing all of those details! I'll pass this along to the team and try to reproduce this on my end as well.
