### ISSUE TITLE
Allow configuring the scale factor of the UI

### ISSUE THREAD

**Issue by netvl** [standardnotes/desktop#50]
I'm using Linux with a HiDPI display, and all electron apps I use detect this and scale themselves by the factor of 2x. This is too big for me, however, DPI of my display is closer to 144 rather than 192, and the perfect scale factor for me is 1.5. Electron apps usually support the chromium flag `--force-device-scale-factor=1.5`, and StandardNotes is not an exception, but it would be very nice if it was possible to configure this parameter through the UI in some kind of settings, like it is done in the Telegram Desktop application:
![screenshot_2017-02-27_16 53 49](https://cloud.githubusercontent.com/assets/280456/23362065/5d6262b8-fd0d-11e6-8353-3648ee294b04.png)

Alternatively, it would be equally good for me if StandardNotes was able to read some config file with command line options for chromium, like chromium itself does (it reads `~/.config/chromium-flags.conf`, that's how I configure it for my display).

I'd like to note that I can create a script wrapper passing all these options to StandardNotes, but nothing beats configuration through the UI, of course.

**Comment by mobitar** [comment]
Can you show me a screenshot of how it looks for you? Also, is the script you can create just for you or something that can be packaged in the app?

**Comment by netvl** [comment]
@mobitar sorry, I don't understand, a screenshot of what? Different scale of the UI depending on the flag?

And I meant a script like

```sh
#!/bin/sh
exec SimpleNote.AppImage --force-device-scale-factor=1.5 "$@"
```

which is definitely not something worth distributing :)

**Comment by mobitar** [comment]
So what is it exactly you think we should do? Let me know if you have specific resources that can help.

**Comment by netvl** [comment]
I think that the best way would be to add a configuration option like the one in Telegram Desktop (a screenshot how it looks is present in the top message).

**Comment by anavarre** [comment]
> So what is it exactly you think we should do? Let me know if you have specific resources that can help.

Yes, the Telegram scale factor works great. I have it set to a scale factor of 150%. Each time I'm launching the Standard Notes desktop app, however, it needs me to zoom in at least 3 times to have a comfortable font size.

**Comment by netvl** [comment]
Recently I've started using the desktop app again, and I have noticed that this problem is still there. Moreover, passing `--force-device-scale-factor 1.5` to the AppImage binary stopped working, so there is even no workaround now.

**Comment by mobitar** [comment]
Haven't started on this yet. But I'm making some improvements to the web/desktop app now, so I'll try to see if I can squeeze this in.

**Comment by hirusi** [comment]
@mobitar (or anyone else from the community) - are there plans to still look into this? It's very inconvenient to zoom twice on every single SN launch on the desktop.

**Comment by mobitar** [comment]
Windows or Linux? Window zoom state should be persisted (when you do ctrl/+). This works for me on Windows and Mac.

**Comment by hirusi** [comment]
Linux. It does not persist for me.
