### ISSUE TITLE
Snap Not Starting on Kubuntu

### ISSUE THREAD

**Issue by fundatillus** [standardnotes/desktop#500]
I'm running SN as a snap on a reasonably fresh Kubuntu 19.10 install and it won't start. It worked the first few times, but maybe after a background `snap refresh`, it stopped, though I did not notice if an update is what triggered it.

I've tried to start it from the KDE menu and the command line to no avail and no obvious errors. Other snaps work (Slack, Atom, Gitkraken, Chromium...), so I don't think it's an issue with the underlying snap services, though I have had similar issues in the past (Bitwarden).

Output of `snap run --strace standard-notes`: https://pastebin.com/9ya4i3XB

Current version installed is 3.3.1 (snap rev. 4) and when I ran `snap revert standard-notes` it ran 3.0.25 (rev. 3) and it also did not work (though it did previously). I also switched to the `--edge` channel with not luck. 

I've completely removed the app, also trying it with `--purge`, and then reinstalling with no luck.

**Comment by baptiste-grob** [comment]
Woah that's strange… Do you remember how your Bitwarden issue resolved itself by any chance? 😮 btw we're on version 3.3.3 right now, might be worth another try

**Comment by fundatillus** [comment]
I gave up on Bitwarden in the past because it works fine as a plugin on Firefox. 

I have 3.3.1 installed as of this writing with the same issue.

**Comment by johnny243** [comment]
You mentioned that you tried running the app from the console, did you get any output from that?

Please run the following command:

```bash
which standard-notes
```
It should be pointing to `/snap/bin/standard-notes`. Try running that directly in the console. Another alternative to run the app is `snap run standard-notes`

If you could provide a short screen recording of when you try to run the app, that would be nice! :+1:

**Comment by fundatillus** [comment]
`which standard-notes` points to `/snap/bin/standard-notes`

Running `snap run standard-notes` renders the same results. 

I'd post a video if I knew how, but literally nothing happens. Whether I launch from the KDE Application Launcher (e.g. "Start Menu") or from the command-line, it "appears" to start with no errors, but the app never starts.

**Comment by johnny243** [comment]
You can install `kazam` for screen recording:

```
sudo apt install kazam
```
But perhaps you could contact me via our Slack channel so we could troubleshoot this issue better?

**Comment by fundatillus** [comment]
I've had some other trouble with this system, so I've gone back to stock Ubuntu. If no one else is having this problem, we can close this issue. Thank you for your attention!

**Comment by JaspalSuri** [comment]
I'm sorry that you had to "revert" to using Ubuntu and about the other issues you were experiencing with Kubuntu. 

Have you considered using the desktop app's [AppImage](https://standardnotes.org/download/linux)? It will contain the latest version of Standard Notes for the desktop (currently v.3.3.5). Try installing it with [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) to make it a lot easier by going to the file's properties and setting it to run with AppImageLauncher.

**Comment by fundatillus** [comment]
Thank you for highlighting the availability of an AppImage! I don't know why I didn't find that sooner... too late now, though I'll keep it in mind when the inevitable hop back to KDE happens.
