### ISSUE TITLE
No Prompt For Desktop Shortcut Creation

### ISSUE THREAD

**Issue by infosisio** [standardnotes/desktop#505]
I am on Ubuntu 18.04 and don't get one all of a sudden.

I can no longer have a menu option for Standard Notes.

I do have desktop-file-utils installed. What's wrong?

**Comment by mobitar** [comment]
AppImage no longer support desktop integration out of the box. You'll need to use something like [appimaged](https://discourse.appimage.org/t/new-appimaged-optional-daemon-that-registers-appimages-with-the-system/87) or [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher).
