### ISSUE TITLE
No shortcut?

### ISSUE THREAD

**Issue by quirkyheadband** [standardnotes/desktop#506]
When I first installed Standard notes via appimage, I got the prompt and created a shortcut. No problem.

After upgrading from Ubuntu 19.04 to 19.10, I didn't get the prompt when running the appimage for the first time. I tried deleting the appimage and the configuration files (~/.config/Standard Notes) and reinstalling, but still no shortcut prompt.
 
I finally figured out that I could make a .desktop file in the ~/.local/share/applications/ directory, which worked. The only thing that wasn't ideal was that every time the app updated, I'd have to go into the .desktop file and change the file name to the new version number.

After reading another post about a similar issue, I decided to try the snap. Unfortunately, the snap wasn't updating correctly, and I was having issues with the snap not creating backups. Maybe something to do with the sandboxing of snaps? I dunno.

I tried switching back to the appimage today, but now my homemade shortcut isn't working.

Here's what I did:

I created a file in ~/.local/share/applications/ called standardnotes.desktop.

This is the content of the file:
_[Desktop Entry]
Version=3.3.3
Name[en_US]=Standard Notes
GenericName[en_US]=Standard Notes
Comment[en_US]=
Exec=/home/user/Standard-Notes-3.3.3.appimage
Path=/home/user/
Icon=~/.local/share/icons/hicolor/512x512/apps/appimagekit-standard-notes.png
Terminal=false
Type=Application
Categories=Application_

Anyone know what I'm doing wrong? I got this to work once before...

**Comment by mobitar** [comment]
AppImage no longer support desktop integration out of the box. You'll need to use something like [appimaged](https://discourse.appimage.org/t/new-appimaged-optional-daemon-that-registers-appimages-with-the-system/87) or [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher).

**Comment by quirkyheadband** [comment]
> I'm sorry to hear about the issues you're experiencing. I'll reach out to the team for further assistance!
> 
> In issue #505, Mo suggested using the [snap](https://snapcraft.io/standard-notes). Would that work in your case?

The snap did create shortcuts as expected. I'm going to try switching back to the snap and see if I can resolve the other issues I was having with that.
