### ISSUE TITLE
Timestamp format configuration

### ISSUE THREAD

**Issue by netvl** [standardnotes/desktop#51]
It would be really nice if it were possible to configure the timestamp format, at least from a set of predefined variants. I personally find the AM/PM system and m/d/y date format very confusing and unnatural and I would like to have 24-hour time format and d/m/y date format. I would also wager that I'm not the only one with such preferences, especially from European countries.

**Comment by netvl** [comment]
I should probably have created this in standardnotes/web, though, since all general ui-related issues go there. I'll create an issue there and close this one if you want.

**Comment by mobitar** [comment]
I get you. Trying to think of a good solution.

**Comment by mobitar** [comment]
v2 will now use localized dates.
