### ISSUE TITLE
SHA256 checksum is wrong

### ISSUE THREAD

**Issue by kaushalyap** [standardnotes/desktop#515]
I am trying to verify the integrity of `Standard Notes-3.3.5.AppImage` but SHA256 sum mentioned in SHA256 sum file is `4fa15212dc42e35f90063505811d491d68f15724319c2d791e126c8a50a2f7f3`
while computed SHA256 check sum of the file is `592f165b8df4ccf4bbe3a40920c93fd7f1ba1b1f33583e06cf84d98f9319cd2e`

I downloaded the file twice still the same.

**Comment by JaspalSuri** [comment]
Thanks for letting us know! I'll assign this to members of the team who I think can handle this best. :)

**Comment by mobitar** [comment]
Fixed, thanks. There is a strange issue with uploading AppImage artifacts to GitHub that cause the file to have mismatching signatures. The fix involves re-downloading the uploaded file and computing that signature.
