### ISSUE TITLE
No Icon or Start Menu (Ubuntu Linux)

### ISSUE THREAD

**Issue by m22rdy** [standardnotes/desktop#518]
I have standard notes downloaded to my home directory, it runs when I click on the .AppImage no problem and the application runs without an issue but it didn't install with an icon. I had a previous install with the icon with a previous iteration of Ubuntu, but after the upgrade I've never had an icon.
![standard_notes_no_icon](https://user-images.githubusercontent.com/30577436/78451740-4d6af200-767f-11ea-9f59-e4adf8abfbf7.png)

**Comment by baptiste-grob** [comment]
I'm closing the issue as this is an AppImage thing that we can't do much about. @m22rdy Feel free to reopen if you think there's something we should be doing about this 🙂
