### ISSUE TITLE
Importing text files

### ISSUE THREAD

**Issue by gordonbrander** [standardnotes/desktop#53]
Is this supported yet? I don't see any menu items, so I attempted drag/drop to import.

Drag/drop text file on to app.

What happens:
File is displayed in window (I'm guessing it's an Electron app)

What should happen:
File should be imported.

**Comment by mobitar** [comment]
The way this will be implemented is a converter from plain text to import file format SN expects. I haven't had the chance to do that but checkout https://github.com/standardnotes/sntools. Wouldn't be too hard to build.

**Comment by mobitar** [comment]
Plaintext importer is now up at https://standardnotes.org/tools

**Comment by onethirdzero** [comment]
I've used the importer to generate a SN-compatible file, but dragging and dropping it into the desktop app (and web app) still only displays the file in the window. Is there a step I'm missing?

I'm on v0.3.2, by the way.

**Comment by mobitar** [comment]
When you open the SN import file in a text editor, what do you see? Is it empty? Also, what is its file size?

Lastly, when you open Developer Tools in your web browser, do you see any errors?

**Comment by onethirdzero** [comment]
Here is the original file `test.md` (`31 bytes`).
```
# Test note

* Test content
```

Here are the `sn-import-file.txt`'s contents (`356 bytes`).
```
{
  "items": [
    {
      "created_at": "2017-04-13T17:20:01.056Z",
      "updated_at": "2017-04-13T17:20:01.056Z",
      "uuid": "e462c87d-e2d6-4c68-a486-95dd7228aa5d",
      "content_type": "Note",
      "content": {
        "title": "test",
        "text": "# Test note\r\n\r\n* Test content\r\n",
        "references": []
      }
    }
  ]
}
```

The Developer Tools console doesn't show any errors.
![2017-04-13 10_25_54-greenshot](https://cloud.githubusercontent.com/assets/15350437/25016174/c93832c6-2033-11e7-9153-14b0be396ca3.png)

**Comment by mobitar** [comment]
Can you show the console in the actual app, when you perform the import? Looks like this console screenshot is just of the file..

**Comment by mobitar** [comment]
Ohh wait a minute, sorry, just re-read your first message. You can't drag and drop into the window ;) You have to press "Account" in the lower left corner, then press Import.

**Comment by onethirdzero** [comment]
Ah, got it! I couldn't find those instructions on the Tools page. My first instinct was to check the File menus on the desktop app and I sorta got lost from there. Thanks!

**Comment by mobitar** [comment]
You're totally right, I need to add instructions to the tools page :)

**Comment by mobitar** [comment]
Drag and drop isn't supported. Good point, I'll see if I can disable that.

**Comment by RemiDesgrange** [comment]
https://stackoverflow.com/questions/31670803/prevent-electron-app-from-redirecting-when-dragdropping-items-in-window from this SO thread it doesn't seems so complicated. I can try to make a PR if you want. (opening a new issue for that ?)

**Comment by mobitar** [comment]
Go for it! (Although I won't be able to review it for at least a couple weeks)

**Comment by RemiDesgrange** [comment]
Ok see #206 when you have time it's quite simple though
