### ISSUE TITLE
External editors unavailable when offline

### ISSUE THREAD

**Issue by brortao** [standardnotes/desktop#54]
In the desktop app right now, the external markdown editors don't load if you open the app while offline.

It would be neat if they were cached locally. This may also save having to load the same editor many times if you want to use it for several notes.

**Comment by mobitar** [comment]
The current solution to this would be to host the extensions locally on your own computer. Which would be as simple as downloading it and setting it up a to a localhost server. Still DIY, but maybe in the future we'll focus on making this easier.
