### ISSUE TITLE
Backups -> Change Backups Location is not persisted

### ISSUE THREAD

**Issue by danielmanesku** [standardnotes/desktop#543]
I am trying to change the backup location with Backups -> Change Backups Location, but this change is not applied. The backups would still go in the default location $HOME/Standard Notes Backups.

I am using Arch Linux with Standard Noted 3.3.5, however this bug is there for a while.

**Comment by baptiste-grob** [comment]
Hey @danielmanesku, does this issue still occur on version 3.4.1? We've changed a lot of the app's internals.

**Comment by zedgoat** [comment]
On SN 3.4.1, changing Backups Location via `Menu -> Backups -> Change Backups Location` seems to have the intended effect on `5.6.8-1-MANJARO`.

Note though, on nominating `/home/<user>/sn_backup_2` it sets the location to `/home/<user>/sn_backup_2/Standard Notes Backups`, which can be disorienting when using `Menu -> Backups -> Open Backup Location` as it looks like the same directory on first glance.

**Comment by baptiste-grob** [comment]
We debated this issue internally, and went with this behavior to prevent accidents when moving notes 🙂

**Comment by zedgoat** [comment]
Ah, good point. Hitting a non-empty dir and polluting both. Is there room to debate spaces vs underscores or hyphens in the default name? ;)

**Comment by baptiste-grob** [comment]
We'd like the default name to use spaces but I understand having a different name could be desirable :) I'll be keeping this in mind, see if there would be a decent way to offer some kind of customization on this front.

**Comment by zedgoat** [comment]
@baptiste-grob yeah, it's literally just a preference in this case. Otherwise legal naming for most OS' =P

**Comment by baptiste-grob** [comment]
Since the original issue has been resolved I'll be closing it but feel free to hop on our [forum](https://github.com/standardnotes/forum) if you still want to get your suggestion in 😀

**Comment by danielmanesku** [comment]
Sorry for replying late. Confirming, it works in 3.4.1
