### ISSUE TITLE
Socks Proxy

### ISSUE THREAD

**Issue by niyumard** [standardnotes/desktop#546]
Hi!
I live in Iran and Standard Notes is blocked, if you add built-in support for socks5 it'd be great.

**Comment by JaspalSuri** [comment]
I'm afraid this is something that currently isn't possible as Electron doesn't support it. 

Would you be able to self-host Standard Notes?

**Comment by baptiste-grob** [comment]
Hey @niyumard, version 3.4 of the app supports your system proxy settings. Would that solve your issue?

**Comment by niyumard** [comment]
> Hey @niyumard, version 3.4 of the app supports your system proxy settings. Would that solve your issue?

I set the https_proxy variable and it worked, so in a sense yes.

**Comment by baptiste-grob** [comment]
I'm glad you can still use the app that way though I understand you'd like proxy support _in the app._ We'll be taking note of it!

**Comment by niyumard** [comment]
For anyone facing this issue who hasn't access to a http proxy, you can use a socks proxy too:
`./standard-notes-3.4.6-linux-x86_64.AppImage --proxy-server="socks5://127.0.0.1:9050"`

**Comment by JaspalSuri** [comment]
Thanks for the tip!
