### ISSUE TITLE
[macOS] Cannot move app window when developer tools are enabled

### ISSUE THREAD

**Issue by cyb3rz3us** [standardnotes/desktop#548]
**GENERAL**

App Version: 3.4.1
Platform: macOS
OS Version: 10.13.6 (High Sierra)
Editor: Does not appear to matter

**ISSUE**

If the **developer tools** are enabled _(View --> Toggle Developer Tools)_, the application window cannot be moved.

This occurs independently of whether or not the note in focus is locked (see issue #547)

The issue resolves as soon as the developer tools are closed.

**EXPECTED BEHAVIOR**

The appWindow can be moved despite the developer tools being enabled.

**STEPS TO RECREATE**

1. Enable the developer tools by clicking _View --> Toggle Developer Tools_.
2. Try to move the appWindow; note this is **not possible**.
3. Close the developer tools.
4. Try to move the appWindow; note this is **possible**.

**Comment by JaspalSuri** [comment]
I can reproduce this issue on my end as well. Thanks for the report!

**Comment by JaspalSuri** [comment]
Hi @cyb3rz3us, we weren't able to reproduce this issue in the latest version of the desktop apps on multiple OS's. I'm going to close this thread for now but please let me know if you're still able to reproduce it or have any other questions!
