### ISSUE TITLE
Columns for tags and note titles too short

### ISSUE THREAD

**Issue by CR0CKER** [standardnotes/desktop#55]
The new plus-buttons for adding tags and notes are great, but the columns for tags and notes are now very narrow, so most tags and note titles get cut off. Would be good if the width of columns could be adjusted. See screenshot.

<img width="997" alt="notes" src="https://cloud.githubusercontent.com/assets/6056387/23717819/a6102fa2-0435-11e7-9bea-f87b406c4a3a.png">

**Comment by mobitar** [comment]
Ahh damn. Accidentally included experimental changes geared towards making the app responsive in the latest release. That wasn't supposed to happen. Thanks for the heads up. I'm recompiling the app and this will be fixed in 0.2.8.
