### ISSUE TITLE
font-weights are thicker in desktop client 3.4.1 than 3.3.5

### ISSUE THREAD

**Issue by saegl5** [standardnotes/desktop#551]
Hi,
After upgrading the desktop client from version 3.3.5 to version 3.4.1, font-weight 300 looks like font-weight 400:
![font-weight difference](https://user-images.githubusercontent.com/63764270/81508823-7f055780-92d4-11ea-99d4-acbfa0962e1f.png)

The thicker font weight makes taking notes feel like programming code. Ugh!
Is this a regression or simply a feature of newer electron versions?

**Comment by JaspalSuri** [comment]
Hi, I've assigned this to our desktop and web dev so they can look into it. Enjoy the rest of your weekend!

**Comment by saegl5** [comment]
thx

**Comment by baptiste-grob** [comment]
With 3.4 we've upgraded to the latest Electron stable so I suspect the change comes from that yes… It looks like the fonts were considered _too thin_ before: https://github.com/electron/electron/issues/14948

**Comment by saegl5** [comment]
@baptiste-grob I see...
What a bummer! :-s

Interestingly, font-weight 300 in VS Code version 1.45.0 looks identical to that in SN 3.4.1, even though VS Code is using Electron v7.
I didn't check what Electron version SN 3.3.5 was using. Maybe it was using Electron v6 or earlier...
I guess VS Code version 1.45.0 got the font patch, and so did SN 3.4.1.

**Comment by baptiste-grob** [comment]
Yup we were on v5 before… Sorry about this :/
