### ISSUE TITLE
[Linux] A white line appears on the notes section when you press PgUp and PgDown

### ISSUE THREAD

**Issue by makarandh** [standardnotes/desktop#554]
This issue is more visible in one of the dark themes such as Midnight, Futura, Solarized Dark. It happens in the Plus Editor.

Issue: A white line appears at the bottom in the notes section. Please see screenshot. 
![Screenshot_20200512_152124](https://user-images.githubusercontent.com/38956972/81712835-9ecb8580-9464-11ea-8b97-901289c03d07.png)

Steps to reproduce: 

1. Switch to the Plus Editor and then change to one of the dark themes (e.g. Midnight).
2. Go to an existing note or create a new note, type in a few lines by pressing enter.
3. Go to the end by pressing PgDown a couple of times and go to the beginning by pressing PgUp. 

A white line will appear at the bottom as shown in the screenshot.

**Comment by JaspalSuri** [comment]
I'm sorry that you're experiencing this issue. 

I can reproduce this on the desktop app for versions 3.3.5 and 3.4.1 on Ubuntu 19.10. However, I can simply press page up/down once and the white line will appear while the toolbar will vanish. 

I can't reproduce this on macOS.

I'll be sure to report this back to the team; thanks for bringing this to our attention!

**Comment by makarandh** [comment]
This was fixed for me a long time ago. Don't remember which version. Closing it.
