### ISSUE TITLE
Linux: Upgrade from 3.0.24 to 3.0.25+ makes notes inaccessible

### ISSUE THREAD

**Issue by mirsev** [standardnotes/desktop#556]
Today I started Standard Notes, it was 3.0.24 version, the local notes opened successfully, and the application upgraded itself to 3.4.1. However when I run it and enter passphrase nothing happened, the screen remained with the passphrase prompt and nothing could be done beyond that.

After some investigation and downloading previous releases I have found that the problem appeared in 3.0.25 revision. The old 3.0.24 version works without a problem. So, for now I have to use the old version and disable automatic updates in order to have access to my notes.

Operating system: Linux Ubuntu 18.04.4 LTS
Any idea?

**Comment by mirsev** [comment]
After removing local Standard Notes configuration directory, then starting version 3.4.1 and signing in my account, the application let me in and synced with server, so everything is back. Now both the old and latest versions work without problem.

Can this issue be closed?

**Comment by JaspalSuri** [comment]
I would say that this issue could be closed. I'll let @baptiste-grob decided, though. :)

Thanks so much for all of this info; it'll help in future cases for users experiencing similar issues!

**Comment by baptiste-grob** [comment]
I'm happy you resolved the issue! This is valuable info that we'll have to keep in mind to ensure people can upgrade from older versions more easily. Thanks!
