### ISSUE TITLE
extensions don't update

### ISSUE THREAD

**Issue by saegl5** [standardnotes/desktop#557]
hi

for extensions, what is the update-checking frequency? \
i updated my extension an hour ago, but standard notes hasn't noticed a change yet \
private post with new version number is updated, and new release with zip file is posted in github

alternatively, is there a way to force extension updates? (besides re-installing extensions manually)

**Comment by baptiste-grob** [comment]
Hi @saegl5,
The app checks for extensions updates on every launch. More precisely, every time the web portion of the app loads (which is only once, when the app launches). If you want to iterate quickly you can press Ctrl/Cmd+R to reload the web portion of the app and it should trigger an update 👍
The package manager also logs this to the strandard output, so if you want to investigate you can launch the app from a terminal/command prompt :)

**Comment by saegl5** [comment]
console output:

> DevTools failed to parse SourceMap: file:///C:/Users/Ed/AppData/Local/Programs/standard-notes/resources/app.asar/dist/Transmitter.js.map

> DevTools failed to parse SourceMap: file:///C:/Users/Ed/AppData/Local/Programs/standard-notes/resources/app.asar/dist/standard-notes-web/javascripts/app.js.map

> DevTools failed to parse SourceMap: file:///C:/Users/Ed/AppData/Local/Programs/standard-notes/resources/app.asar/dist/sn-electron-valence/Receiver.js.map

> DevTools failed to parse SourceMap: file:///C:/Users/Ed/AppData/Local/Programs/standard-notes/resources/app.asar/dist/javascripts/renderer/renderer.js.map

> DevTools failed to parse SourceMap: file:///C:/Users/Ed/AppData/Local/Programs/standard-notes/resources/app.asar/dist/standard-notes-web/stylesheets/app.css.map
index.html:1 

> Refused to load the stylesheet 'https://fonts.googleapis.com/css2?family=Fira+Code:wght@300;400;700&display=swap' because it violates the following Content Security Policy directive: "style-src 'unsafe-inline' 'self' http://127.0.0.1:45653". Note that 'style-src-elem' was not explicitly set, so 'style-src' is used as a fallback.

> DevTools failed to parse SourceMap: http://127.0.0.1:45653/Extensions/org.standardnotes.advanced-markdown-editor/dist/dist.js.map

**Comment by saegl5** [comment]
I don't think the stylesheet would prevent updates. \
Also, [Themes directions ](https://docs.standardnotes.org/extensions/themes/) and [Publishing directions](https://docs.standardnotes.org/extensions/publishing) don't mention mapping; so, I don't think the SourceMap would prevent updates either. 

thanks for the tip, though (re: Ctrl/Cmd+R)

**Comment by baptiste-grob** [comment]
What do you mean by preventing updates?
What I meant by standard output was your terminal output. So on Windows you'd launch the app from cmd or Powershell, and on Linux/macOS from the Terminal.

**Comment by saegl5** [comment]
sorry, i had used developer tools (I edited the comment above to reflect that)

in powershell, `&"C:\Users\Ed\AppData\Local\Programs\standard-notes\Standard Notes.exe"` output:
> Latest: 1.0.1 | Installed: undefined
> ...

Regarding "preventing updates," the installed version was 1.0.0 but latest was 1.0.1, so I was just trying to find why the theme/extension was stuck on 1.0.0

turns out I forgot to add the version number in package.json
now, the theme/extension updates

**Comment by JaspalSuri** [comment]
I'm happy to hear that! I'll go ahead and close this. Let us know if you have any further questions; you're more than welcome to reopen this at any time. :)

**Comment by baptiste-grob** [comment]
Glad to know you got it working :D

**Comment by joshcsullivan** [comment]
Related: https://github.com/standardnotes/forum/issues/1008#issue-635614874

When running the above command to run SN from PS, I see this:

```
PackageManager: Extracting C:\Users\USERNAME~1\AppData\Local\Temp\Standard Notes\downloads\Markdown Pro.zip to C:\Users\USERNAME\AppData\Roaming\Standard Notes\Extensions\org.standardnotes.advanced-markdown-editor
(node:9832) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(node:9832) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
PackageManager: Installed component Markdown Pro
PackageManager: received sync event for: Markdown Pro (1.3.7) (deleted: false)
PackageManager: received sync event for: Markdown Pro (1.3.7) (deleted: false)
Uncaught exception SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (C:\Users\USERNAME\AppData\Local\Programs\standard-notes\resources\app.asar\dist\index.js:22:255307)
    at IncomingMessage.emit (events.js:210:5)
    at endReadableNT (_stream_readable.js:1183:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

OS: Windows 1909 Enterprise
SN: 3.4.2-beta1
Markdown Pro: 1.3.7
