### ISSUE TITLE
Allow tab indenting in editor

### ISSUE THREAD

**Issue by umamiMike** [standardnotes/desktop#56]
I would like to be able to visually indent things when I am taking notes.  It's not a show stopper, but thought I would mention it.  Great work on creating the app btw!

**Comment by mobitar** [comment]
Thanks! Indent support will likely be added to the Simple Markdown Editor extension sometime within the next week or two.

**Comment by mobitar** [comment]
Tab support has been added to the Simple Markdown Extension: https://standardnotes.org/extensions/simple-markdown
