### ISSUE TITLE
Where to obtain icon images?

### ISSUE THREAD

**Issue by Eduardo06sp** [standardnotes/desktop#560]
I noticed AppImage automatic shortcuts are no longer supported, so I created a desktop file to make it easier to access. I think others are doing the same from the looks of it.

I'm just missing the Standard Notes icon image, where would I be able to find it?

**Comment by JaspalSuri** [comment]
Hi, I’m sorry about the confusion! Fortunately there’s a way to get the app’s icon again by using [AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher).

Simply select it as the app to launch to AppImage when exploring the AppImage’s properties. 

Please let us know if you have any more questions!

**Comment by Eduardo06sp** [comment]
Super quick question, is there a direct link where I can download the image directly? I was just curious if there was a way to avoid using AppImageLauncher. Otherwise, I'll just suck it up and go over the installation guide :}

**Comment by JaspalSuri** [comment]
Hi, I’m sorry that I misread your message! 

Please try this link: https://standardnotes.org/assets/app-icon-blue.png

@baptiste-grob might have access to a better file. :)

**Comment by JaspalSuri** [comment]
Hi, I’m sorry that I misread your message! 

Please try this link: https://github.com/standardnotes/desktop/tree/dev/app/icon

It’s not a direct link, but contain direct links to icons of two different sizes.

**Comment by Eduardo06sp** [comment]
THANK YOU so much man! I feel like the fact that shortcuts aren't automatically crated should be pointed out on the Download page. 
Anyway, I appreciate your time :}

**Comment by JaspalSuri** [comment]
You're welcome, that's a good point! I'll be sure to pass that a long! The team is in the process of redesigning a lot of things, so I'll make sure that we don't miss this.
