### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by rramesh83** [standardnotes/desktop#562]
**Describe the bug**
I am at version 3.3.5. I have tried to update the program to the latest version.The installer loads but hangs at about a third through.

I see this through the program's "Install Pending Update" UI, and also when I download the updated file from GutHub.

I have tried clearing the cache before installing, but that didn't change anything.

**Desktop (please complete the following information):**
 - OS: Windows 8
 - Browser: Chrome
 - Version: 83.0.4103.61

**Comment by JaspalSuri** [comment]
@baptiste-grob Is this something that will be fixed in the next release?

**Comment by rramesh83** [comment]
Downloaded version 3.3.5.

First time attempted install, it failed silently.
Second time, it reported failure with the message "ffmpeg.dll is missing", and asked to try again.
But then Standard Notes automatically executed, and seem to work well.
Did the update, and 3.4.1 installed successfully.

Documenting this, in case it makes sense and is useful to you. Since it's working, am assuming the error messages are not critical errors.

Thank you very much for the timely response. Will keep this open, in case there are additional comments. Will close, if there is no more activity.

**Comment by baptiste-grob** [comment]
Glad to hear you got it working @rramesh83!
@JaspalSuri It's been difficult to pinpoint what is causing the issue from machine to machine. In any case, I've updated our electron-builder dependency for version 3.4.2. Let's hope it irons some things out.

**Comment by JaspalSuri** [comment]
Thanks, @baptiste-grob! Let's hope so. 🤞 

@rramesh83 I'm glad that despite some hiccups, it's working. Thanks for trying that! 

> Thank you very much for the timely response. Will keep this open, in case there are additional comments. Will close, if there is no more activity.

You're welcome! Don't worry about it. :)
