### ISSUE TITLE
Google Keep to Standard Notes converter

### ISSUE THREAD

**Issue by lzambarda** [standardnotes/desktop#573]
Hello everyone!

Not sure if this is the right place but I recently migrated from Google Keep to Standard Notes and I created [this small NodeJS script](https://gist.github.com/lzambarda/5e6cebd8356d3a2b5a2de01068745f5b) to convert my Google Keep Takeout export into a format compatible with Standard Notes decrypted backups.

It's clunky and probably does not cover everything but it was good enough for me!

**Comment by JaspalSuri** [comment]
Thanks again for working on this!

**Comment by mobitar** [comment]
@lzambarda nice work! Be sure to get it submitted here as well: https://github.com/jonhadfield/awesome-standard-notes

**Comment by lzambarda** [comment]
@mobitar thanks! That has already happened via a conversation on Reddit!
