### ISSUE TITLE
Home and End keys take the cursor to the start/end of entire note, not current line.

### ISSUE THREAD

**Issue by iedd** [standardnotes/desktop#575]
I was expecting the home and end keys to behave like other text editors, but instead they seem to treat the entire note as one line. Perhaps this is an issue with how the note is stored and organized or presented in it's view, but it would be great to get consistent behavior with other editors.

**Comment by JaspalSuri** [comment]
Hi, is this on macOS? If so, it could be a system-related issue in that case, which we might not be able to fix.

**Comment by iedd** [comment]
Ah, thank you. It is only an issue on macOS.

**Comment by JaspalSuri** [comment]
Thanks for letting me know! I currently use [BetterTouchTool](https://folivora.ai/) (paid) to set the <KBD>Home</KBD> and <KBD>End</KBD> keys to the `cmd+left arrow` and `cmd+right arrow` keyboard shortcuts respectively.
