### ISSUE TITLE
help / slack button 

### ISSUE THREAD

**Issue by umamiMike** [standardnotes/desktop#58]
clicking on the help / slack button  (on mac) takes me to "Slack https://now-examples-slackin-phikcdqtmt.now.sh/"  which is blank.

**Comment by mobitar** [comment]
Strange, clicking it takes me here: https://now-examples-slackin-phikcdqtmt.now.sh/

Is that link itself coming up blank? Or is the issue you're seeing that the url contains "Slack" as a prefix?

**Comment by umamiMike** [comment]
Strange...It works now.  Not sure why the difference, but I swear I tried it a few times over the course of a day or two before I mentioned it.

**Comment by mobitar** [comment]
This link was down before the latest update..maybe you tried clicking in an old version. In any case, if you notice this again, feel free to reopen.
