### ISSUE TITLE
Decrypted Backup Download only as zip-File

### ISSUE THREAD

**Issue by angobango** [standardnotes/desktop#596]
Hello
It seems that the update to the last version (3.4.2) broke the functionality for the decrypted .txt-file download. The offer to download the .txt-file is skipped and it goes directly to the download for the zip-file. this occurs on different systems, win 7.

opening the error console and downloading it again throws no errors, but there is a bunch of warnings, already BEFORE i download the backup:

```DevTools failed to parse SourceMap: file:///C:/Users/[USER]/AppData/Local/Programs/standard-notes/resources/app.asar/dist/preload.js.map

DevTools failed to parse SourceMap: file:///C:/Users/[USER]/AppData/Local/Programs/standard-notes/resources/app.asar/dist/Transmitter.js.map

DevTools failed to parse SourceMap: file:///C:/Users/[USER]/AppData/Local/Programs/standard-notes/resources/app.asar/dist/standard-notes-web/javascripts/app.js.map

DevTools failed to parse SourceMap: file:///C:/Users/[USER]/AppData/Local/Programs/standard-notes/resources/app.asar/dist/sn-electron-valence/Receiver.js.map

DevTools failed to parse SourceMap: file:///C:/Users/[USER]/AppData/Local/Programs/standard-notes/resources/app.asar/dist/javascripts/renderer/renderer.js.map

DevTools failed to parse SourceMap: file:///C:/Users/[USER]/AppData/Local/Programs/standard-notes/resources/app.asar/dist/standard-notes-web/stylesheets/app.css.map
```
can you take a look at it?

thank you very much.
regards
angelo

**Comment by JaspalSuri** [comment]
This appears to be the opposite issue of #485, unless there was a change that was made to decrypted backups that I've overlooked. I'll be sure to pass this along to the team for review! Thanks so much for bringing it to our attention!

**Comment by baptiste-grob** [comment]
This is intentional, the .txt file is now located at the top of the zip file 👍 This is to only prompt users for one download.
The DevTools warnings are something we're aware of but that don't impact the user experience whatsoever.
