### ISSUE TITLE
Strange Characters Ubuntu 20.04 "Change Backup Location"

### ISSUE THREAD

**Issue by himmelreich-it** [standardnotes/desktop#597]
When trying to change the backup location the following is visible:

![image](https://user-images.githubusercontent.com/5830411/91800693-bf913400-ec29-11ea-99d7-4315d794605b.png)

Ubuntu 20.04
Snap package from Software: 3.4.2

**Comment by himmelreich-it** [comment]
AppImage version does not have this issue and the Snap version is not maintained by you I imagine. I guess this issue is invalid

**Comment by JaspalSuri** [comment]
Thanks for bringing this to our attention! I'm glad to hear that the AppImage is working for you. :) 

Are you by any chance using multiple languages for your OS? I currently can't reproduce this issue.
