### ISSUE TITLE
[Windows] Application is Spamming the Sync Endpoint

### ISSUE THREAD

**Issue by Ryonez** [standardnotes/desktop#599]
The desktop client is currently hitting my self-hosted sync endpoint at a rate of about 2-3 requests a second. It looks fine, gets a 200 status code, but it just won't stop.

![image](https://user-images.githubusercontent.com/16157130/92101876-df934400-ee31-11ea-9614-bb85ef5dced3.png)

This is about 10 minutes worth.

**Comment by mobitar** [comment]
When did you set up your self hosted server? And through what method? What branch is it running (make sure it is master)? Can you pull in the latest code?

**Comment by Ryonez** [comment]
I've been setting up the server over the last two days via docker.

Sync server: standardnotes/syncing-server (latest)
Being routed through linuxserver's swag (letsencrypt) for https access: linuxserver/swag

The web client is run through the standardnotes/web:stable docker image. It doesn't appear to have the constantly syncing issue.

Web Client Version: 3.3.6
Desktop Client Version: 3.4.2

**Comment by mobitar** [comment]
As far as I know this issue can occur if the sync server silently fails to save items due to a misconfiguration issue. This occurs when running the development branch without proper env variables set.

@karolsojko do the specs above all sound like the right options/images?

**Comment by karolsojko** [comment]
Hi @Ryonez this issue occurs when you are using our stable mobile/destkop/web clients with the `latest` image of syncing-server which is currently under heavy work-in-progress and breaking changes. 

In order to fix this please use the syncing server image tagged with `stable` as described in here: https://github.com/standardnotes/syncing-server#standalone-instance

**Comment by Ryonez** [comment]
Sorry, wasn't awear of that tag. The documentation is a little fragmented and the dockerhub readme doesn't mention the tag. I normally look at the tags as well, but guess I looked at builds by mistake to boot.

I've switched it over to the stable tag, but it's still happening. I signed out of the desktop app as well, and that's caused no change. Web app is still showing no issues.

**Comment by karolsojko** [comment]
I think @johnny243 and @baptiste-grob might have more insight what could cause this issue on desktop

**Comment by Ryonez** [comment]
At some point the issues was resolved.
I haven't been checking with the sync server updates, but I did when the 3.5.6 desktop app was released. 
It not longer is displaying the system, and nothing looks out of place in the logs, so I'll close this issue.
Thank you for the hard work!

**Comment by JaspalSuri** [comment]
Thanks for letting us know and thank you for the kind words!
