### ISSUE TITLE
[Mac/Win] Trouble installing extension

### ISSUE THREAD

**Issue by ryanpcmcquen** [standardnotes/desktop#602]
I've used this extension for years without issue, but I grabbed the Mac app today and hitting some weird behavior:

```
Error installing locally: error-downloading https://github.com/ryanpcmcquen/standardnotes_org_mode_editor/archive/gh-pages.zip
```

Here's the extension:
https://github.com/ryanpcmcquen/standardnotes_org_mode_editor

The link it is having trouble with downloads if I visit it directly. I am on version 3.4.4 of the desktop app.

**Comment by ryanpcmcquen** [comment]
If I try to enable the extension, things get really interesting:
![org_mode_sn_mac_desktop](https://user-images.githubusercontent.com/772937/92819197-663da900-f37d-11ea-8cf8-2c5de20e563f.gif)


And this call keeps failing in the network tab:

```
curl 'https://ryanpcmcquen.org/standardnotes_org_mode_editor/' -H 'authority: ryanpcmcquen.org' -H 'upgrade-insecure-requests: 1' -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) StandardNotes/3.4.4 Chrome/80.0.3987.165 Electron/8.2.5 Safari/537.36' -H 'sec-fetch-dest: iframe' -H 'accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9' -H 'sec-fetch-site: cross-site' -H 'sec-fetch-mode: navigate' -H 'accept-language: en-US' --compressed
```

**Comment by JaspalSuri** [comment]
Trying [this link](https://gitcdn.link/repo/ryanpcmcquen/standardnotes_org_mode_editor/gh-pages/org_mode.json
) from the README worked fine for me. The extension hasn't had any performance issues in either the web app or desktop app. 

Can you reproduce this behavior if you restart the app?

**Comment by JaspalSuri** [comment]
I can reproduce the flickering issue in v3.4.2 of the desktop app on Ubuntu, but not on macOS or Windows.

**Comment by ryanpcmcquen** [comment]
I think it is a network issue ... maybe. I added a backup install link because gitcdn was being sonky today.

**Comment by JaspalSuri** [comment]
It could have been. I visited it directly and it triggered the download of the zip file within seconds.

**Comment by ryanpcmcquen** [comment]
@JaspalSuri, I am still having the issue and uninstalling and reinstalling.

**Comment by ryanpcmcquen** [comment]
It's worth noting that this extension works perfectly on iOS and the web.

**Comment by ryanpcmcquen** [comment]
@JaspalSuri, something is causing an infinite loop in the Mac OS desktop app:
![it_keeps_going](https://user-images.githubusercontent.com/772937/92959901-832bb800-f421-11ea-8c63-a809ec623bad.gif)

**Comment by JaspalSuri** [comment]
What errors are outputted to the console tab? You may need to expand them, copy them, and then strip out any sensitive info before sharing them here.

**Comment by ryanpcmcquen** [comment]
No useful errors on the console, same issue on the Windows app. In the browser (Firefox), I get a prompt to allow the extension permission to access the note. I never get that prompt on the desktop app.

**Comment by mobitar** [comment]
I was able to replicate this as well. Strange. Going to try to see if this is fixed with our 3.5 beta.

**Comment by ryanpcmcquen** [comment]
The plot thickens, now when installing, two copies attempt to get installed:
<img width="755" alt="Screen Shot 2020-09-15 at 10 02 18 AM" src="https://user-images.githubusercontent.com/772937/93241767-ad8bb700-f73a-11ea-8179-9d3b86c11495.png">

**Comment by ryanpcmcquen** [comment]
Now, when trying to install the extension on web, I am getting a CORS blocker:
```Content Security Policy: The page’s settings blocked the loading of a resource at eval (“script-src”). app.standardnotes.org:107:30
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://ghcdn.rawgit.org/ryanpcmcquen/standardnotes_org_mode_editor/gh-pages/org_mode.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).```

**Comment by ryanpcmcquen** [comment]
@mobitar, any ideas on the CORS issue in Firefox?

**Comment by mobitar** [comment]
I'm not sure rawgit was ever acceptable, as they are missing the correct headers for CORS. Did it work before? I'd say try your own CDN or one that returns proper headers (you can try S3).

**Comment by JaspalSuri** [comment]
I was able to reproduce the duplicate extension issue in the internal beta. I'll make an additional report for this.

**Comment by ryanpcmcquen** [comment]
I believe I at least resolved the installation issue in Firefox by switching to gitcdn.xyz, it seems to be working well again, hopefully it stays reliable ...

**Comment by baptiste-grob** [comment]
Thank you for providing all of this information by the way! We've logged your issue in our private tracker and I intend to take a deeper look at it 👍

**Comment by baptiste-grob** [comment]
Hey again! I noticed that the extension repo has no `package.json` file. Theoretically you don't need it, but the app is at least expecting it to be there at the moment. We're going to fix this on our end but in the meantime you can create a `package.json` file in the repository and it should fix the looping issue 🙂
