### ISSUE TITLE
There is a problem with the behavior of the enter key in the title field.

### ISSUE THREAD

**Issue by gif-byte** [standardnotes/desktop#604]
When I press the Enter key in the title field, the cursor moves to the body field.
This is a very difficult behavior for those using the CJK input method to use.
Change the behavior so that when I press the Enter key in the title field, it doesn't move to the body field.

**Comment by JaspalSuri** [comment]
Thank for your feedback! This issue seems similar to #603. 

What operating system and what tool(s) are you using to insert the characters?

**Comment by gif-byte** [comment]
> What operating system and what tool(s) are you using to insert the characters?

It is as follows.

OS: Windows 8.1 x64
Browser: Firefox 80.0.1 x64
IME: Google Japanese Input 2.25.3700.0

**Comment by gif-byte** [comment]
Oh! Sorry, this was a web issue.
I made a mistake. Close this.
