### ISSUE TITLE
Feature Request - Delete a note from desktop app

### ISSUE THREAD

**Issue by lucamosca1** [standardnotes/desktop#607]
I use this app since a couple of days, but what is the way to delete a note from desktop app? I can delete note only from my phone.

**Comment by JaspalSuri** [comment]
Hi @lucamosca1,

While we plan on making this easier in future updates to Standard Notes, currently (one way that) you can delete a note is by opening it > clicking on `Options` (located beneath the tags text field) > clicking on `Move to Trash` and then clicking on `Confirm` in the prompt that follows. 

To permanently delete the note, click on `Trash` underneath the `Views` folder > open the selected note and click on the `Options` menu > and then click on `Delete Permanently`. As the name suggests, this cannot be undone, but you can restore notes from your previous backups in the future. 

I hope this helps! Please let us know if you have any other questions!

**Comment by lucamosca1** [comment]
Thanks a lot :)

**Comment by JaspalSuri** [comment]
You're welcome! We hope you enjoy using Standard Notes! 🙂
