### ISSUE TITLE
"Your session has expired"

### ISSUE THREAD

**Issue by oliversturm** [standardnotes/desktop#609]
Standard Notes has stopped working for me today. I have three different installations I was using at once: one on Linux, one on Mac OS and one on an iPad. The Mac and Linux ones are up to date on 3.4.6, updated today - however, the update was not what caused the problem, the Linux installation was on 3.4.4 because the auto-update was also not working, but it already showed the same problem. The iPad version seems to be 3.0.23, although it is also the latest one available.

"Your session has expired. New changes will not be pulled in. Please sign out and sign back in to refresh your session."

It happened that I was running the Linux installation from the console, so I can tell you that there is no output at all related to this issue.

I signed out and back in on all three devices. I was then able to work again for about ten minutes or so, and just now the same error has popped up again on all three devices. What is going on?

**Comment by mobitar** [comment]
Sorry about that, please see here: https://github.com/standardnotes/forum/issues/1033#issuecomment-701404486

The first part of the issue should now be fixed. If you fall into the second camp, please hang tight while we get the fix deployed and propagated.

**Comment by oliversturm** [comment]
Thanks for the quick reply. Strange thing: I searched GitHub for "your session has expired" before posting this issue and I didn't find anything. Will try that again in a minute, out of curiosity. Hope the issue will be fixed soon!

**Comment by oliversturm** [comment]
Oh - that search issue would have been because that's a different repo where the issue was reported. Fair enough.

**Comment by mobitar** [comment]
So at this point, because you signed out and back in after seeing that first alert, if you sign out and back in again now, you should resolve the issue for good.
