### ISSUE TITLE
New backup folder structure deleted all backups

### ISSUE THREAD

**Issue by leafcutterant** [standardnotes/desktop#611]
This is connected to the theme of #588 and I'm sorry that I won't be able to document properly how to replicate it. It was a few months ago so I forgot, but the aforementioned issue prompted me to bring it up a least as a reminder to the devs. Maybe this will help to avoid anything similar happening in the future.

So a few months ago I had to reinstall the desktop app. A week after that I noticed that my auto-backups are no longer going to my old custom location (apparently I forgot to define my custom location after the reinstall). After redirecting backups where I wanted them to be, I noticed the new folder structure. I didn't like it, but neither did I understand it, so first I consolidated the old and the new backups to the folder I want them to be in, and then tried to tell SN to use that without making  parent folder. I was moving backups multiple times while the app was open and meanwhile trying to redefine the location through the app. I also vaguely recall a SN error message while I was doing this, but can't remember the text. After trying multiple times, I thought I got around the parent folder issue and considered it done (obviously wrong, you can only do that with the JSON hack explained in the issue linked above).

About a week later I checked on my auto-backups and was surprised to find that 1) all my backups from before the previous scheme, and 2) all backups after the new scheme but before I did the above fiddling, were gone. Only backups after the fiddling survived. I'm 100% positive it was not me deleting them. Thankfully I had backups of my backups so I could restore everything except the one week between the two events.

**Comment by JaspalSuri** [comment]
Hi @leafcutterant,

Thank you for describing this issue. I will look into this and make a report for the dev team to review.

**Comment by baptiste-grob** [comment]
Hey @leafcutterant, thanks a lot for your report, I looked into our logic for changing backup folders and encountered an edge case that you must've run into. I'm very sorry about the lost backups. This won't happen again starting with version 3.5 (https://github.com/standardnotes/desktop/commit/2128572a58dff92f20d2744dd4438fb5ec33619d)
