### ISSUE TITLE
"Your extended subscription expired"

### ISSUE THREAD

**Issue by JulianWgs** [standardnotes/desktop#613]
Whenever a new subscription period starts I always must manually click on "Reload" to update my subscription. That is annoying and should not happen, but usually that helps. Sometimes I can click all of the three banners away, but the one on the top left above the tags list. This leads to all extensions being frozen and the app is in an unusable state. Going in the extensions menu it says everything is valid. Restarting the app does not help.

I'm using Standard Notes 3.4.6 on Ubuntu 18.04.

- Why do I always have to manually click away all banners?
- Why are there multiple banners? (One should be sufficient)

Best regards
Julian

**Comment by JulianWgs** [comment]
Ok, no apparently everything has crashed and the Desktop and Web app have become completely unresponsive and unusable. I'm getting a 403 error on https://app.standardnotes.org/.

**Comment by mobitar** [comment]
Hmm, 403 errors are related to rate-limiting. It's possible that your app entered into an invalid state and entered into a loop of communicating with the server. Rate-limits are reset every 5 minutes.

Regarding renewals, admittedly the current architecture doesn't have the best method for handling them, and this will be a big focus for us in the upcoming several months. For now what I recommend is that anytime you see the expired subscription message, to open Extensions in the footer, press refresh on your status, then reload on the extensions. If that doesn't work, then just quit the app and restart after pressing Refresh in the Extensions window.

**Comment by JulianWgs** [comment]
Thank you for the quick response. Now all notes have been deleted. I'm seriously disappointed. I've written you an email.

**Comment by JulianWgs** [comment]
Notes are back. The issue was that some extension were installed multiple times.

**Comment by mobitar** [comment]
Glad to hear!
