### ISSUE TITLE
'Sync Unreachable' error dialog shows raw HTML

### ISSUE THREAD

**Issue by alstr** [standardnotes/desktop#615]
When offline I noticed the status window shows an error message with the formatting messed up.

<img width="317" alt="Screenshot 2020-10-06 at 15 25 07" src="https://user-images.githubusercontent.com/11612438/95222736-b8dd7a00-07f0-11eb-87fa-fbce646f094c.png">

Mac, version 3.4.6.

(As an aside, I think the app seemed to go slightly haywire with 'conflicted' versions popping up constantly even when I reconnected and cleared them, but I can't remember exactly or reproduce this right now, so won't open it as an issue).

**Comment by mobitar** [comment]
Sorry, we had some server turbulence this morning that should be resolved now, which includes the issue with duplicating items. Please let me know if you continue seeing this issue.
