### ISSUE TITLE
Protected Notes not asking for password to view in 3.5.0-beta7

### ISSUE THREAD

**Issue by stevesbrain** [standardnotes/desktop#619]
Hi there,

Just installed 3.5.0-beta7, and upgraded the encryption scheme. It appears that protected notes are no longer protected by a password when going to view (I checked it's still ticked in privileges).

It does take away the preview in the notes list as it's supposed to, but the viewing of the note itself is able to happen bypassing the password. Let me know if you need more details - thanks!

**Comment by JaspalSuri** [comment]
Hi @stevesbrain,

Currently the desktop and web apps use a global unlock (i.e. the passcode lock to serve as a lock for all notes) and do not offer any additional privacy-related UI protection for protected notes (as it has for several months now). I'm not sure if this behavior was different in the past, but I will check with the dev team.

**Comment by stevesbrain** [comment]
Oh, I must have missed that change. When I last used it, there was a local open passcode, and then you could separately add a UI-level protection for individual notes within (which was protected by the permissions system). If that's changed, no worries - however you can still flag items as "protected" which essentially means they have that flag, but for no reason (different to locked).

**Comment by JaspalSuri** [comment]
I apologize for the confusion provided on my part. I think I misunderstood something from a previous conversation about this with the team and there might be a bug that "confirmed" my understanding. 

Can you try removing all of the passcode and password privileges and then re-enabling them again (exactly as they were before or as desired)? I think that should fix the issue.

**Comment by JaspalSuri** [comment]
If you go to Account > Manage Privileges > and click on `Clear Session`, you can reset the behavior by selecting a shorter time span and leave it as the default amount of time before the application asks for your password and/or passcode. It might be set to a week at the moment.

**Comment by mobitar** [comment]
Nothing has changed here and this should be working as you expect.

The only way protection can be bypassed is if you set the "Remember" option to a term length you may have forgotten about. You can verify this by going to Account > Manage Privileges, and see if you see the "Clear Session" option. If you do, this means you won't be asked to authenticate. If you don't see that option, it means you should be asked to authenticate. Which is your case?

**Comment by stevesbrain** [comment]
Perhaps it was remembered as part of the conversion? I hadn't specifically viewed any before noticing that I could straight away after the conversion, but I can confirm that today it's not-remembering fine. Sorry for the false alarm!

**Comment by JaspalSuri** [comment]
No worries. Thank you for letting us know and thanks for testing out the new protocol. Please let us know if you run into any other issues or have any other questions!
