### ISSUE TITLE
Extension and fold sync issue

### ISSUE THREAD

**Issue by mem101296** [standardnotes/desktop#620]
I get two errors when opening the application:
- "There was an issue loading Folders"
- "There was an issue loading Task Editor"(Says this for all extensions)

When looking at the log under /home/$USER/.config/Standard Notes/logs it says the following:
``[2020-10-14 09:47:35.501] [info] Checking for update``

``[2020-10-14 09:47:35.519] [error] Error: Error: ENOENT: no such file or directory, open '/opt/standardnotes-desktop/app/dev-app-update.yml'``

``[2020-10-14 09:47:36.203] [info] Checking for update``

``[2020-10-14 09:47:36.204] [error] Error: Error: ENOENT: no such file or directory, open '/opt/standardnotes-desktop/app/dev-app-update.yml'[2020-10-14 09:47:35.501] [info] Checking for update``

``[2020-10-14 09:47:35.519] [error] Error: Error: ENOENT: no such file or directory, open '/opt/standardnotes-desktop/app/dev-app-update.yml'``

``[2020-10-14 09:47:36.203] [info] Checking for update``

``[2020-10-14 09:47:36.204] [error] Error: Error: ENOENT: no such file or directory, open '/opt/standardnotes-desktop/app/dev-app-update.yml'``

``[2020-10-14 09:50:44.836] [info] Checking for update``

``[2020-10-14 09:50:44.867] [error] Error: Error: ENOENT: no such file or directory, open '/opt/standardnotes-desktop/app/dev-app-update.yml'``

``[2020-10-14 09:50:45.472] [info] Checking for update``

``[2020-10-14 09:50:45.473] [error] Error: Error: ENOENT: no such file or directory, open '/opt/standardnotes-desktop/app/dev-app-update.yml'``

``[2020-10-14 09:50:44.836] [info] Checking for update``

``[2020-10-14 09:50:44.867] [error] Error: Error: ENOENT: no such file or directory, open '/opt/standardnotes-desktop/app/dev-app-update.yml'``

``[2020-10-14 09:50:45.472] [info] Checking for update``

``[2020-10-14 09:50:45.473] [error] Error: Error: ENOENT: no such file or directory, open '/opt/standardnotes-desktop/app/dev-app-update.yml'``

That file is indeed missing from the listed directory.

I'm running Arch 

Linux and recently updated the app through AUR. I can confirm the AUR package source is directly from Github. 
Both log file and screenshot attached. Notes have been blurred out for privacy purposes.

![Screenshot_2020-10-14_10-00-30](https://user-images.githubusercontent.com/19231888/96000047-1f1f5980-0dfc-11eb-85f0-310137f83b0c.png)

Log File
[main.log](https://github.com/standardnotes/desktop/files/5378671/main.log)

**Comment by baptiste-grob** [comment]
We've had reports pointing to invalid builds being distributed with third-party AUR packages. Does this happen when you use the AppImage as well?

**Comment by baptiste-grob** [comment]
Glad to read you got it working!

**Comment by rstrube** [comment]
I'm also running into an issue with AUR version of standard notes.  The reason I went the AUR route was because you don't have a Flatpak version of StandardNotes.  As a subscriber is there any way to vote for a Flatpak version?

**Comment by baptiste-grob** [comment]
Thanks for subscribing! Investigating to see if we have the bandwidth to support publishing to FlatHub is on the todo list 👍
