### ISSUE TITLE
Editor goes to the top of the list of notes whenever changes are synced

### ISSUE THREAD

**Issue by jmtb28** [standardnotes/desktop#627]
Whenever I edit one of my notes, the app gets to the top of the page after it syncs.

Version: 3.5.1
OS: Debian 10 (Buster)

**Comment by JaspalSuri** [comment]
Hi @jmtb28,

Are you saying that whenever you edit a note, the editor scrolls to the top after syncing/saving changes? 

What editor(s) does this issue occur in?

Can you log into the [web app](https://app.standardnotes.org/) and see if you can reproduce the same issue?

**Comment by jmtb28** [comment]
@JaspalSuri Yes, the editor scrolls to the top whenever it syncs. The editor that I'm using is the default one.

**Comment by JaspalSuri** [comment]
Thank you for taking the time to test it out on the web app and for the additional info. I have not been able to reproduce this, but I have created a report for this issue.

**Comment by jmtb28** [comment]
After further encounters with the issue, I've found that the app actually send me to the top, pinned note whenever it syncs, not the top of any note.

**Comment by JaspalSuri** [comment]
To double-check, are you saying that whenever the app syncs changes and says "All changes saved", the notes list is scrolled to the very top (i.e. every time that you type into a note) or every time that you load the app or hit refresh? If the latter, then that's expected. 

Also, please let me know if you are still experiencing this in v3.5.6 of the desktop app.

**Comment by jmtb28** [comment]
Problem solved in v3.5.6. Thanks.

**Comment by jmtb28** [comment]
Using v3.5.6, the issue occurs only to archived notes.

**Comment by JaspalSuri** [comment]
I was able to reproduce that issue! For me, it only happens when trying to edit Archived notes that are visible in the All Notes list. Doing so takes the user to the title of the top-most note. I've created a report for the dev team to review. Thanks so much for bringing it to our attention!

**Comment by jmtb28** [comment]
The same issue still occurs even after updating to v3.5.11.

**Comment by JaspalSuri** [comment]
I'm sorry to hear that. There haven't been any fixes (that I'm aware of) that were applied to address this issue yet as the dev team is currently focused on fixing migration and performance related issues, but rest assured that we've taken note of this issue and it will be fixed. I'm sorry about the inconveniences that have resulted from the issue and how it impacts your workflow.

**Comment by jmtb28** [comment]
This issue no longer happens on v3.6.1

**Comment by JaspalSuri** [comment]
That's great to hear; thank you for taking the time to let us know!
