### ISSUE TITLE
all user-installed extensions duplicated

### ISSUE THREAD

**Issue by chaserene** [standardnotes/desktop#636]
without updating, or any other potentially bug-triggering behavior, I started to have two of each extension I installed. this happened on 3.5.6, Windows desktop app. examples:

![](https://user-images.githubusercontent.com/64873595/100027752-b1e4e800-2ded-11eb-9f2c-e4d600ebc433.png)

![](https://user-images.githubusercontent.com/64873595/100027774-bf01d700-2ded-11eb-83c6-85fef4e163d7.png)

for some, UI elements are also duplicated. though e.g. for the Action bar, one instance works, the other (or sometimes both) give you error messages:

![](https://user-images.githubusercontent.com/64873595/100027814-d771f180-2ded-11eb-9e6b-0e42d720971b.png)

**Comment by mobitar** [comment]
What app version?

**Comment by chaserene** [comment]
sorry, some of the text I intended was missing the opening post. I repaired it now, including the version (3.5.6, Windows).

**Comment by mobitar** [comment]
Is it possible these were duplicated using a version older than 3.5, and you just noticed them in this version? Because v3.5.x should prevent any extensions for duplicating.

It's safe to just delete any duplicates for now.

**Comment by chaserene** [comment]
no, it definitely happened after my update to 3.5.6 (as in using that version, not as a direct consequence of the update). editors, themes, even components duplicated (with the exception of the ones that come as defaults, Batch Manager and Extensions).

update on the situation: I deleted the themes. to make things sure, I deleted both instances of each one and proceeded to reinstall them. in case you needed more info, I haven't deleted the editors. since I reported the issue, another doubling happened, so now I have two of each theme again, and four of each editor (the doubles also doubled):

![image](https://user-images.githubusercontent.com/64873595/100387926-877f6e80-3029-11eb-81d3-ed8637fa4d6d.png)

if anyone has an idea what's going on, let me know.

**Comment by chaserene** [comment]
I recently had [a crash on mobile](https://github.com/standardnotes/mobile/issues/327) that duplicated all my notes and tags. that may be connected to this bug, but it's not a 100% correlation because the first extension doubling happened without my notes doubling.

**Comment by chaserene** [comment]
by the way, ever since this happened, I have two extension repositories in the Extension window. do you think it's safe to delete one of them?

**Comment by JaspalSuri** [comment]
Yes, it's safe to delete either one. 🙂

**Comment by chaserene** [comment]
this never happened again since then, so I'm closing this. others can re-open it if the need arises.
