### ISSUE TITLE
Backups directory created when backups are disabled

### ISSUE THREAD

**Issue by ghost** [standardnotes/desktop#638]
The backups folder has started to be recreated everytime SN is launched, even with backups disabled.

It looks like it might be related to the introduction of the decrypt script in 1984a318?

--
macOS 10.15
Standard Notes 3.5.11

**Comment by JaspalSuri** [comment]
Nice catch! Thanks for bringing this to our attention. I was able to reproduce this and will report it over to our desktop dev for review.

**Comment by JaspalSuri** [comment]
For anyone who was following this thread (since the original poster's account was deleted), this issue should be resolved and the fix should be included in the latest stable build of the desktop app.
