### ISSUE TITLE
SetKeychainValue error during launch

### ISSUE THREAD

**Issue by bbc2** [standardnotes/desktop#639]
This is what I get when I launched the app after an update:

```
> standard-notes
extServer: Server started at http://127.0.0.1:45653/
18:26:01.519 › Checking for update
18:26:02.254 › Checking for update (already in progress)
Error occurred in handler for 'SetKeychainValue': [Error: No such interface “org.freedesktop.Secret.Collection” on object at path /org/freedesktop/secrets/collection/login]
18:26:02.435 › Update for version 3.5.11 is not available (latest version: 3.5.11, downgrade is disallowed).
```

The application UI looks only partially loaded.  It's almost all blank, just a menu bar at the top.

I use Arch Linux and I don't have any keychain service installed.

**Comment by JaspalSuri** [comment]
Hi @bbc2,

What version of the desktop app are you currently using? You can locate it by clicking on the **Account** menu button and scrolling all the way down.

Are you using the package provided by AUR? If so, I'm afraid that you'll have to switch to the [AppImage or Snap for v3.5.11](https://github.com/standardnotes/desktop/releases) of the desktop app. Before doing so, I would recommend signing into our [legacy web app](http://app-legacy.standardnotes.org/) (or [the latest stable](app.standardnotes.org), if the former doesn't work) and exporting a backup of your encrypted and decrypted data via the **Account** menu button as version 3.5.X (of our apps) contains several significant changes and updates.

[Here is the link](https://github.com/standardnotes/desktop/releases) that will contain the latest version of our desktop app at the top. You can reveal the list of packages by clicking on the triangular button next to the word **Assets**. If you accidentally install an older version of the desktop app, it will allow you to update to the latest version of the app. 🙂 If the update fails to work, you may need to manually update the app via the releases page.

Please let me know if this helps resolve the issue. Thank you for reaching out to us!

**Comment by bbc2** [comment]
I think I've always used AppImages from your release page on GitHub.

Right now, 3.5.11 and 3.5.9 both lead to a blank screen.  Sometimes they would prompt me for my key but then they would be stuck at "Generating key".  I've also tried 3.5.6, which loads my theme but not the notes.  If I try to log in, it's also stuck when generating keys.

Now that I have backups, perhaps I should try to remove local data and start from scratch with the latest version?

**Comment by bbc2** [comment]
I managed to reproduce the case when 3.5.11 prompts me for my key. Here it is stuck generating keys:

![generating_keys](https://user-images.githubusercontent.com/1645335/101765977-623b3780-3ae2-11eb-9e80-eda5024b18ad.png)

**Comment by JaspalSuri** [comment]
Hi @bbc2,

I apologize for the late response. Thank you for the screenshots! If you haven't reset the app yet, can you see if there are any logs stored in a similar path as the following? `~/.config/<app name>/log.log` If so, can you send them to either help@standardnotes.org or standardnotes@protonmail.com?

Can you also relaunch the app and try pressing `ctrl+shift+I` (not L) to toggle the developer tools, click on the `Console` tab, and send a screenshot of the output if you see any errors highlighted in red?

**Comment by bbc2** [comment]
I sent the logs to help@standardnotes.org.  I haven't tried to reset the app yet.

I had opened the developer console but didn't find anything that the log message hadn't already shown.  Anyway, here's a screenshot in case you see something interesting:

![console](https://user-images.githubusercontent.com/1645335/101981269-e0771580-3c6b-11eb-8193-9e90d5899935.png)

**Comment by JaspalSuri** [comment]
> I had opened the developer console but didn't find anything that the log message hadn't already shown. 

You're right; I apologize for forgetting about that. 

Thank you so much for taking the time to send the log file and this screenshot! You can reset the app now, if you'd like. Thank you for waiting.

**Comment by mobitar** [comment]
> I managed to reproduce the case when 3.5.11 prompts me for my key

Can you share the replication steps?

**Comment by bbc2** [comment]
> Can you share the replication steps?

Unfortunately, no. I've reset the app now (I deleted `~/.config/Standard Notes`).

After the reset I still get the same kind of error with 3.5.11:

![login_after_reset](https://user-images.githubusercontent.com/1645335/102090703-13610b00-3e1e-11eb-8dab-4a205585bfbe.png)

This problem is also present on 3.5.9 but not on 3.5.6 with which I can access my notes.

**Comment by baptiste-grob** [comment]
Hey @bbc2, can you look at `~/.config/Standard Notes/user-preferences.json` and tell us what the value of to `"useNativeKeychain"`? Should be true or false.
It looks like the app is able to get a value from your keychain but not set it, which is the first time we've seen this happen on a system. If it weren't able to get a keychain value it would have asked if you wanted to user local app storage instead.

**Comment by baptiste-grob** [comment]
Thanks a lot for your feedback, I'm happy that you got it solved. 🙂 We'll make sure future versions of the app check if they can read _and_ write to your keychain/keyring.

**Comment by alexaldrick** [comment]
Hi there, I get the exact same issue, and I change `UseNativeKeyChain` to `false` and clear the local data, and it does not work. I was originally using the AUR package, but switched to the latest stable AppImage. Any idea what else I could try? I will use the web app for now.

**Comment by baptiste-grob** [comment]
Hey @alexaldrick, the AUR package is not maintained by us so I don't know if something's happened there. Could you try running the AppImage from the command line, and share what it logs? When you say it doesn't work, do you mean you get something like a blank screen?
