### ISSUE TITLE
Privilege escalation in win10 desktop app

### ISSUE THREAD

**Issue by MagnificentMagician** [standardnotes/desktop#644]
It is possible to circumvent the account password protection when knowing the application password.

Steps to reproduce:
Change your privilege settings (Account -> Manage Privileges) to the following:
- note deletion requires app password only
- viewing protected notes requires account password only

Try to delete a note. App password will be required. Select "Remember for 1 hour" and supply the password. Then try to view a protected note.

Expected behaviour:
- Viewing the protected note requires the account password.

Actual behaviour:
- For one hour it is now possible to view the protected note, knowing the account password is not required.

System: Win10 20H2; SN 3.5.11

**Comment by JaspalSuri** [comment]
Hi @MagnificentMagician,

I was able to reproduce this. I think it's currently working as intended, but you raise a good point so I'll get in touch with the team for their thoughts on this and someone will get back to you ASAP.

**Comment by JaspalSuri** [comment]
Hello again @MagnificentMagician,

I spoke with our web/desktop app dev and they said that it currently works as intended as there is one shared timer for every privileged action. We have taken note that this could be communicated more clearly. I apologize for the confusion; thanks for bringing this to our attention!

**Comment by MagnificentMagician** [comment]
Thank you for the prompt response. The granular permissions are something I appreciated when choosing SN. I do believe there are multiple use cases for this. Therefore I would love to see the permissions working as described right now instead of just smashing all timers into one & updating the labels, especially because SN has a focus on security.
