### ISSUE TITLE
Unable to start installation of AppImage in Debian 10

### ISSUE THREAD

**Issue by engineer22** [standardnotes/desktop#649]
I'm trying to install the **standard-notes-3.5.14-linux-x86_64.AppImage** binary in Debian 10 Buster, and I get the following error after I make it executable as per the documentation:

**FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /tmp/.mount_standafuKeo1/chrome-sandbox is owned by root and has mode 4755. Trace/breakpoint trap**

Chown-ing the file, results to the same error. I then tried to install **NodeJS** & **NPM** so I can test installing the binary via NPM but I get this error:

**npm WARN npm npm does not support Node.js v10.23.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! code ENOLOCAL
npm ERR! Could not install "standard-notes-3.5.14-linux-x86_64.AppImage" as it is not a directory and is not a file with a name ending in .tgz, .tar.gz or .tar
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/testdev/.npm/_logs/2021-01-16T21_09_57_341Z-debug.log**

Downgrading Node version results to: 

**npm ERR! code E404
npm ERR! 404 Not Found: standard-notes-3.5.14-linux-x86_64.AppImage@latest
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-01-16T21_18_58_652Z-debug.log**

The only fix I found is set the _--no-sandbox_ parameter or change Kernel User Sandbox, but I don't want to run anything outside of sandbox for security reasons. 

Any way I can fix this and maintain security (I don't have Snap and I don't want to install it just for this software)?

**Comment by baptiste-grob** [comment]
Hey @engineer22, this issue has come up a couple of times before and I don't believe there's anything we at Standard Notes can do about it: https://github.com/standardnotes/desktop/issues/394

**Comment by engineer22** [comment]
Very unfortunate, thank you.

I guess I will be able to run it if I decide to compromise and run it without sandboxing, but at least it's an option for other users.
