### ISSUE TITLE
Syncing and importing is not possible

### ISSUE THREAD

**Issue by user6529576559** [standardnotes/desktop#65]
Hello,

In the Android app there is no possibility to save the notes to a TXT file onto the SD card or device memory. So I have exported it to Google Drive as encrypted format. Few days later border officers took my phone and didn't give back / human trash has stolen it / fallen into a river / insurgent forces have destroyed it.

So how can I restore my encrypted notes? In the desktop app there is no option to enter my credentials and download it from the server or import the encrypted TXT file.

**Comment by mobitar** [comment]
You can import the file easily using desktop/web. Simply click "Account" in the lower left and press "Import Data from Archive"

**Comment by user6529576559** [comment]
Ah, OK, I see it now. It was just so small I did not find it. But works well! I was searching in the upper menu but I didn't find it there. Maybe the bottom menu should be larger or something. Or have the same menus in the upper menu also. Or have everything in one place because for example currently there is a Help menu in the bottom and an other in the upper menu too.

I see that the desktop app is basically the same what we have for the web version, and in the web version there is that menu in the bottom. Anyways, if I didn't find it, other users can have problem with this also.

**Comment by mobitar** [comment]
Good point thanks. Currently the desktop app acts as a wrapper around the web app. Maybe in the future it will sync up menus.
