### ISSUE TITLE
Cannot open anything that requires password prompt

### ISSUE THREAD

**Issue by ingshtrom** [standardnotes/desktop#650]
I cannot manage privileges, cannot open protected notes, etc. 

I thought maybe it was because I didn't have a local password, so I added that but it doesn't seem to help.

I keep getting this error: 
<img width="541" alt="CleanShot 2021-01-26 at 11 25 04@2x" src="https://user-images.githubusercontent.com/571756/105873131-117c9100-5ff3-11eb-9f37-d67ace227314.png">

Please let me know what other data I can send to help sort this out. Thanks!

**Comment by baptiste-grob** [comment]
Hey @ingshtrom, sorry about this. We've published an update (version 3.5.18) which fixes this issue.
