### ISSUE TITLE
Dark mode for the application.

### ISSUE THREAD

**Issue by Sahil2004** [standardnotes/desktop#652]
Light mode makes me feel like blind. I love dark mode and I guess so does many. So, dark mode a huge need.

**Comment by JaspalSuri** [comment]
Hi @Sahil2004,

You can install one of the dark themes that we provide as part of [Extended](https://standardnotes.org/extensions) or try out the ones [provided by the community](https://github.com/jonhadfield/awesome-standard-notes/). 🙂 

A free dark theme for the desktop app is a feature that's part of our internal roadmap for v4, which is our next long-term update.
