### ISSUE TITLE
AppArmor denies file access for snap package

### ISSUE THREAD

**Issue by feinersaft** [standardnotes/desktop#653]
Hi,

while trying to open a settings file inside my home directory, the snap binary of standardnotes is denied by my apparmor profile:

```
Jan 30 15:34:29 ubuntu kernel: [24749.856278] audit: type=1400 audit(1612017269.344:43): apparmor="DENIED" operation="open" profile="snap.standard-notes.standard-notes" name="/home/chshrc/.dotfiles/config/.config/gtk-3.0/settings.ini" pid=21631 comm="standard-notes" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
Jan 30 15:34:29 ubuntu kernel: [24749.903525] audit: type=1107 audit(1612017269.392:44): pid=1236 uid=103 auid=4294967295 ses=4294967295 subj=unconfined msg='apparmor="DENIED" operation="dbus_method_call"  bus="system" path="/" interface="org.freedesktop.DBus.ObjectManager" member="GetManagedObjects" mask="send" name="org.bluez" pid=21631 label="snap.standard-notes.standard-notes"
```
The binary initially accesses /home/chshrc/.config/gtk-3.0/settings.ini which is a symlink to the file mentioned above.

The apparmor profile `snap.standard-notes.standard-notes` is in enforce mode.

I can try to edit the apparmor profile, but I wonder if the apparmor default profile for the snap package is supposed to behave this way.

If this issue is more related to snap, please tell me, where I should report the issue.

Regards,
chshrc

#### aa-notfiy -s 1 -v
```
Profile: snap.authy.authy
Operation: open
Name: /home/chshrc/.dotfiles/config/.config/gtk-3.0/settings.ini
Denied: r
Logfile: /var/log/kern.log

Profile: snap.standard-notes.standard-notes
Operation: open
Name: /home/chshrc/.dotfiles/config/.config/gtk-3.0/settings.ini
Denied: r
Logfile: /var/log/kern.log
```
#### snap version
```
snap    2.48.2
snapd   2.48.2
series  16
ubuntu  20.10
kernel  5.8.0-41-generic
```
#### snap info standard-notes
```
...
installed: 3.5.18
```

**Comment by baptiste-grob** [comment]
Hey @chshrc, thanks for the report! I'm not sure if this is a snap issue or a SN issue. Have you experienced this with other snaps as well?

**Comment by feinersaft** [comment]
Hi @baptiste-grob sorry for the long pause. I have moved from the snap package to the AppImage package, so I cannot comment on this issue anymore. Feel free to reopen, if applicable :)

**Comment by JaspalSuri** [comment]
Hi @feinersaft, thank you for letting us know. 🙂 We're sorry to hear that there might have been a Snap-specific issue that conflicted with AppArmor and are glad that the AppImage is working as expected. Please don't hesitate to reach out to us if you have any additional questions or feedback. 🙂
