### ISSUE TITLE
Endorse the Flatpak redistribution

### ISSUE THREAD

**Issue by proletarius101** [standardnotes/desktop#654]
Although standardnotes is an OSS, it's better to get your consent before we redistribute standardnotes desktop as a Flatpak. Although I'm aware that you don't want to spend time on maintaining this, actually you don't have to, just consent that we can redistribute this way.

Flatpak has much better user experience and security than snap and AppImage (at least for the current package without protection). It has seamless auto-update, and has wider audience than snap. Moreover, it has much better compatibility for CJK input which requires an input method.

https://github.com/flathub/flathub/pull/2086

**Comment by dtantono** [comment]
I think with this https://flathub.org/apps/details/org.standardnotes.standardnotes. this problem can be solved. But, we need to test it to ensure the app stability compared to another packaging such as: snap or Appimage.

**Comment by proletarius101** [comment]
Yeah, that's maintained by me, and the source code is here: https://github.com/flathub/org.standardnotes.standardnotes

**Comment by dtantono** [comment]
the flatpak is fine. But it also ask for keyring everytime I reboot my PC. that means I need to enable password reading on the startup like the snap app. isn't?

**Comment by proletarius101** [comment]
> the flatpak is fine. But it also ask for keyring everytime I reboot my PC. that means I need to enable password reading on the startup like the snap app. isn't?

Well, it's the standardnotes who needs the system keyring to store keys. So yes.

**Comment by dtantono** [comment]
I know in snap we use this command snap connect standard-notes:password-manager-service or to the GUI settings in ubuntu. But, how about this flatpak?

**Comment by xcffl** [comment]
Well, I'm not sure. Most distros should unlock the keyring as long as you're login to your system. Maybe you should refer to the arch wiki to see how to enable this behavior

**Comment by proletarius101** [comment]
> I know in snap we use this command snap connect standard-notes:password-manager-service or to the GUI settings in ubuntu. But, how about this flatpak?

Actually the keyring permission is granted at the installation time (by the `--talk-name=org.freedesktop.secrets` permission). So it shouldn't ask for permissions later.

> it also ask for keyring everytime I reboot my PC

Not sure what is it. Does it prompt for the password of the system keyring? If yes, you should auto-unlock your default keyring upon system login.

**Comment by dtantono** [comment]
I mean that every time I started standardnotes after I rebooted my PC. the popup fo insert keyring appeared. in snap, I can stop this by this command snap connect standard-notes:password-manager-service. But, for flatpak that is new to me. You mentioned for general purpose (--talk-name=org.freedesktop.secrets). So, to be specific. what is the right command for Standardnotes flatpak?

**Comment by proletarius101** [comment]
I don't think there's such a command. The flag was set in the build time and you grant the rights as soon as you install the flatpak. The problem must be in your libsecret agent, such as gnome-keyring. You'd better ask this question in the irc or matrix room of your desktop environment such as #gnome or #kde

**Comment by dtantono** [comment]
Well, that is weird because when I used snap standardnotes and there is an instruction to use that command and everything looks good on my ubuntu 20.04 until now. I will try to check ubuntu forum about this.
