### ISSUE TITLE
Tried setting passcode  lock -- app now hanging

### ISSUE THREAD

**Issue by archerships** [standardnotes/desktop#655]
I'm running  Standard Notes v3.5.16 (3.5.16) on Mac OS X (v10.14.6).  I tried to set the passcode, but now it's hanging with the message "Setting passcode...Do not close the application until this process completes".   It's been in this state for several hours, which does not seem like normal operation.   Suggestions for what to do next?   Thanks!

![Screen Shot 2021-02-01 at 8 43 42 AM](https://user-images.githubusercontent.com/77993343/106489540-bff85a00-6469-11eb-95e2-06ebb57ec546.png)

**Comment by mobitar** [comment]
Can you click Help > Toggle Error Console, and see if anything is reported in the console when you attempt to do this?

**Comment by archerships** [comment]
Thanks for following up.  Unfortunately, I was not able to duplicate.  When I closed and restarted, Standard Notes came up with the passcode lock set and no hanging.
