### ISSUE TITLE
Emoji not rendering properly in Elementary OS

### ISSUE THREAD

**Issue by Vyshnav2255** [standardnotes/desktop#663]
Most emojis are displayed in greyscale.
![Screenshot from 2021-02-23 21-31-48](https://user-images.githubusercontent.com/36617488/108870953-a4bedb80-761e-11eb-9547-8c7a67452c33.png)

**Comment by JaspalSuri** [comment]
Hi @Vyshnav2255,

Thank you for bringing this issue to our attention; I will put it on our list of issues to investigate further. I'm afraid that I wasn't able to reproduce this issue in Ubuntu (which is what Elementary OS is currently based on), so there might not be an easy fix for this issue at the moment.
