### ISSUE TITLE
Different bigger font after update to 3.6.0

### ISSUE THREAD

**Issue by igorkulman** [standardnotes/desktop#670]
Hi I have updated to 3.6.0 on macOS 11.2 and the font changed to a bigger size with some different typeface. I think this is the font that was previously shown when the app was started offline and the "proper" font could not have been loaded

![Screenshot 2021-03-02 at 21 22 11](https://user-images.githubusercontent.com/4746070/109709975-6769c900-7b9d-11eb-9507-5060d4cbeef1.png)

**Comment by JaspalSuri** [comment]
Hi @igorkulman,

Thank you for reporting this change. I've been able to reproduce it and will forward it to the dev team for review.

**Comment by baptiste-grob** [comment]
Hey @igorkulman, this bug has been fixed in a followup v3.6 update 🙂 what's in your screenshot is a monospace font, which you can toggle on or off in the 'Options' note menu.
