### ISSUE TITLE
Different number of notes

### ISSUE THREAD

**Issue by And96** [standardnotes/desktop#671]
What's the real number of notes?

All notes show **255** notes
![All Notes](https://user-images.githubusercontent.com/42185838/109714591-dc8bcd00-7ba2-11eb-91ed-74beebde59f9.JPG)

While in account panel there are **473** notes
![Right Number Of Notes ](https://user-images.githubusercontent.com/42185838/109714593-ddbcfa00-7ba2-11eb-9b5e-87df94f45611.JPG)

**Comment by JaspalSuri** [comment]
Hi @And96,

If you subtract the amount in the the **Account** menu from the total amount of notes that you have, then it would mean that you have (473 - 255=) 218 tags and items. The amount of tags that you have should be visible as well and you can subtract it from the remaining total (218 - # of tags) to determine the amount of miscellaneous items are stored on your account.

**Comment by And96** [comment]
Ok. Thanks

**Comment by JaspalSuri** [comment]
You're welcome! I'm going to close this thread for now. Please let us know if you have any additional questions!
