### ISSUE TITLE
Plus Editor not working on Standard Notes 3.6.1 on Debian 10 (buster)

### ISSUE THREAD

**Issue by makarandh** [standardnotes/desktop#675]
### Summary 

When Plus Editor is active, notes do not load. In their place the following error message is shown

> The extension was not found on your system, possibly because it is still downloading. If the extension doesn't load, try uninstalling then reinstalling the extension.

Edit: --
When I switch to a different editor, the notes do load. But since Plus Editor uses HTML and none of the rest of the editors do, so it is almost impossible to read and make sense of my notes without the Plus Editor. 
-- End of edit. 

### I have tried:

- Uninstalling and re-installing the Plus Editor extension to no avail. 
- Downloading an older version of Standard Notes -- version 3.6.0 and I see the same problem. 
- Closing, re-opening Standard Notes. Same problem is seen every time. 
- Downloading a fresh appimage of the latest version (Standard Notes 3.6.1) and it didn't work. 
- Deleting the config files and directory .config/Standard Notes (after which I had to log in again and it downloaded all my notes fresh) 

### Repro environment:

- Debian Linux 10 (buster)
- Standard Notes 3.6.1 (Appimage)
- Plus Editor 1.4.6

### Screenshot

![standard_notes_screenshot](https://user-images.githubusercontent.com/38956972/110748232-58d37f80-8237-11eb-86f6-e8ba0ae52ea8.png)

**Comment by JaspalSuri** [comment]
Hi @makarandh,

I'm sorry to hear that you were unable to use the Plus Editor. Thank you for the detailed report and for troubleshooting the issue! 

A fix has been make available for this issue and you should be able to use the Plus Editor without needing to make any changes on your end. 🙂 

> But since Plus Editor uses HTML and none of the rest of the editors do

You can use the Bold Editor to render the HTML as well. 🙂 

Please let us know if you're still running into any issues or have any additional questions.

**Comment by makarandh** [comment]
Thanks @JaspalSuri ! I can confirm that the problem is resolved and Plus Editor is working again.
