### ISSUE TITLE
Ability to collapse/condense sub folders/tags view in side bar

### ISSUE THREAD

**Issue by OddHouseGames** [standardnotes/desktop#679]
It would be great to have the option to collapse the fully expanded list of folders/tags for a condensed at a glance view. 

The vertical list can get quite long and having an option to click to only collapse or only show top level folders, perhaps showing an arrow to indicate sub folders/tags.

**Comment by JaspalSuri** [comment]
Hi @OddHouseGames, 

You can do this by clicking on the circle next to each tag to collapse any subtags that are nested beneath them. 🙂 

[Here's a quick demo](https://streamable.com/8p7ldp) on how to do this.

**Comment by OddHouseGames** [comment]
Thank you so much, I had no idea!

Where during on boarding does this feature get explained to new users? 

I'm not used to clicking on a bullet to collapse but super happy that the functionality is there!!

**Comment by JaspalSuri** [comment]
You're very welcome! Currently there isn't an onboarding process that I'm aware of, but it wouldn't be a bad idea to have one! We plan to make the Folders extension a native feature at some point in the future and redesign it to make this feature less inconspicuous.
