### ISSUE TITLE
Menu bar controls all disabled prior to unlock on Linux AppImage

### ISSUE THREAD

**Issue by phipolis** [standardnotes/desktop#684]
Using standard-notes-3.6.4-linux-x86_64.AppImage, the menubar controls are all disabled when Standard Notes is locked, including the close button. It would be nice if the generic hamburger menu options could be available too [View, Window, Updates, Help].

**Comment by baptiste-grob** [comment]
Thanks for the catch @phipolis 🙂 this will be fixed in an upcoming patch version.

**Comment by odyon01** [comment]
This is also the case for the Windows app. You can't close SN without first entering your application code? Assume this will also be patched for the windows app.

**Comment by JaspalSuri** [comment]
>I assume this will also be patched for the Windows app.

Hi @odyon01, that is correct. 🙂

**Comment by baptiste-grob** [comment]
Thank you for the reports! version 3.6.6 fixes this issue. 🙂
