### ISSUE TITLE
ui: overflow issue (CSS)

### ISSUE THREAD

**Issue by supermensa** [standardnotes/desktop#691]
In a document with more than a page of words (scrollable), the header of the document (area for document title and hashtags) is "scrolled up" — is out of view / cut off.  

<img width="1031" alt="header-cut-off" src="https://user-images.githubusercontent.com/1273852/114358864-b24f0700-9b73-11eb-8c1d-54279515b97e.png">

In a document with more than a page of words (scrollable), the bottom of the document is unreachable
as it is it hidden by the app footer.  

<img width="1023" alt="bottom-document-cut-off" src="https://user-images.githubusercontent.com/1273852/114358855-b0854380-9b73-11eb-94a3-b56044e6aa1f.png">

Desktop
OS X 11.2.3, Standard Notes 3.6.4

**Comment by JaspalSuri** [comment]
Hi @supermensa,

Thank you for bringing this issue to our attention. I'm afraid that I wasn't able to reproduce the issue on either the Windows or macOS desktop apps. I will take note of this and keep and eye out for similar reports.

**Comment by joshcsullivan** [comment]
Just had the same issue, SN Desktop 3.6.6 Windows 10.

I’ll try to reproduce tomorrow morning.

**Comment by m-walt** [comment]
I have the same issue on Kubuntu 20.10 with the snap installed.

Its only present in fullscreen mode. The scrollbar disappears and i cannot scroll down except clicking in the editor panel and moving the cursor down with the arrow keys. When i scroll down this way, the header disappears as shown above.

In windowed mode everything works fine.

**Comment by JaspalSuri** [comment]
Hi everyone, thank you for the additional reports. 🙂 I haven't been able to reproduce the issue, but I'll check in with the rest of the team on this and hopefully we'll be able to find out what's causing it.

**Comment by joshcsullivan** [comment]
Yes, I'm able to reliably reproduce the issue. It is when I have Standard Notes set to be using the entire height of the monitor, but only starts to become an issue when SN is using a certain width of the monitor.

Here is a screencast of the issue: https://www.loom.com/share/c8cd22899e0d4440974821da37099f38

**Comment by m-walt** [comment]
I am able reproduce it easily. Spin up a VM with plain Kubuntu 21.10, install the standardnotes snap package and the problem occurs every time...

The error doesn't occur with Ubuntu 21.10. With Ubuntu everything works flawless.

**Comment by JaspalSuri** [comment]
Hi @joshcsullivan, thank you for providing a screen recording of the issue! Please click on the **Options** menu in the note and let us know **Margin Resizers** are enabled. 

@m-walt, thank you for letting us know that you can reproduce the issue with the snap in Kubuntu but not Ubuntu. Can you check to see if the **Margin Resizers** option is enabled in your notes as well?

![image](https://user-images.githubusercontent.com/44656000/114810718-82fded00-9d61-11eb-9a98-39a5aab46e97.png)

**Comment by m-walt** [comment]
@JaspalSuri The Margin Resizers are enabled. The issue is resolved, if i disable the margin resizers!

**Comment by JaspalSuri** [comment]
That's great to hear; thank you for confirming!

**Comment by joshcsullivan** [comment]
Confirmed, turning Margin Resizers off stops the issue from occurring.

**Comment by baptiste-grob** [comment]
Thanks for the reports and followups everyone; [this commit](https://github.com/standardnotes/web/actions/runs/751752806) fixes the issue and will be available in the next update :)
