### ISSUE TITLE
Native support for M1 Macbooks?

### ISSUE THREAD

**Issue by tosziro** [standardnotes/desktop#693]
Any chance for native arm version for new M1 Apple chip? Thanks

**Comment by JaspalSuri** [comment]
Hi @tosziro, we plan to offer an desktop app that supports M1 Macs. However, we are still waiting on the security dependencies, that the desktop app relies on, to support M1 Macs first.

**Comment by superfreeman1989** [comment]
It's an electron app. It'll never be "native" lol

**Comment by tosziro** [comment]
Nevermind, I found out that iPad version works perfectly on M1 Macbook. Thanks for this great application.

**Comment by JaspalSuri** [comment]
That's great to hear! Thanks for the kind words. 🙂 Please make sure to export a regular set of local backups as needed since the desktop app generates one backup daily.

**Comment by WA9ACE** [comment]
If you wouldn't mind I would appreciate if this was reopend. The iPad app isn't exactly the same, and native builds of the desktop app would be very much appreciated going into the second generation of these laptops.

**Comment by tosziro** [comment]
Actually you right. iPad app is good, but as a temporary solution.

**Comment by AuthenticPumpkin** [comment]
Hi, I want to second this - not everyone uses the iPad apps on our m1 devices. A native app for arm64 is way overdue at this point of time, Apple Silicon is here to stay, please do make one!

**Comment by moughxyz** [comment]
I expect to have this by late December/early January.

**Comment by SebDanielsson** [comment]
I think this can be closed now👍
