### ISSUE TITLE
Update alert appears but restarting does not install update

### ISSUE THREAD

**Issue by aaronraimist** [standardnotes/desktop#70]
Often I will open Standard Notes, receive the update alert and restart my client to find that I am still on the same version. I assume this is happening because the alert is showing up as soon as my client finds out there is an update, but before it has finished downloading it.

![](https://www.dropbox.com/s/utndzwcvp5e3ac0/Screenshot%202017-04-26%2016.02.39.png?dl=1)

Solutions:
- wait to show the alert until the download has completed
or
- show a download progress bar on the alert so that the user knows when they can restart

Slightly unrelated but with either of these solutions I would suggest that you also add a button to restart Standard Notes in addition to the existing OK button so that I don't have to manually quit and restart. I would also prefer if this alert appeared in a separate window and did not take away focus from the text area. I have had important note taking interrupted by the update dialog several times which is quite annoying, especially when you are on the phone or multitasking in some other way.

**Comment by mobitar** [comment]
I just tested this on Mac 12.2.5 by downloading v0.3.3 of this app, waiting for the alert, quitting the app, and re-opening it, and it does indeed upgrade to 0.3.4.

This alert is presented after the download of the update is complete. Can you test again using the same steps I did and let me know if you see the same issue?

**Comment by mobitar** [comment]
Regarding annoyingness of alert, I am very afraid to push out updates frequently since I know how annoying it can be. That's why I only push out updates once every 2 weeks or so. Displaying the alert is optional, but if I don't, I'm afraid people won't quit the app to restart it and get the new version. And not sure how a separate window would work, if at all.

**Comment by aaronraimist** [comment]
Yeah I understand about the alert. Maybe you can add a more customized alert that is just a horizontal bar saying that a new update has been downloaded above the text writing area that shifts everything down to make room. It doesn't pull focus so writing can continue.

About the actual update, yes I just had this issue yesterday right before I reported it.

I had 0.3.3 installed on my Mac running macOS 10.12.4 and I opened Standard Notes. After a minute or so the update alert appeared and I clicked OK and quit the app. When I restarted I went up to the menu bar and clicked About Standard Notes or whatever it says to get the version and it said 0.3.3. A minute or two later the update alert appeared again. I did the same set of steps and was still on 0.3.3. I think on the third time it finally said 0.3.4. I have had this same issue with several previous Standard Notes updates.

**Comment by mobitar** [comment]
Strange. Where is your SN app located? /Applications?

**Comment by aaronraimist** [comment]
Should be. I'm away from my computer right now but I'll double check later.

**Comment by aaronraimist** [comment]
Yep it is located in the standard /Applications/ folder

**Comment by aaronraimist** [comment]
@mobitar not sure if there are any logs I can give you but just so you know this is still happening. Current app version is 1.0.1 (👍  on this better update dialog) and I've gotten the update dialog, restarted, and came back to the same version 1.0.1 about 5 times now.

**Comment by sersarov** [comment]
I have the same issue on MacOS 12.10.6 and app version 1.2.4. The app doesn't update to the latest after quitting and restarting. The update download just starts all over again.

**Comment by mobitar** [comment]
This issue has been fixed with [1.2.6](https://github.com/standardnotes/desktop/releases/tag/v1.2.6). Until you're on that version, to get your current version to update, quit the app, re-open it, and keep the window open for 60s without going anywhere. Then quit the app. It should work after that.

**Comment by sersarov** [comment]
Thanks, still experiencing the same issue on 1.2.6 though.

**Comment by mobitar** [comment]
Hmm. Strange. Worked for me. I'll do some more testing when I get the chance.

**Comment by mobitar** [comment]
Should be improved in v3.
