### ISSUE TITLE
stuck at "Waiting for key" after having network issues once during starting app

### ISSUE THREAD

**Issue by chaserene** [standardnotes/desktop#702]
today I had connectivity issues while Standard Notes started. it got stuck at this screen (see below) and didn't proceed even after my connectivity resumed (I gave it ample time to pick up). I restarted the app multiple times after this, with perfect network conditions, and it still didn't proceed.

I had to log out and log in to get back to normal, but this is a hassle because you need to enter certain setting each time you do this. it would be great if you could add some checks so that this doesn't happen!

desktop version 3.6.8

> Waiting for Key
> This note is awaiting its encryption key to be ready. Please wait for syncing to complete for this note to be decrypted.

![image](https://user-images.githubusercontent.com/64873595/117550217-5dea5a80-b03f-11eb-92a9-392605915eb0.png)

**Comment by JaspalSuri** [comment]
>but this is a hassle because you need to enter certain setting each time you do this.

Which settings are you referring to?

**Comment by chaserene** [comment]
@mobitar it happened again. I didn't do anything special -- my VPN failed to establish a connection at startup so I had to tweak it. meanwhile Standard Notes started up and got stock at the same stage. this time only one note is displayed in the note list. I also got the "Potentially Out Of Sync" message in the status bar.

**Comment by chaserene** [comment]
@JaspalSuri right, it;s just one setting, not multiple! I meant the passcode lock. I also had the auto-backup location in mind but now that sticks though logouts.

**Comment by mobitar** [comment]
Hmm, I wonder if the initial sync request to download your keys is failing, thus causing the inability to decrypt further items. I presume that this happens only when you're signing into an account? That is, you're not just opening a previously signed in application that has its data downloaded locally, then suddenly seeing notes turn from decrypted to unable to decrypt, right?

**Comment by chaserene** [comment]
> you're not just opening a previously signed in application that has its data downloaded locally, then suddenly seeing notes turn from decrypted to unable to decrypt, right?

on the contrary, I *am* opening an application that's been previously signed in and had all data locally, up to the last time it was open. it's starting up with the OS and asks for the passcode.

on the first occasion there were many notes (as seen in the screenshot in the opening comment), they appeared one by one, populating the notes bar. they were in "Waiting for keys" mode as soon as they appeared. the second time this happened, only one note appeared (I don't know which, the redacted part is a date, not the title).

**Comment by chaserene** [comment]
this never happened again since my last comment so I'm closing this. it can be re-opened if the need arises.
