### ISSUE TITLE
make the deletion of backups at logout opt-IN

### ISSUE THREAD

**Issue by chaserene** [standardnotes/desktop#703]
I think it's crazy dangerous that one can lose all their backups if they don't pay enough attention to all the text in this window. it almost occurred to me. please set that tick box to be *off* by default (it's currently on by default).

![image](https://user-images.githubusercontent.com/64873595/117550439-b5d59100-b040-11eb-9577-b36834adb87e.png)

**Comment by JaspalSuri** [comment]
Hi @chaserene, sorry for the inconvenience. A fix for this issue is on the dev team's todo list.

**Comment by antsgar** [comment]
This has been implemented on version 3.8.1 🙂
