### ISSUE TITLE
Resizing App window from Top edge issue

### ISSUE THREAD

**Issue by Parkertg** [standardnotes/desktop#706]
**Describe the bug**
I am unable to resize the app windows from anywhere on the top edge (non-maximized window). Both while locked or unlocked
From either side, or bottom, it works as expected. There is some sections on that do still work.. but only directly above the buttons.

**To Reproduce**
1. try resizing the app from the top edge with mouse in middle of the top edge.

**Expected behavior**
Expect any location on the top edge to allow resizing. (assuming window is in a non-maximized state

**Screenshots**
The circled areas indicate approximately where does resizing works
![Untitled](https://user-images.githubusercontent.com/46120246/117730172-90b46000-b1b1-11eb-9574-187970f2fda7.png)

**Desktop**
 - OS: Windows
 - Browser: app 
 - Version: 3.6.8

**Comment by JaspalSuri** [comment]
Hi @Parkertg, thank you for creating this report. I'll was able to reproduce the issue and will forward this over to the dev team for review.

**Comment by JaspalSuri** [comment]
Hi @Parkertg, are you able to reproduce this issue in the latest version of the desktop app (`v3.8.3`)? I wasn't able to in `v3.8.2` and `v3.8.3`.

**Comment by Parkertg** [comment]
@JaspalSuri , Not totally sure about those two versions. but I'm on 3.8.5 and its still an issue

**Comment by JaspalSuri** [comment]
Sorry about that @Parkertg. I'm afraid that I still cannot reproduce the issue in `v3.8.6` of the desktop app in Windows 10. I've tested it while the app is locked, unlocked, and has the dev tools modal open.

**Comment by Parkertg** [comment]
Strange.. yea I'm on `v3.8.6` now and its still an issue for me.   resizing only works in the areas in circles shown above. but does not work in the middle of the top edge

**Comment by Parkertg** [comment]
If I add 1 pixel margin to the title bar div, then it works correctly for me.
![image](https://user-images.githubusercontent.com/46120246/123160298-9f8a6580-d433-11eb-8eae-a6a8e618db24.png)

**Comment by JaspalSuri** [comment]
Hi @Parkertg, thanks for sharing that! 

>Perhaps it has to do with my resolution? 1080p with text/app scaling set to 125%

While I don't have a monitor with native resolution of 1080p, I changed the display settings to that resolution and level of zoom, and wasn't able to reproduce the issue. Have you found that the issue isn't reproducible if you change the "zoom" level from 125% to 100%?

**Comment by Parkertg** [comment]
@JaspalSuri , I've tried it on two separate windows laptops thus far.. issue persists on both. The zoom level doesn't seem to make any difference. so that's not the culprit it seems

**Comment by JaspalSuri** [comment]
Thank you for taking the time to test that, @Parkertg. 🙂 I hope we'll be able to find a way to reproduce this issue.

**Comment by Parkertg** [comment]
This is no longer an issue in 3.9.x releases
