### ISSUE TITLE
Tags not being imported correctly 

### ISSUE THREAD

**Issue by craig-s** [standardnotes/desktop#71]
From the desktop app, I exported my notes (decrypted) from one account, and then imported them into another account, All 100 notes were imported correctly, but the tags were a bit of a mess.
- all tags were imported
- the note counts were correct for some of the tags, but showed as less for others
- those tags that did show a note count, actually filtered that number of notes - but the notes included in that tag filter did not have the tag recorded as one of their tag values
- some notes, that originally had multiple tags, actually had some tags present as a tag value - although there was no link present for that tag

AN EXAMPLE
- original note had two tags, MUSIC and ARTIST
- the imported note was still included in the ARTIST tag filtering, even though it now only had one tag - MUSIC. And when the MUSIC tag was selected, the note was not included in that filter.

DATA
- the source account contained 100 notes and 42 tags
- a lot of the notes had multiple tags
- four of the tags contained white space (eg. "how to", "to do")
- the receiving account had all its notes and tags removed before the import

THEN THINGS GOT WORSE

After signing out and then back in again, none of the tags had note counts, and none of the notes had any tag values. And, the total note count was now reduced to 66.

**Comment by mobitar** [comment]
Hmm I just tested this with all my notes, I have about 240, many with multiple tags. The import was perfect—all the counts were correct, associations were correct.

Can you try the import one more time and tell me if you see the same results?

And is the data in the import file you have private, or can it be shared for debugging? If it's something with your file then it's a goldmine. Or maybe if you can reproduce it with a subset of your data that's shareable?

**Comment by craig-s** [comment]
I've already tried this twice, just to prove to myself that I hadn't done something wrong.

Unfortunately I do have some sensitive data included in my notes. And I'm reluctant to remove those until I'm sure the backup / restore is working correctly.

JUST A THOUGHT

Most of my notes were entered via the Android app, And its from this account I am exporting from (on the desktop). Could this have anything to do with the encoding issues between the web / desktop side and the Android side that has just been addressed ?

**Comment by mobitar** [comment]
Well as long as the desktop app shows your notes correctly and with the correct associations, then it shouldn't be the issue. So when you tried again, did the same exact results occur? Or was it random mismatches?

**Comment by craig-s** [comment]
Can't say categorically that it was exactly the same, as I did the first import yesterday and didn't take a note of what tag counts had what, Then, with today's import, I took my time and looked at what happened a little more. If not exactly the same, then very similar - including the clearing of all tag counts after the  signing out and then back in again.

**Comment by mobitar** [comment]
Importing needs to be perfect, so I'm glad you caught this. But it's really hard to debug without a source file. If you can find 5 minutes in your day, would you be able to open the import file and do a find and replace, and replace all note title/text with arbitrary data (even just a single letter will do)? Keep tag names in place. This way you can remove the sensitive data and share the file with me.

**Comment by craig-s** [comment]
I've managed to reproduce it with a test database of 10 records.
When I exported it from one account, cleared the data, then re-imported it into the same account again - all was fine. But, when I imported the same file into a different account - that's where the trouble starts.

**Comment by craig-s** [comment]
[SN Extract (10 note test).txt](https://github.com/standardnotes/desktop/files/966248/SN.Extract.10.note.test.txt)
Here's the file.

**Comment by mobitar** [comment]
Thanks! Let me play around with this.

**Comment by mobitar** [comment]
Ok, I've pushed out a potential fix to the web app. Can you try again on web?

**Comment by craig-s** [comment]
Yep, that looks better :-)
I tried both with the 10 note test file, and with my 'real' file of 103 notes.
Both imports look to be spot on !

What was the problem ?
I'm assuming that the extract process was working fine - so the exported data is fine.
So there must have been something amiss in the import process.
But what was triggering it, as not all imports were being corrupted.

**Comment by mobitar** [comment]
The issue was with when you tried to import data to a different account. The IDs of the items had to be changed, but it was not re-mapping the relationships. See this commit: https://github.com/standardnotes/web/commit/80c723b4002474807ee8c41e286048881fe7e00f

**Comment by craig-s** [comment]
Great stuff.
Glad you got it sorted.
Thanks.
