### ISSUE TITLE
[Help Wanted] End your session? This will delete all local items and extensions

### ISSUE THREAD

**Issue by whatsforbreakfast** [standardnotes/desktop#712]
I'm a bit confused about this prompt when logging out. My understanding is that notes are only stored locally, so if I do this I will lose all my notes? I have two devices running Standard Notes and one is already logged out, I want to log the other out but I strongly do not wish to lose all my data if I do so.

**Comment by whatsforbreakfast** [comment]
Thanks for taking the time to explain that, is there a way to verify my notes data is synced with your servers? I'm using a free account, not extended.

**Comment by JaspalSuri** [comment]
The best way to verify would be to sign into a new session on another browser by using the [web app](https://app.standardnotes.org) to confirm that all of your recent changes have been synced. Check the tags, sort the notes by date modified via the **Options** menu beneath the search bar, and confirm other recent changes that you recall making (and compare them to what you see in apps that you're already signed into). You can always export a backup via the Settings page in the mobile apps or the **Account** menu in the web and desktop apps.

**Comment by whatsforbreakfast** [comment]
Legend, thanks again!
