### ISSUE TITLE
Filling out title for new note is interrupted after first keystroke

### ISSUE THREAD

**Issue by pcrockett** [standardnotes/desktop#713]
## Steps to Reproduce

1. Open Standard Notes and unlock, let it load one of your existing notes. Here I just have an empty note with the title "I".
![01](https://user-images.githubusercontent.com/1114385/120916846-36bd9200-c6ac-11eb-9a37-5382e35aa86b.png)
2. Hit the "+" button to create a new note, see that the title is highlighted
![02](https://user-images.githubusercontent.com/1114385/120916860-5359ca00-c6ac-11eb-9b90-1db483ac5d10.png)
3. BUG: Start filling out the title. After typing the first letter of the title, you are suddenly interrupted - the title goes away and the previous note and current note are selected in the note list
![03](https://user-images.githubusercontent.com/1114385/120916888-92881b00-c6ac-11eb-9b08-84780f2dac9e.png)

## Other Observations

The weird selection behavior also seems to depend on what note you were viewing at the time when you hit the "+" button. For example, if I'm viewing the "E" note in step 1 above, then Standard Notes selects all notes between "E" and my new note:
![many](https://user-images.githubusercontent.com/1114385/120916991-15a97100-c6ad-11eb-8d04-70a51a7039f9.png)

It's easy to recover from this state; I can just select the note again and finish filling out the title, and everything works fine from there.

This is a very frequent bug. Sometimes Standard Notes seems to be in "bug" mode where the bug happens for every single note that I create, and at other times Standard Notes seems to work fine.

**Comment by JaspalSuri** [comment]
Hi @pcrockett, thank you for taking the time to fill out this detailed report! We're aware of this issue and plan to address it in a future update. The issue pertains to the new feature where users can select multiple notes with the `Shift` and `Control`/`Command` keys (users can then right-click the selection to activate/reveal the context menu).

**Comment by pcrockett** [comment]
Aha, `Shift` indeed is what was causing it. I updated today, looks fixed. Thanks for such quick turnaround.

**Comment by JaspalSuri** [comment]
Hi @pcrockett, you're very welcome on behalf of the dev team. Thank you for letting us know that it's currently working as expected!
