### ISSUE TITLE
Styling bug in tags after upgrade to 3.8.1

### ISSUE THREAD

**Issue by dec0dOS** [standardnotes/desktop#722]
Hello, Standard Notes team!
After upgrade to 3.8.1 on some themes like (Overcast, Yaru) an additional line was added that does not seem to be here before.
It is reproducible on macOS and the web.
Screen recording on 3.8.1:
https://user-images.githubusercontent.com/14824142/121955650-e52a9c80-cd68-11eb-94d0-b0da51a493b8.mov

Before upgrade (3.8.0):
![121789883-791e2c00-cbe2-11eb-987c-b0e246507b78](https://user-images.githubusercontent.com/14824142/121958000-ced21000-cd6b-11eb-8642-3340cfc29aba.jpg)

**Comment by antsgar** [comment]
Hi @dec0dOS! Thank you so much for bringing this to our attention 🙂 we've just deployed a new web version (3.8.2) with a fix for this issue, please let us know if it's resolved after upgrading. Desktop version is on its way, should be available soon.
