### ISSUE TITLE
Task Editor not displaying correctly on MacOS

### ISSUE THREAD

**Issue by menkari** [standardnotes/desktop#724]
Have just updated to 3.8.6 on Mac (Big Sur)

Task Editor is not longer displaying correctly. When I switch the editor back to `Plain Editor` The data is available. I've confirmed that the issue is isolated to Mac as the task editor displays correctly on Windows and Android.

I've looked under the hood at the developer tools and it looks as though the body is missing the data or is not populated when the `ngIf` condition is satisfied.

![image](https://user-images.githubusercontent.com/531131/122666018-41b90c00-d1ee-11eb-9151-c30e10ac8182.png)

**Comment by JaspalSuri** [comment]
Hi @menkari, sorry to hear that. I'm afraid that I wasn't able to reproduce the issue. Can you open the Extensions menu and reinstall the the Task Editor extensions to see if that resolves the issue? Please let us know how that goes.

**Comment by menkari** [comment]
Hi @JaspalSuri that did the trick! Thank you
