### ISSUE TITLE
Failure to authenticate sign in and sync on v3.8.13

### ISSUE THREAD

**Issue by nichrishayes** [standardnotes/desktop#729]
As the title suggests, after updating to the newest version, syncing stopped working. I tried to sign out and back in in hope of fixing the sync issue and now can't authenticate my account.

This is true on both MacOS and iOS. Thoughts?

**Comment by antsgar** [comment]
Hi @nichrishayes, thank your for reaching out. Apologies for this inconvenience, we're currently investigating the issue and will let you know as soon as it's resolved

**Comment by nichrishayes** [comment]
Edit: iOS version would be 3.6.17, whereas MacOS version is listed in title.

Not sure if changes have been made yet on your end, but I was just able to authenticate a sign in and sync on both devices!

**Comment by antsgar** [comment]
The issue has been resolved and everything is currently back to normal 🙂 please don't hesitate to let us know if you run into any more problems!

**Comment by fbartels** [comment]
Hi @antsgar,

what exactly was the solution here? With automatic updates I got 3.8.16 installed yesterday and now also can no longer use the desktop client (it asked me to reenter my credentials, but would not accept them, after signing out I cannot sign in because of an `Unknown error.`).

I'm running the old Ruby based syncing server, is the newer desktop client no longer compatible with it?

**Comment by mobitar** [comment]
Please see related thread: https://github.com/standardnotes/mobile/issues/464#issuecomment-879898436

> The latest version of the clients have been updated to rely on the latest version of our server infrastructure. So I'm afraid there's no way to move forward without upgrading your server infra.

**Comment by fbartels** [comment]
@mobitar thanks for the link. Do you have a changelog where you announce these kinds of breaking changes?

**Comment by JaspalSuri** [comment]
We do not at the moment, but we may in the future.
