### ISSUE TITLE
Add ability to disable (toggle) note text preview in list

### ISSUE THREAD

**Issue by notDavid** [standardnotes/desktop#73]
The list shows not only the title of a note, but also the first approximately 40 (?) characters of the text.
So when i have the app open with people sitting next to me they can read all my "sensitive" notes...

**Comment by billymedia** [comment]
Agree, would be nice to remove this, or at least make it optional.
Also, when using the html editor, it displays the html tags making it look untidy.

**Comment by mobitar** [comment]
You can actually now do this in the 2.1 beta: https://github.com/standardnotes/desktop/releases/tag/v2.1.0
