### ISSUE TITLE
Ver 3.1.8 - MacOS - Can't load theme/extension editor

### ISSUE THREAD

**Issue by movewho** [standardnotes/desktop#732]
I just update to 3.1.8 and after then, i can't use standard note ;( Please help me.

I open `Toggle Develop Tools` and i see this error. what is wrong with me?

![image](https://user-images.githubusercontent.com/5396414/126858506-6456c49f-d365-4522-aefa-70ae744e3c4a.png)

**Comment by JaspalSuri** [comment]
Hi @movewho, which operating system are you using? 

Please [download](https://standardnotes.org/download) the latest version of the desktop app (v.3.8.17) and let us know if you still run into the issue.

**Comment by movewho** [comment]
Sorry I post wrong version, I using version 3.8.18. When i restart my mac, i used normally. Maybe I use openVNP app for work make  StandardNotes crash. 

Thanks for your support,
