### ISSUE TITLE
Add ability to sort notes alphabetically

### ISSUE THREAD

**Issue by johncock** [standardnotes/desktop#74]
Having the option to sort notes alphabetically accordning to the title enables you to find the note you're looking for a lot faster.

**Comment by craig-s** [comment]
I agree with this request.
As a general sort option, this would be great.
Or, at lease, within a tag filter or within search results. This does actual help with locating a specific note.

**Comment by ClarkeCC** [comment]
+1

**Comment by ElCoyote27** [comment]
+1
This allows to detect duplicates faster too (I just went through this on close to 2,000 notes)

**Comment by mobitar** [comment]
This is now available in v1.2.5.
