### ISSUE TITLE
Stripping Metadata from Backups?

### ISSUE THREAD

**Issue by alat-rights** [standardnotes/desktop#740]
Hi! I'm just trying out Standard Notes on the desktop.

I noticed that the backup feature keeps a lot of metadata unencrypted. Would it be possible to keep track of notes by a UUID so that at least their post titles can be encrypted?

Also, may I ask about the thinking behind keeping exact timestamps unencrypted (is this perhaps necessary for some part of the app to function)?

I apologize if this is overly obtuse. Standard Notes is truly amazing and I want to make sure that it'd be right for me to use all the desktop too.

**Comment by alat-rights** [comment]
Oh! My apologies. It looks like I missed that the backups seemingly store backed up data in plain text? (image attached)

![image](https://user-images.githubusercontent.com/54920181/129065324-d91d2588-5a4e-47b4-b74a-87fa96826652.png)

**Comment by mobitar** [comment]
This means this backup was created when there was no account or passcode set up in the application.

**Comment by alat-rights** [comment]
Gah! Got it, sorry!
