### ISSUE TITLE
Locked keychain

### ISSUE THREAD

**Issue by lasseQ** [standardnotes/desktop#744]
I have Debian 11 and standard-notes-3.8.18-linux-x86_64.AppImage
Opening it asks my password but don't accept it.

"Error occurred in handler for 'SetKeychainValue': [Error: Cannot create an item in a locked collection]"

**Comment by mobitar** [comment]
Can you see if this helps? https://github.com/shiftkey/desktop/issues/507

**Comment by lasseQ** [comment]
That was not standardnotes fault, somehow keyring on Debian were corrupted, or something, All is working fine now.

**Comment by lasseQ** [comment]
That was not standardnotes fault, somehow keyring on Debian were corrupted, or something, All is working fine now.
