### ISSUE TITLE
Add option to have the same default font on desktop client as on Android.

### ISSUE THREAD

**Issue by johncock** [standardnotes/desktop#75]
Having the same smooth font by default on desktop client as on android makes for a more fluid and unified experience on all your devices. Is it Roboto in the Sans Serif family that is standard on Android?

Its challenging to search the context to find the line where I left off when moving from my Android device to the desktop client and vice versa due to the different fonts.
Monospace font doesn't fit very well on Android in my opinion.

**Comment by mobitar** [comment]
Monospace option is available on desktop now.
