### ISSUE TITLE
Can't change password

### ISSUE THREAD

**Issue by kslstn** [standardnotes/desktop#759]
I want to change my password but encounter a few issues:

1. In the step where I'm asked to download a backup, neither the encrypted nor the decrypted action seems to happen
2. After providing a new password, I get a message saying 'Something went wrong while changing your password. Your password was not changed. Please try again.'
3. The application then gets stuck at: 
````
Step 4 — Encrypt and sync data with new keys
Your data is being re-encrypted with your new keys and synced to your account.

Do not close this window until this process completes.

Unable to process your password. Please try again.
````

At that point I can't close the modal (because 'Cannot close window until pending tasks are complete.') and I can't close the application (CMD+Q/Quit Standard Notes has no effect).

**Comment by kslstn** [comment]
I was able to change my password with the web app in Firefox without any issue.

**Comment by mobitar** [comment]
It sounds like you're using an outdated version of the desktop app, since "Step 4" in the password change process is part of an old process. Your desktop app may be 1+ years out of date. Should be 3.8.x.

**Comment by kslstn** [comment]
Thanks! Now I can log in again too :)
