### ISSUE TITLE
Clicking on the App Icon Opens App With A Differnent Icon Acting as It's Window Icon

### ISSUE THREAD

**Issue by OriginalFannibal** [standardnotes/desktop#76]
I'm sorry but I just don't know how to properly describe my problem.  
I am using Standard Notes on Fedora Workstation 25. Launching the app by clicking on the app icon always results in a new icon representing it on my dock for the duration that the app is open. The launcher icon is unlinked from the app it just launched. Clicking on it launches the app again.  

Maybe the image could help me explain better.  

![screenshot from 2017-06-14 08-26-00](https://user-images.githubusercontent.com/20235646/27425744-fc0b670a-5728-11e7-9f4a-5f25f331d57e.png)

My Standard Notes launcher, as generated by the AppImage is third from left while the new icon that it creates for the instance of the app that's been launched is the last one. The left-most one.

Ideally, the launcher icon would be representing the app window, not a new (generic looking) icon.

**Comment by OriginalFannibal** [comment]
I'm so, so sorry. I screwed up left and right.  
🙈   
The icon that's created is the right-most one. The one with that tiny blue bar underneath it. That's what I have to click on to minimise or maximise the currently open instance of Standard Notes and right-clicking on that is what lets me quit the current instance. Quitting makes that icon disappear. 

The actual Standard Notes icon (which is the one third from _right_), acts like it hasn't been clicked at all. But that's what launches the app along with the other icon.

**Comment by mobitar** [comment]
Hmm interesting. I believe that might just be how AppImages function. I'll have a look at this when I can. Thanks for the report.

**Comment by OriginalFannibal** [comment]
Tried it with another AppImage (Etcher) and that doesn't have this problem.

**Comment by OriginalFannibal** [comment]
I moved to elementary OS now and things work the way they should on it. Would you like me to close the issue? I don't see myself returning to Fedora anytime soon so I don't think I can reproduce this issue. Has anybody else complained about having the same problem?

**Comment by mobitar** [comment]
Ya you can probably close it. We can re open it if others report the same issue.

**Comment by OriginalFannibal** [comment]
So, I got back on Fedora again and faced the same problem except I managed to resolve it this time.  
I edited the `.desktop` file to add the `StartupWMClass` key and set it to `Standard Notes` and the icon shows up normally now and the window is associated with the launcher.  

Just wanted to let you know :)

**Comment by mobitar** [comment]
Hmm interesting. Thanks for the update.

**Comment by probonopd** [comment]
See https://github.com/AppImage/AppImageKit/issues/260 which may be related.

![](https://cloud.githubusercontent.com/assets/2480569/19418347/56fcc7a6-93c2-11e6-9665-bad874554c66.gif)

**Comment by OriginalFannibal** [comment]
Whoa! I had no idea this was a documented issue! And great work on the GIF. I struggled so much to explain what exactly was going wrong.

**Comment by probonopd** [comment]
I used the Peek AppImage. Yes, there's an AppImage for that ;-)
