### ISSUE TITLE
[Windows] App remains on TokenVault extension when Autolock engages

### ISSUE THREAD

**Issue by ctp9** [standardnotes/desktop#761]
When Standards Notes is running the "TokenVault" extension and Autolock engages - Standard Notes remains stuck on the TokenVault screen.

Steps to reproduce:

1. Ensure Autolock is enabled (any duration)
2. Open TokenVault editor
3. Minimize Standard Notes while TokenVault is open
4. Maximize Standard Notes after Autolock duration of your choice has engaged
5. You should see that TokenVault remained opened/unlocked and/or blended with the lock screen

**Comment by JaspalSuri** [comment]
Hi @ctp9, thanks for the report; I'll look into this.

**Comment by ctp9** [comment]
Just wondering if we can direct some attention to this issue?

**Comment by moughxyz** [comment]
That's weird. I can't replicate this. Does it happen if you also immediately trigger locking by clicking the lock icon in the bottom right corner? Can you post a screenshot of how the application looks in the final state? I'm curious by what "blended with the lock screen" would mean..

**Comment by ctp9** [comment]
Sorry for taking a while to reply. I was testing this issue and I'm happy to report that the last few releases have fixed this issue. None of what I described earlier is happening anymore. I tested it thoroughly with the last four builds and could no longer reproduce anything from my initial report.

**Comment by ctp9** [comment]
Sorry for taking a while to reply. I was testing this issue and I'm happy to report that the last few releases have fixed this issue. None of what I described earlier is happening anymore. I tested it thoroughly with the last four builds and could no longer reproduce anything from my initial report.
