### ISSUE TITLE
Zoom configuration is saved, but doesn't initialize with the correct saved configuration

### ISSUE THREAD

**Issue by sucrose** [standardnotes/desktop#77]
It seems that the Zoom configuration that I've set is being saved when exiting the application, but upon re-opening the application it is initialized with the 100% scale / Actual Size configuration. If you then change the configuration by Zooming In or Out it will change based on the saved configuration.

To reproduce:
1. Open the application and Zoom Out
2. Exit the application
3. Re-open the application (you'll notice it's back to 100% scale / Actual Size)
4. Zoom Out again and you'll now notice that it has skipped 2 scale steps

**Comment by mobitar** [comment]
I've just tested with 2.1.25 and am not seeing this issue. Zoom saving seems to be working properly.
