### ISSUE TITLE
Synching problem after duplicating a note with the «Action bar» button

### ISSUE THREAD

**Issue by ErikConstant** [standardnotes/desktop#78]
Everytime I duplicate a note and then modify the duplucate note, a synching error pop. After that, all modifications done to any notes are not synching with the server(just localy) until I delete the duplicate and reload(refresh) the app. It seems impossible to generate a duplicated note without breaking the synching process.

![image](https://user-images.githubusercontent.com/29755795/27644712-390d3c32-5bf2-11e7-9822-0bfa1a815ff7.png)

Just want you to know and help your project.
Thanks for the work. I appreciate and enjoy very much your project.

**Comment by mobitar** [comment]
This issue should be fixed now.
