### ISSUE TITLE
long Note Title text and text "All changes saved" text stacked/overlap

### ISSUE THREAD

**Issue by erlangp** [standardnotes/desktop#80]
long Note Title text and text "All changes saved" text stacked/overlap

**Comment by erlangp** [comment]
screenshot: http://imgur.com/a/rMQIq

**Comment by mobitar** [comment]
Good catch, thanks.

**Comment by erlangp** [comment]
will it moved to other position to make clean design? i'm waiting for patch :D

**Comment by mobitar** [comment]
I'll just modify the width of the title so it doesn't overlap. Haven't had a chance to fix this yet though.

**Comment by erlangp** [comment]
great 👍

**Comment by mobitar** [comment]
This has been fixed in v1.2.5.
