### ISSUE TITLE
CloudLink not displaying on MacOS since upgrade to 3.9.11

### ISSUE THREAD

**Issue by jonhadfield** [standardnotes/desktop#804]
MacOS 11.6.1
Standard Notes Desktop App: Version 3.9.11 (3.9.11)

After upgrade from 3.9.10 to 3.9.11 the following is shown when navigating to the menu and then CloudLink. The same is happening on two different laptops: one on Big Sur and the other on Monterey.
![image](https://user-images.githubusercontent.com/843944/148042730-ecee4e2d-3eb0-4e27-8705-4dd65d4cf8ac.png)

A log out from Standard Notes and then log back in does not resolve the issue.

If I login into https://app.standardnotes.com (showing as using 3.9.11 also), the CloudLink menu loads correctly. If it helps, it mentions version 1.2.3 of that extension is installed.

**Comment by moughxyz** [comment]
This will be fixed in the production release of 3.9.11 👍
