### ISSUE TITLE
support RTL

### ISSUE THREAD

**Issue by Monirzadeh** [standardnotes/desktop#81]
hi
please add a Right to left alignment for RTL language.

**Comment by mobitar** [comment]
Does that not work? Can you attach a screenshot?

**Comment by Monirzadeh** [comment]
![note](https://user-images.githubusercontent.com/25131576/28476813-a8967826-6e66-11e7-9add-535b7ef879d3.png)
I attached another shot from Gedit that has true direction and a good font 
![note](https://user-images.githubusercontent.com/25131576/28476983-5579c980-6e67-11e7-8a77-5698f0acb34a.png)

**Comment by AmirHosseinKarimi** [comment]
Is here any news about right to left support?

**Comment by mobitar** [comment]
Sorry haven't had a chance yet :/ Hope to get to it soon.

**Comment by mobitar** [comment]
RTL is now available as of version 2.0.2. https://github.com/standardnotes/desktop/releases
