### ISSUE TITLE
After updating to v3.9.14 on windows (desktop) I am having White Screen on the selected note

### ISSUE THREAD

**Issue by vedant64** [standardnotes/desktop#810]
![unknown (1)](https://user-images.githubusercontent.com/17106428/149275026-c9022b57-1dbc-48a8-afff-b12f1931d9b9.png)

The selected note or even my I hover my house over the notes in the "All Notes" section, the note goes all white. Never happened anything like this before. I tried restarting the windows but had no luck.

**Comment by stefan-yas** [comment]
Hey @vedant64, which theme are you using? Couldn't replicate your issue with the default themes.

**Comment by primu5** [comment]
Facing the same issue.
Using a custom theme at below repo
https://github.com/primu5/Dark-Theme-SN

![image](https://user-images.githubusercontent.com/66946937/149303259-27c14151-0bca-49bd-a8fd-b96eec97cecc.png)

**Comment by stefan-yas** [comment]
Please notify the theme's developer - we can't guarantee third-party themes working with latest updates.

**Comment by primu5** [comment]
For all Theme Devs. This is the tag responsible for highlighting the selected Note.

`--sn-stylekit-grey-5`

This tag fixes the note highlight.
![image](https://user-images.githubusercontent.com/66946937/149312804-8643a3a0-ab06-4aca-ad59-e1f59362b7ef.png)

**Comment by primu5** [comment]
@vedant64 you can use this theme, I have fixed it to be compatible with the current update.

`https://github.com/primu5/Dark-Theme-SN`

**Comment by vedant64** [comment]
Thank You
