### ISSUE TITLE
No snap version 3.9.14?

### ISSUE THREAD

**Issue by CdtDelta** [standardnotes/desktop#811]
Hello,
There wasn't a snap release listed in the latest 3.9.14 release listing. I just wanted to ask if that was an oversight or if snap versions will no longer be provided.

Thanks...

**Comment by johnny243** [comment]
Hi @CdtDelta,

The `snap` package for 3.9.14 should now be listed: https://github.com/standardnotes/desktop/releases/tag/v3.9.14

You can download 3.9.14 via the Snap store as well

**Comment by CdtDelta** [comment]
Got it, just wanted to check before I did anything else (I normally just download it from GitHub vs Snap Store).
