### ISSUE TITLE
Initial screen options not clickable

### ISSUE THREAD

**Issue by ghost** [standardnotes/desktop#812]
I've just installed ubuntu's latest version and standardnotes via snap as usual.

With the last update, the two buttons on the first screen: "use password manager or local storage" are no longer clickable.

**Comment by moughxyz** [comment]
What version? There have been a few recent updates.

**Comment by infosisio** [comment]
Standard Notes 3.9.13, Ubuntu 21.10

**Comment by moughxyz** [comment]
Can you try 3.9.15?

**Comment by infosisio** [comment]
That doesn't seem to be available on the snap store. 

I granted those permissions manually but wanted to report the issue so that it can get fixed.

**Comment by infosisio** [comment]
@moughxyz I just saw that the snap store entry was just updated and tested it, in order to help. Unfortunately the issue persists.

**Comment by lazycalcium** [comment]
Hello, I'd like to add that I am experiencing this same issue and therefore cannot use the snap version of the application. I am on the latest version of ubuntu (21.10) and Standard Notes version 3.9.15

**Comment by infosisio** [comment]
@lazycalcium You could grant those permissions manually until it gets fixed. If you click show more it will give you the snap command to grant it permissions to use the password manager.

**Comment by infosisio** [comment]
@moughxyz Unfortunately a few releases down the road and the issue still persists.

**Comment by moughxyz** [comment]
No one on our team has been able to replicate this. If you're down to screen share with me so I can take a look please DM me on Slack or Discord.

**Comment by infosisio** [comment]
@moughxyz The issue has been fixed with the latest release.

**Comment by lazycalcium** [comment]
Thanks to the devs for fixing this issue! And thanks @infosisio for your notice, I just tested it and its fixed on my end as well on the latest release.
