### ISSUE TITLE
Duplicate on Action Bar no longer works

### ISSUE THREAD

**Issue by onlinemumie** [standardnotes/desktop#816]
Duplicate on Action Bar no longer works. I've tried on Standard Notes desktop and web, on both Windows 10 and Linux.

**Comment by stefan-yas** [comment]
Hey @onlinemumie, Action Bar as it is now is going to be deprecated as we modernize the UI a bit. You can now duplicate notes by right-clicking on a note and selecting "Duplicate".

**Comment by onlinemumie** [comment]
Right. Didn't see that. Very good. Quicker to do it the new way.
