### ISSUE TITLE
Secure Spreadsheet Editor: Merged Cells ignore background color

### ISSUE THREAD

**Issue by SuppenGeist** [standardnotes/desktop#819]
**Afftected Version:** 3.9.20

**Reproduction steps:**

1. Open spreadsheet editor
2. Merge 2 or more cells
3. Give the merged cell a background color

The merged cell now seems to have a small border in the selected color, but the background itself is unaffected

**Expected behavior:**
The background color should be applied correcly.

In the image: The cell containing "Fixkosten" should have a background color.
![image](https://user-images.githubusercontent.com/10869751/150674687-5ac4a9b9-5639-4426-a063-20bfe6235a7a.png)

**Additional Notes**

- Normal (not merged) cells still apply the background color correctly
- The web app might also be affected but I didnt try that out

**Comment by stefan-yas** [comment]
Thanks @SuppenGeist, I've successfully replicated your issue. We'll be looking into a fix for this soon.

**Comment by SuppenGeist** [comment]
This seems to be fixed with version 3.10.0. Thank you!
