### ISSUE TITLE
change default font

### ISSUE THREAD

**Issue by Monirzadeh** [standardnotes/desktop#82]
the default font for Persian or Arabic language is so bad
please add an option that user can change the font.

**Comment by mobitar** [comment]
Hey @Monirzadeh, can you attach a screenshot of how the font looks? It should just use the system font.

**Comment by Monirzadeh** [comment]
this is a screenshot from standardnotes
![note](https://user-images.githubusercontent.com/25131576/28477174-14ed29d8-6e68-11e7-9729-dbdfbe881bca.png)

we have some great font like 
IranianSans: https://github.com/nvdnkpr/Iranian-font-family
pfont: https://github.com/pfont/pfont
vazir font : https://github.com/rastikerdar/vazir-font
Samim font : https://github.com/rastikerdar/samim-font
below shot is Iranian sans Fonts
![note2](https://user-images.githubusercontent.com/25131576/28477141-f50b16fc-6e67-11e7-978b-f7aa2af29011.png)
if I have an option for change default font it can be so much easier

**Comment by mobitar** [comment]
Does this only happen on the Desktop app? Or web app as well?
