### ISSUE TITLE
Editor indicator icon takes up too much space

### ISSUE THREAD

**Issue by quartertone** [standardnotes/desktop#822]
Desptop app version: 3.9.20
(Linux)

Editor indicator icon is a nice idea, but it takes up precious space that could be used to display more of the title/first line. Also, nearly all my notes use the Plain Editor, so this feature is not that useful and kind of distracting. I propose one or some of:

- implement an option to hide the editor icon
- make it a transparent element that sits behind the title text
- no icon if "Plain Editor" is being used

**Comment by moughxyz** [comment]
https://github.com/standardnotes/web/issues/817

**Comment by quartertone** [comment]
> 

Aha! forgot about that option menu. It's hidden so nicely.
