### ISSUE TITLE
[Bug][3.10.0-beta.1] Auto lock screen broken

### ISSUE THREAD

**Issue by B1773rm4n** [standardnotes/desktop#825]
OS: Win11
Version: 3.10.0-beta.1
Enabled extensions: VS Code Theme
Type: Bug
Subscription: None
Settings: Use system color scheme: false

What happened:
I'm using the fresh beta update. After 5 minutes when the auto lock should start the window froze, turned off the dark theme (all became regular white) and the window doesn't respond to clicks

I can hover around in the application and the application will highlight what I am hovering over,  but it won't react to clicks. Only the header bar with files/help/etc react to clicks.
The content of the notes is still visible.No password prompt is appearing

After closing the application regularly it starts normally but without the VS Code Theme (starts in white instead of dark). App is responsive again. It asks for the passcode in dark mode. After entering the passcode the application is still in dark mode. After doing the first click it jumps into white mode again while still being responsive. Theme can be changed to dark mode again

I tested again with a 1 minute locking timer and it appeared again. Easy to see since it's jumps to the white theme

**Comment by moughxyz** [comment]
Can replicate, thanks.

**Comment by B1773rm4n** [comment]
Verison: 3.10.0-beta.2
Theme: VS Code Theme
Settings:
Use color scheme: true
Automatic Light Theme: VS Code Theme
Automatic Dark Theme: VS Code Theme

It locks correctly now
But it instantly jumps into whitemode after locking. So the lockscreen is white.   
Funnily after unlocking it becomes dark for 1 second and then jumps back to whitemode and stays like this until I change the theme in the options

**Comment by B1773rm4n** [comment]
Plus under certain (unknown circumstances) it still can lock up in the old way.
It happens rarely now. Most of the time the client stays in light mode. Right now it's not feasable for me to change to dark mode every unlock.

**Comment by moughxyz** [comment]
> But it instantly jumps into whitemode after locking

Good catch, can replicate, thanks 👍

**Comment by B1773rm4n** [comment]
Both issues (blocking, theme) seems to be fixed with 3.10.0-beta.3
