### ISSUE TITLE
No dark mode

### ISSUE THREAD

**Issue by H3n-beep** [standardnotes/desktop#827]
for the appimage the dark mode is behind a paywall and such a simple feature should be available

**Comment by stefan-yas** [comment]
Theming is something Standard Notes have worked on quite extensively to bring the best experience to our users. To support the efforts of development, as well as future development, we've decided for theming to be a paid feature. Standard Notes, however, does allow third-party extensions, so you may use third-party built custom themes on a free plan, or [feel free to build a custom theme yourself](https://docs.standardnotes.com/extensions/themes/).

**Comment by H3n-beep** [comment]
Ok i understand
