### ISSUE TITLE
Cannot properly use theme extension in latest update

### ISSUE THREAD

**Issue by accountforprivacy** [standardnotes/desktop#833]
Hello, I have been using a custom theme installed as an extension (a dark theme).

In the latest release, whenever the desktop app starts, it would switch back to the default light theme. (But the preference shows that the custom theme is selected). 

This goes away after I selected a different theme and then back to the custom one. But the issue persists on each start up.

This occurs on both Mac and Linux. I also tried forcing the app to always use the custom theme regardless of the system’s light/dark mode. But the issue persists.

Server side problem can be ruled out as this issue doesn’t occur when I revert back to an older release of the desktop app.

Thank you so much!

**Comment by moughxyz** [comment]
This will be fixed in next release, 3.10.1.

**Comment by moughxyz** [comment]
Fixed in 3.11: https://github.com/standardnotes/desktop/releases/tag/v3.11.0
