### ISSUE TITLE
Can't remove items from Folder View

### ISSUE THREAD

**Issue by nickAtWybar** [standardnotes/desktop#84]
With the 'folder' extension installed, there does not appear to be a way to remove the folder from the Standard Notes Windows desktop GUI.

When attempting to delete the last note in the folder (or #tag), that folder re-populates with "New Note 1", leaving the tag/folder non empty.

Does this have to be removed from the database instead of GUI?

**Comment by mobitar** [comment]
I'm not following. Are you trying to delete a folder? A folder will not be deleted automatically once its contents are empty. Instead, you'll have to drag and drop the folder onto the trash at the bottom of the pane.

**Comment by nickAtWybar** [comment]
Thank you for pointing there is a 'trash' item. In my installation, as I have just found out, there is a floating 'Trash' in light grey in behind one of the folders I had created. Not sure why it is floating there - this is the first time I've noticed it. Dragging into there deleted the item, so thanks for the suggestion.

As for the floating 'Trash', perhaps that is a very small issue worth considering.
![capture](https://user-images.githubusercontent.com/6332337/28986441-3fa29b60-7924-11e7-9dde-18c260490592.JPG)

**Comment by wittjosiah** [comment]
Can confirm that the trash seems to be floating behind folders.

<img width="177" alt="screen shot 2017-08-10 at 12 53 07 pm" src="https://user-images.githubusercontent.com/4529818/29181916-e5ed028a-7dca-11e7-9888-2798859a37d0.png">

When scrolled to the top it sits at the bottom of the sidebar but it stays behind the same folders as I scroll.

**Comment by mobitar** [comment]
Should be much improved in recent versions.
