### ISSUE TITLE
Clicking on Account Settings / Account / Subscription / Manage subscription does nothing in 3.12.0 desktop on Ubuntu 20.04

### ISSUE THREAD

**Issue by fury182** [standardnotes/desktop#841]
Clicking on Account Settings / Account / Subscription / Manage subscription does nothing in 3.12.0 desktop on Ubuntu 20.04. I downgraded to 3.11.1 and I was able to click the button and manage my subscription.

**Comment by khlinuxdeveloper** [comment]
I confirm the issue.

_Version in use: 3.12.0 Linux-x86_64 (AppImage)
Operating System: Ubuntu 20.04_

**Comment by moughxyz** [comment]
Sorry about that, this should be fixed in 3.12.1.
