### ISSUE TITLE
Add sinchronization delay

### ISSUE THREAD

**Issue by lzambarda** [standardnotes/desktop#843]
Hi there,

Great work on SN!
Sometimes my editor stutters and struggles to keep up with what I am typing. I think this may be related to the synchronization background process.

I think it would be helpful to be able to add a synchronization delay to the editor, maybe configurable via the settings. This way it would try to save my changes only if I stop typing for enough time.

**Comment by stefan-yas** [comment]
Hey @lzambarda, thanks for the kind words! Which editor are you using that seems to slow down performance? Turning off spellcheck may improve performance with longer notes. Try turning off spellcheck and let me know if that makes things better for you.
![image](https://user-images.githubusercontent.com/52251483/157569289-c211cc17-d58d-4b77-9c38-cc73c6303430.png)

**Comment by lzambarda** [comment]
Thank you for the prompt reply. Disabling Spellcheck helped, thanks!

(On a side note, just to report it: the editor I've been using is https://github.com/arturolinares/sn-rme but changing the editor made no difference)
