### ISSUE TITLE
Don't clutter the home directory in macOS

### ISSUE THREAD

**Issue by SebDanielsson** [standardnotes/desktop#845]
Please don't clutter our home directories with more directories like Standard Notes Backups. Standard Notes on macOS and Linux should adhere to the basedir spec and store  data in .config, .local, .cache etc if those variables are set.

More info:
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html
https://wiki.archlinux.org/title/XDG_Base_Directory#Support

**Comment by haflaxa** [comment]
Hi @SebDanielsson! SN stores settings and data in default and XDG directories on macOS and Linux ...

- "`~/Library/Application Support/Standard Notes/`"
- "`~/.config/Standard Notes/`"

<br>

For ease of access, the `Standard Notes Backups` directory is created in the home directory by default, but it can easily be relocated from inside SN like so: 

![image](https://user-images.githubusercontent.com/91064300/159784642-96f5fcdf-3e72-428c-894f-0f6f781706a8.png)

<br>

Hope this helps!
