### ISSUE TITLE
AppImage XPCOMGlueLoad error

### ISSUE THREAD

**Issue by makruiten** [standardnotes/desktop#86]
When I click any menu item that should open a website (for example: `Help` -> `Website`), nothing happens. When running the AppImage from the terminal, I get the following error when clicking any of the applicable menu items:

```
XPCOMGlueLoad error for file /usr/lib64/firefox/libxul.so:
/tmp/.mount_U2V3hB/usr/lib/libssl3.so: version `NSS_3.27' not found (required by /usr/lib64/firefox/libxul.so)
Couldn't load XPCOM.
```

This is on Fedora 26.

**Comment by mobitar** [comment]
Thanks for the heads up. I'll take a look at this when I get the chance. I've received this report before I believe for Linux. It doesn't happen on any other platforms.

**Comment by makruiten** [comment]
This seems to be fixed. I'm not sure when, but I'm confident that this issue can be closed. Thanks.
