### ISSUE TITLE
Migrating labels has no effect

### ISSUE THREAD

**Issue by SuppenGeist** [standardnotes/desktop#877]
There is the possibility to migrate folders to the new native folders.
![image](https://user-images.githubusercontent.com/10869751/171905780-cd60533f-82ea-402f-9bd2-bac73ddcaff7.png)

If I press "Migration Available" and then confirm with "Run migration" then nothing happens.

Im on version 3.20.0

**Comment by atmoio** [comment]
The migration looks for tags that have a `.` in it. Try removing dots from your tag names, then running the migration. You could then re-add the dots, though I don't quite recall what the behavior would be then (if it would still prompt for migration).

**Comment by SuppenGeist** [comment]
That worked! Thanks for the fast response.

I already suspected that it had something to do with the dots in my tags. Unfortunatly, if I readd the dots, I am again prompted for migrating the tags.

I use the dots to get my tags in a certain order. So I kind of "need" them. But on the other hand, native support for a custom tag order would be nice, too ;)

Edit: Commas work as well, so I'll just switch from dots to commas :D
