### ISSUE TITLE
Links open in new notes window

### ISSUE THREAD

**Issue by jamesrascal** [standardnotes/desktop#9]
When you click a link from within a note it opens a new note window.

Expected behavior would be to open in default browser on the desktop.

**Comment by mobitar** [comment]
Hmm I can't replicate this. Do you mean clicking a link from the Markdown preview? When I do that, it opens it in the same window and tab (though it should probably open a new tab)

**Comment by jamesrascal** [comment]
[Example](http://i.imgur.com/09bbhKw.gifv)

All links should open in the browser IMO.

**Comment by mobitar** [comment]
Oh I see, you're talking about those links, I thought you were talking about your own links in your content. In that case thanks for the heads up, will get this fixed.

**Comment by mobitar** [comment]
Fixed in latest release: https://github.com/standardnotes/desktop/releases/
