### ISSUE TITLE
Use proportional font for notes

### ISSUE THREAD

**Issue by kslstn** [standardnotes/desktop#90]
Like in the iOS app, a proportional font would be more legible than the currently used monospace font. 

There is research to back this up:
http://journals.sagepub.com/doi/pdf/10.1177/001872088302500303
https://blog.codinghorror.com/comparing-font-legibility/

**Comment by mobitar** [comment]
We could potentially introduce this as an option..or another theme.

**Comment by mobitar** [comment]
Monospace is now an option on desktop.
