### ISSUE TITLE
Add a per note monospace setting 

### ISSUE THREAD

**Issue by kslstn** [standardnotes/desktop#91]
Related to #90: if the notes font is proportional, people relying on monospace fonts may experience issues. A toggle setting for monospace/proportional would solve this.

The default for new notes would be proportional. A user preference setting could be added to change the default to mononspace. Existing notes stay as they are, as to not cause issues of notes that were made to be monospace.

**Comment by mobitar** [comment]
This could be done with an extension similar to the [Action Bar](https://standardnotes.org/extensions/action-bar). It's an interesting idea.
