### ISSUE TITLE
Remember Zoom Level

### ISSUE THREAD

**Issue by joshcjohns** [standardnotes/desktop#94]
Each time the Standard Notes desktop app is started, it defaults to the "Actual Size" zoom level. On my system, this makes the text quite large by default. I always Zoom Out several times, but each time I restart the app, this zoom level is lost and the app defaults back to "Actual Size". It would be very helpful if the desktop app would remember the zoom level that was being used in the previous session.

**Comment by mobitar** [comment]
Hmm good catch. I've made a note to look into this.

**Comment by mobitar** [comment]
I've just tested version 2.1.25 on Mac, and the zoom level is remembered automatically. Anyone seeing something different with 2.1.25?
