### ISSUE TITLE
Add option to open and edit files on the local filesystem?

### ISSUE THREAD

**Issue by ErikBjare** [standardnotes/desktop#95]
Sometimes I find it would be convenient if I could edit files directly in the standard files editor. For example such as when copying from a note to somewhere else. I usually edit two kinds of files: the ones that end up public, and those who don't and instead end up in my private notes (which is Standard Notes).

Haven't developed in Electron much, but I don't expect it to be a lot of work. I might give it a shot if I end up using the desktop client more.

Is there any interest in this from anyone else?

 - [ ] Label as `enhancement`

**Comment by mobitar** [comment]
Do you mean like Atom where you can edit local files? I haven't put much thought into that before, but it sounds like a ridiculous amount of work to get SN adapted for that. It just wasn't made for that. Would be an interesting fork though if you ever decide to put work into it.

**Comment by ErikBjare** [comment]
>but it sounds like a ridiculous amount of work to get SN adapted for that.

Oh really? I wasn't thinking of integrating the local file with SN in any significant way, just being able to quickly open, edit and save to the filesystem directly from the editor. 

In case it really is a lot of work due to the desktop client internals: Don't bother and feel free to close the issue.

**Comment by mobitar** [comment]
It's an interesting idea. Though why would you wanna use the SN editor over say Atom?

**Comment by ErikBjare** [comment]
I tend to use vim, but when editing markdown/prose I sometimes find it nice to have a rich-text markdown mode like offered by the standardnotes desktop client.

**Comment by mobitar** [comment]
This probably won't happen officially, but see here: https://github.com/tannercollin/standardnotes-fs
