### ISSUE TITLE
[Feature Request] Option to hide the menu bar

### ISSUE THREAD

**Issue by lokesh-krishna** [standardnotes/desktop#96]
Could you please consider adding an option to hide the menu bar within the view settings? It could be displayed again by pressing the Alt key. This is standard behavior across many apps (Firefox and Atom to name a few), offering a less cluttered experience and a little extra vertical space.

**Comment by mobitar** [comment]
I suppose a theme could handle this as well. I'll look into add it as a part of the Dynamic theme.

**Comment by OriginalFannibal** [comment]
A theme? Um, just to make sure that you understood which bar I am talking about, this is the one:  

![screenshot from 2017-10-07 05-54-13](https://user-images.githubusercontent.com/20235646/31302986-32f94256-ab24-11e7-9cff-ab56d09265f2.png)

**Comment by mobitar** [comment]
Sorry, thought you were talking about the account bar at the bottom. I'll look into this.
