### ISSUE TITLE
Fonts family and spacing problem: really hard to work with notes for prolonged time periods

### ISSUE THREAD

**Issue by sanchoio** [standardnotes/desktop#97]
Unfortunately, SN's fonts (and spacing) are very difficult to deal with especially on long notes. I'm using Fedora 26 Gnome. I attach 2 screenshots which are speaking for themselves: one is SN's editing and other one is Typora's. Are the any solution to tweak SN font and spacing because it's really hard to work with notes for a prolonged time (and especially if you are short-sighted as I am)?

![screenshot from 2017-10-09 00-01-36](https://user-images.githubusercontent.com/32115115/31325652-30493284-ac85-11e7-8eca-fbd294a31d06.png)
![screenshot from 2017-10-09 00-02-14](https://user-images.githubusercontent.com/32115115/31325651-30484afe-ac85-11e7-8b67-a212c8c0841f.png)

**Comment by sancho-one** [comment]
The same situation is with SN Web, notes are hard to read. Here's Web version screenshot:
![screenshot from 2017-10-09 00-09-03](https://user-images.githubusercontent.com/32115115/31325741-1ca50a9a-ac86-11e7-8666-b15b587a32da.png)

**Comment by sancho-one** [comment]
Here I attach my exported from Typora note as html:

[Note 2017-09-19T00.43.02.zip](https://github.com/standardnotes/desktop/files/1367561/Note.2017-09-19T00.43.02.zip)

**Comment by mobitar** [comment]
Hmm..does it look any better with the Plain editor instead of the Markdown editor? One immediate solution is to press `Ctrl/Cmd` + `+` to increase the page size. This will increase the font size and everything else. I know that's helped a few people before.

Another solution is for us to create a more "typographic" theme that's more suitable for long-term writing (essays, books, etc) vs general "note-taking".

**Comment by sancho-one** [comment]
@mobitar as I have some IT background in my past, I'd like to clarify for myself, by "typographic" theme you mean theme as current midnight, futura, etc. So this "typographic" theme could perfectly work **together** with editors as simple/minimal or advanced markdown, couldn't it?

**Comment by mobitar** [comment]
Well, current themes are focused on colors. By typographic I mean a theme that is focused on fonts and sizes instead. I'd have to check whether it would work with external editors like Markdown. Primarily it will be for the plain text editor.

**Comment by sancho-one** [comment]
Dear @mobitar I've sent you a message to your email address that you've provided in your profile.
