### ISSUE TITLE
Folders component filtering behavior

### ISSUE THREAD

**Issue by sanchoio** [standardnotes/desktop#99]
First of all, sorry if it should have been posted to another place, but I could find Folders component in Extensions page.

As it is beta, I'd like to share my concerns about unexpected and illogical behavior of Folders component as for folder selection. 

How to replicate? If you choose top "All" folder, you get the full list of files within all folders. Nevertheless, if you choose any folder, you'll get only its own files, but never get its subfolders' files. (See attached screenshots)

Expected behavior: Show **both** folder **and** all its subfolders' files.

![screenshot from 2017-10-09 14-22-07](https://user-images.githubusercontent.com/32115115/31355122-9a9d79aa-acfe-11e7-8a95-dff7f89fea2c.png)

![screenshot from 2017-10-09 14-23-23](https://user-images.githubusercontent.com/32115115/31355124-9e67408e-acfe-11e7-8311-0ba6755cd537.png)

**Comment by mobitar** [comment]
Oh that's no good. Thanks for the heads up. Here is the folders component repo btw: https://github.com/sn-extensions/folders-component/issues

**Comment by mobitar** [comment]
This should be fixed in recent versions.
